package jp2;

/* loaded from: classes2.dex */
public enum k {
    CRONET_SOURCE_UNSPECIFIED,
    CRONET_SOURCE_STATICALLY_LINKED,
    CRONET_SOURCE_PLAY_SERVICES,
    CRONET_SOURCE_FALLBACK,
    CRONET_SOURCE_PLATFORM
}
