package i10;

import android.util.Log;
import com.google.gson.reflect.TypeToken;
import com.pinterest.api.model.e40;
import nm.i0;
import nm.o;
import um.c;
import vb0.j;

/* loaded from: classes3.dex */
public final class a extends i0 {

    /* renamed from: a, reason: collision with root package name */
    public final o f70952a;

    /* renamed from: b, reason: collision with root package name */
    public i0 f70953b;

    /* renamed from: c, reason: collision with root package name */
    public i0 f70954c;

    public a(o oVar) {
        this.f70952a = oVar;
    }

    @Override // nm.i0
    public final Object c(um.a aVar) {
        if (aVar.K() == um.b.NULL) {
            aVar.B1();
            return null;
        }
        e40 e40Var = new e40();
        aVar.c();
        while (aVar.hasNext()) {
            String k03 = aVar.k0();
            if (aVar.K() == um.b.NULL) {
                aVar.B1();
            } else {
                k03.getClass();
                int hashCode = k03.hashCode();
                char c13 = 65535;
                if (hashCode != -1221029593) {
                    if (hashCode != 116079) {
                        if (hashCode == 113126854 && k03.equals("width")) {
                            c13 = 2;
                        }
                    } else if (k03.equals("url")) {
                        c13 = 1;
                    }
                } else if (k03.equals("height")) {
                    c13 = 0;
                }
                o oVar = this.f70952a;
                if (c13 == 0) {
                    if (this.f70954c == null) {
                        oVar.getClass();
                        this.f70954c = oVar.g(new TypeToken(Integer.class));
                    }
                    e40Var.g((Integer) this.f70954c.c(aVar));
                } else if (c13 == 1) {
                    if (this.f70953b == null) {
                        oVar.getClass();
                        this.f70953b = oVar.g(new TypeToken(String.class));
                    }
                    e40Var.h((String) this.f70953b.c(aVar));
                } else if (c13 != 2) {
                    Log.d("Plank", "Unmapped property for PinImage: ".concat(k03));
                    aVar.E();
                } else {
                    if (this.f70954c == null) {
                        oVar.getClass();
                        this.f70954c = oVar.g(new TypeToken(Integer.class));
                    }
                    e40Var.j((Integer) this.f70954c.c(aVar));
                }
            }
        }
        aVar.g();
        return e40Var;
    }

    @Override // nm.i0
    public final void e(c cVar, Object obj) {
        j.f125466a.G("TypeAdapters generated by @AutoTypeAdapter can only used for reading.", new Object[0]);
        cVar.m();
    }
}
