package i32;

/* loaded from: classes2.dex */
public final class j {
    public static l a(int i13) {
        switch (i13) {
            case 1:
                return l.NOOP;
            case 30004:
                return l.ANDROID_NAG_INVITER;
            case 30074:
                return l.ANDROID_PINIT_BTN_TOOLTIP;
            case 30075:
                return l.ANDROID_CLICKTHROUGH_BTN_TOOLTIP;
            case 30077:
                return l.ANDROID_FIRST_PIN_TAP_PROMPT;
            case 30081:
                return l.ANDROID_WARM_SEO_NUX_HOMEFEED_INTRO;
            case 30082:
                return l.ANDROID_WARM_SEO_NUX_GIFTWRAP_INTEREST_PICKER;
            case 30093:
                return l.ANDROID_FIRST_BOARD_CREATE;
            case 30098:
                return l.ANDROID_PINIT_BTN_TOOLTIP_RETRIGGER;
            case 500044:
                return l.ANDROID_NOTIFICATION_PIN_CLOSEUP_TOOLTIP;
            case 500071:
                return l.ANDROID_DID_IT_BTN_TOOLTIP;
            case 500076:
                return l.ANDROID_DONE_PIN_TOAST;
            case 500078:
                return l.ANDROID_FIRST_TRIED_SCROLL_PROMPT;
            case 500115:
                return l.ANDROID_USM_REPIN_UPSELL_AFTER_CLICKTHROUGH;
            case 500134:
                return l.ANDROID_USM_BOARD_CREATE_UPSELL_SEARCH_SCROLL;
            case 500139:
                return l.ANDROID_IMAGE_ONLY_PIN_GRID;
            case 500146:
                return l.ANDROID_USM_REPEATED_SEARCH_UPSELL;
            case 500147:
                return l.ANDROID_USM_HIGH_QUALITY_SEARCH_UPSELL;
            case 500187:
                return l.ANDROID_NEWS_HUB_SCROLL_PROMPT;
            case 500202:
                return l.USM_CHRISTMAS_SEARCH_TOOLTIP_UPSELL;
            case 500211:
                return l.ANDROID_LIBRARY_V2_PROMPT;
            case 500241:
                return l.ANDROID_AFFINITY_CIRCLE_EDUCATION;
            case 500250:
                return l.ANDROID_USM_HOMEFEED_PROMPTED_RENUX;
            case 500327:
                return l.ANDROID_TRIED_IT_CREATION_EDUCATION;
            case 500412:
                return l.ANDROID_IN_APP_BRAND_SURVEY;
            case 500474:
                return l.ANDROID_TRIED_IT_REEDUCATION_CLOSEUP_PULSAR;
            case 500550:
                return l.ANDROID_PIN_CLOSEUP_RETRIGGER_CLICKTHROUGH_PULSAR_LFV;
            case 500626:
                return l.ANDROID_RELATED_PINS_UPSELL;
            case 500657:
                return l.HOMEFEED_PFY_OFF_USER_EDUCATION;
            case 500683:
                return l.MOBILE_PRIVACY_AND_TERMS_UPDATED_20180501;
            case 500684:
                return l.MOBILE_PRIVACY_AND_TERMS_UPDATE_20180501;
            case 500703:
                return l.MOBILE_PRIVACY_AND_TERMS_BLOCKING_UPDATE_20180525;
            case 500708:
                return l.ANDROID_SHOPPING_ADS_AUTOSCROLL_EDUCATION;
            case 500730:
                return l.ANDROID_CLOSEUP_SEND_BTN_TOOLTIP;
            case 500770:
                return l.ANDROID_MORE_IDEAS_ON_BOARD_EDUCATION_TOAST;
            case 500900:
                return l.ANDROID_SHARE_AFTER_SCREENSHOT;
            case 500941:
                return l.ANDROID_STELA_STL_UPSELL;
            case 500969:
                return l.ANDROID_IAB_RATE_WEBSITE_TOOLTIP;
            case 501026:
                return l.ANDROID_HOMEFEED_TABS_TOOLTIP;
            case 501048:
                return l.ANDROID_HOMEFEED_TABS_PULSAR;
            case 501141:
                return l.ANDROID_SEARCH_PRODUCT_EDUCATION;
            case 501146:
                return l.ANDROID_HOMEFEED_CONTROL_OVERFLOW_TOOLTIP;
            case 501148:
                return l.ANDROID_CLOSEUP_SEND_BTN_TOOLTIP_RESEND;
            case 501397:
                return l.ANDROID_CLOSEUP_REACTION_TOOLTIP;
            case 501600:
                return l.ANDROID_SAVE_EMAIL_UPDATE;
            case 501661:
                return l.ANDROID_HOMEFEED_BUSINESS_PROMOTE_TRENDING_PIN;
            case 501849:
                return l.ANDROID_SAVE_AFTER_SCREENSHOT;
            case 501992:
                return l.ANDROID_CLOSEUP_REACTION_TOOLTIP_2;
            case 502020:
                return l.ANDROID_CLOSEUP_REACTION_TOOLTIP_3;
            case 502051:
                return l.ANDROID_QUICKSAVE_BOARD_CREATE_EDU;
            case 502054:
                return l.ANDROID_LINKED_BUSINESS_NUX;
            case 502068:
                return l.ANDROID_BOARD_ACTION_GROUP_YOUR_PINS;
            case 502116:
                return l.ANDROID_BOARD_INVITE_EDUCATION_ACTIONUPSELL;
            case 502125:
                return l.ANDROID_BOARD_ACTION_ARCHIVE_BOARD;
            case 502132:
                return l.ANDROID_BOARD_NOTE_CREATE_TOOLTIP;
            case 502133:
                return l.ANDROID_BOARD_NOTE_COMPONENTS_TOOLTIP;
            case 502137:
                return l.ANDROID_QUICKSAVE;
            case 502264:
                return l.ANDROID_ORGANIZE_BOARD_PINS_TOOLTIP;
            case 502336:
                return l.ANDROID_BIZ_HUB_PROFILE_IMAGE_TOOLTIP;
            case 502343:
                return l.ANDROID_BIZ_HUB_BUTTON_PROFILE_TOOLTIP;
            case 502351:
                return l.ANDROID_BOARD_PERMISSIONS_TOOLTIP;
            case 502374:
                return l.ANDROID_SEARCH_OWN_PINS_NAG;
            case 502398:
                return l.ANDROID_INBOX_MESSAGE_NOTIFS_OPT_IN_BANNER;
            case 502399:
                return l.ANDROID_SHARESHEET_MESSAGE_NOTIFS_OPT_IN_BANNER;
            case 502498:
                return l.ANDROID_PIN_STATS_PINNER_INTRO_EDUCATION;
            case 502523:
                return l.ANDROID_BOARD_NOTE_ACTIONS_BY_VERTICAL_TOOLTIP;
            case 502529:
                return l.ANDROID_BOARD_NOTE_TOOL_TOOLTIP;
            case 502533:
                return l.ANDROID_PROFILE_BUSINESS_HUB_ICON_TOOLTIP;
            case 502555:
                return l.ANDROID_HIDE_BOARD_FOLLOW;
            case 502561:
                return l.ANDROID_HOMEFEED_LOCATION_UPSELL;
            case 502606:
                return l.ANDROID_NEWS_HUB_UPSELL_HF_TOOLTIP;
            case 502656:
                return l.ANDROID_BOARD_ACTION_ADD_DATES;
            case 502693:
                return l.ANDROID_BIZ_HUB_ENABLE_PROFILE_MESSAGING;
            case 502694:
                return l.ANDROID_BIZ_HUB_ADD_DESCRIPTION;
            case 502749:
                return l.ANDROID_PIN_CLOSEUP_NOTE_TOOLTIP;
            case 502751:
                return l.ANDROID_PIN_NOTE_FILTER_TOOLTIP;
            case 502780:
                return l.ANDROID_COMMENT_NUDGE_UPSELL_MODAL;
            case 502805:
                return l.ANDROID_OS_PUSH_SETTINGS_PROMPT;
            case 502923:
                return l.ANDROID_CURATED_CONTENT_REMOVAL;
            case 502934:
                return l.ANDROID_BOARD_FAVORITE_BUTTON_TOOLTIP;
            case 502935:
                return l.ANDROID_BOARD_FAVORITE_FILTER_TOOLTIP;
            case 502972:
                return l.ANDROID_OS_PUSH_SETTINGS_PROMPT_V2;
            case 503039:
                return l.ANDROID_GROUP_MY_PINS_ORGANIZE_TOOLTIP;
            case 503116:
                return l.ANDROID_GROUP_BOARD_REACTION_MIGRATION_MODAL;
            case 503189:
                return l.ANDROID_PIN_CLOSEUP_GROUP_BOARD_COMMENTS_MIGRATION_TOOLTIP;
            case 503306:
                return l.ANDROID_CLICKTHROUGH_EDUCATION;
            case 503413:
                return l.ANDROID_EDUCATION_STREAM;
            case 503419:
                return l.ANDROID_SAVE_EDUCATION;
            case 503423:
                return l.ANDROID_FOLLOW_EDUCATION;
            case 503463:
                return l.ANDROID_GROUP_MY_UNORGANIZED_PINS_UPSELL;
            case 503529:
                return l.ANDROID_PROFILE_PRONOUNS_TOOLTIP;
            case 503738:
                return l.ANDROID_MANUAL_FILTERS_EDUCATION_TOOLTIP;
            case 503771:
                return l.IDEA_PIN_SWIPE_TO_RELATED_EDUCATION;
            case 503787:
                return l.ANDROID_CTC_LANDING_PAGE_HIGHLIGHT_UPSELL;
            case 503789:
                return l.ANDROID_CTC_CLOSEUP_HIGHLIGHT_EDUCATION;
            case 503848:
                return l.ANDROID_SHARE_EDUCATION;
            case 503854:
                return l.ANDROID_ALLOW_IDEA_PIN_DOWNLOAD_EDUCATION_TOOLTIP;
            case 503871:
                return l.ANDROID_IDEA_PIN_GESTURE_SWIPE_UP_EDUCATION;
            case 503872:
                return l.ANDROID_IDEA_PIN_SAVE_EDUCATION;
            case 503873:
                return l.ANDROID_IDEA_PIN_FOLLOW_EDUCATION;
            case 504047:
                return l.ANDROID_TAKE_CREATION_TOOLTIP;
            case 504116:
                return l.ANDROID_HOLISTIC_PROFILE_SINGLE_FIELD;
            case 504123:
                return l.ANDROID_SHOPPING_LIST_CONTROLS;
            case 504267:
                return l.ANDROID_ABOUT_DRAWER_TOOLTIP;
            case 504408:
                return l.ANDROID_HOLISTIC_PROFILE_TWO;
            case 504409:
                return l.ANDROID_HOLISTIC_PROFILE_MULTIPLE;
            case 504447:
                return l.ANDROID_DEPRECATE_TILTED_PINS_PROFILE_COVER_TOOLTIP;
            case 504448:
                return l.ANDROID_DEPRECATE_VIDEO_PROFILE_COVER_TOOLTIP;
            case 504449:
                return l.ANDROID_PERSONAL_BOUTIQUE_NUX;
            case 504460:
                return l.ANDROID_CREATOR_REWARDS_SUBMIT_IDEAS_TOOLTIP;
            case 504473:
                return l.ANDROID_PERSONAL_BOUTIQUE_TOOLTIP;
            case 504474:
                return l.ANDROID_MERCHANT_TUNER_TOOLTIP;
            case 504551:
                return l.ANDROID_USER_BIRTHDAY_COLLECTION;
            case 504563:
                return l.ANDROID_IDEA_PIN_CREATION_CAMERA_ASSET_PICKER_ONBOARDING;
            case 504576:
                return l.ANDROID_TV_HOME_ICON_TOOLTIP;
            case 504643:
                return l.ANDROID_CLOSEUP_BUY_BTN_TOOLTIP;
            case 504647:
                return l.ANDROID_IDEA_PIN_POST_SHARE_UPSELL_TOOLTIP;
            case 504816:
                return l.ANDROID_BOUNCED_EMAIL_RECOLLECTION;
            case 504905:
                return l.ANDROID_NOTIFS_PERMISSION;
            case 504923:
                return l.CREATOR_ONBOARDING_LANDING_PAGE_DEEP_LINK;
            case 504985:
                return l.UPSELL_PAID_PARTNERSHIP_LEGAL_PRIVACY_CONSENT;
            case 505011:
                return l.ANDROID_LIVE_PIN_SWIPE_UP_EDUCATION;
            case 505056:
                return l.ANDROID_CREATOR_HUB_UPSELL_TOOLTIP;
            case 505126:
                return l.ANDROID_CREATOR_METRICS_TOAST;
            case 505155:
                return l.ANDROID_LIVE_APPLICATION_UPSELL_BANNER;
            case 505174:
                return l.ANDROID_IDEA_PIN_CREATION_CANVAS_BUTTON_ONBOARDING;
            case 505175:
                return l.ANDROID_LIVE_APPLICATION_UPSELL_LANDING_PAGE_CARD;
            case 505198:
                return l.ANDROID_DSA_HOMEFEED;
            case 505223:
                return l.ANDROID_USER_BIRTHDAY_COLLECTION_EU;
            case 505238:
                return l.ANDROID_DSA_PROFILE;
            case 505378:
                return l.ANDROID_SCE_TEXT_FEATURE_UPSELL;
            case 505379:
                return l.ANDROID_SCE_MUSIC_FEATURE_UPSELL;
            case 505380:
                return l.ANDROID_SCE_STICKERS_FEATURE_UPSELL;
            case 505407:
                return l.ANDROID_FORMAT_AGNOSTIC_CREATED_TAB_TOOLTIP;
            case 505408:
                return l.ANDROID_SCE_ORGANIC_PIN_STATS_ANNOUNCEMENT_MODAL;
            case 505476:
                return l.ANDROID_PIN_CREATION_PINS_TOOLTIP;
            case 505504:
                return l.PRODUCT_HAIRPATTERN_TOOLTIP_ANDROID_ALL_US_2023_STATIC;
            case 505534:
                return l.ANDROID_QUESTION_STICKER_EDUCATION_TOOLTIP;
            case 505576:
                return l.PRODUCT_HAIRPATTERN_AP_ANDROID_ALL_US_2023_STATIC;
            case 505595:
                return l.ANDROID_UAB_UNIFIED_SOCIAL_LONGPRESS_EDUCATION;
            case 505622:
                return l.ANDROID_BOARD_AUTO_ORGANIZE_TOOLTIP;
            case 505639:
                return l.ANDROID_IDEA_PIN_MULTIPAGE_DEPRECATION_EDU;
            case 505765:
                return l.ANDROID_SCE_DRAW_FEATURE_UPSELL;
            case 505781:
                return l.ANDROID_SCE_TEXT_FEATURE_UPSELL_FOR_IMAGE;
            case 505782:
                return l.ANDROID_SCE_TEXT_FEATURE_UPSELL_FOR_VIDEO;
            case 505802:
                return l.ANDROID_PRIVACY_MODAL;
            case 505810:
                return l.ANDROID_RETRIEVAL_HUB_PINS_TAB_TOOLTIP;
            case 505847:
                return l.ANDROID_BOT_CHALLENGE;
            case 505851:
                return l.ANDROID_ACCOUNT_LEVEL_COMMENT_CONTROL;
            case 505977:
                return l.ANDROID_REPIN_ANIMATION_AFTER_SAVE;
            case 506049:
                return l.PROFILE_EVOLUTION_EDU_YOUR_ACCOUNT_ANDROID;
            case 506050:
                return l.PROFILE_EVOLUTION_EDU_PUBLIC_PROFILE_ANDROID;
            case 506074:
                return l.ANDROID_INSTAGRAM_ACCOUNT_CLAIMING_PROFILE_TAKEOVER;
            case 506130:
                return l.GRAD_WALKTHROUGH_SETTINGS_MOMENT_B;
            case 506245:
                return l.ANDROID_COMMENT_PUSH_NOTIFICATION_NUDGE;
            case 506248:
                return l.ANDROID_PIN_STATS_PRODUCT_TAGS_EDUCATION;
            case 506263:
                return l.PROFILE_FIND_SAVED_CONTENT_EDU_ANDROID;
            case 506300:
                return l.ANDROID_POST_REPIN_BOARD_UPSELL;
            case 506302:
                return l.ANDROID_POST_REPIN_BOARD_UPSELL_POST_CREATE;
            case 506314:
                return l.ANDROID_SG_BOARD_VIEW_EDUCATION_UPSELL;
            case 506360:
                return l.ANDROID_CLICK_THROUGH_COMMENT_NUDGE_UPSELL_MODAL;
            case 506420:
                return l.ANDROID_BOARD_PREVIEW_MODAL_ACTION_PROMPT_CORE;
            case 506421:
                return l.ANDROID_BOARD_PREVIEW_MODAL_ACTION_PROMPT;
            case 506422:
                return l.ANDROID_BOARDLESS_PREVIEW_MODAL_ACTION_PROMPT;
            case 506423:
                return l.ANDROID_BOARD_PREVIEW_SHARE_SLIDESHOW_TOOLTIP;
            case 506424:
                return l.ANDROID_BOARD_PREVIEW_SHARE_BOARD_TOOLTIP;
            case 506425:
                return l.ANDROID_BOARD_PREVIEW_INVITE_UPSELL;
            case 506426:
                return l.ANDROID_BOARDLESS_PREVIEW_INVITE_UPSELL;
            case 506481:
                return l.ANDROID_BOARD_PREVIEW_SHARE_SIMPLE_TOOLTIP;
            case 506533:
                return l.ANDROID_MOBILE_FB_RECOVERY_ACCOUNT;
            case 506592:
                return l.ANDROID_BOARD_SHOP_TOOL_TOOLTIP;
            case 506603:
                return l.COLLAGE_COMPOSER_PRESENT_CUTOUT_PICKER;
            case 506628:
                return l.GRAD_WALKTHROUGH_SETTINGS_MOMENT_C;
            case 506629:
                return l.ANDROID_EASY_GIFT_GUIDE_SAVING_UPSELL;
            case 506630:
                return l.ANDROID_HOMEFEED_YOUR_WISHLIST_TOOLTIP;
            case 506794:
                return l.EASY_GIFT_GUIDE_SAVING_MEDIA_MODAL;
            case 506816:
                return l.MP_SAVED_PLAN_FRE;
            case 506850:
                return l.PERFORMANCE_PLUS_GENAI_ACK_MODAL;
            case 506913:
                return l.ANDROID_RETRIEVAL_HUB_COLLAGES_TAB_TOOLTIP;
            case 506927:
                return l.HYBRID_SEARCH_LANDING_TOOLTIP;
            case 506935:
                return l.NRT_AUTO_ORG_UPSELL_MEDIA_MODAL;
            case 506984:
                return l.PROFILE_UPSELL_DISMISS_NRT_AUTO_ORG_TOOLTIP;
            case 506985:
                return l.BOARD_AFTER_AUTO_ORG_TOOLTIP;
            case 506993:
                return l.ANDROID_CLOSEUP_REDESIGN_SAVE_EDUCATION;
            case 506994:
                return l.ANDROID_CLOSEUP_REDESIGN_VISIT_EDUCATION;
            case 506995:
                return l.ANDROID_CLOSEUP_REDESIGN_DOWNLOAD_EDUCATION;
            case 506996:
                return l.ANDROID_CLOSEUP_REDESIGN_SAVE_AFTER_REACTION_EDUCATION;
            case 506997:
                return l.ANDROID_CLOSEUP_REDESIGN_SAVE_AFTER_SHARE_EDUCATION;
            case 506998:
                return l.ANDROID_CLOSEUP_REDESIGN_DOWNLOAD_AFTER_SCREENSHOT_EDUCATION;
            case 507007:
                return l.EU_PERSONALIZED_ADS_PROMPT;
            case 507021:
                return l.AUTO_URL_PARAMETER_UPSELL_BANNER;
            case 507025:
                return l.HOLIDAY_GIFT_GUIDE_QUIZ_SHOP_PROFILE;
            case 507032:
                return l.CATALOGS_OVERVIEW_ADS_CREDIT_UPSELL;
            case 507201:
                return l.CATALOGS_OVERVIEW_GENERIC_ADS_UPSELL;
            case 507207:
                return l.ANDROID_WIDGET_UPSELL;
            case 507249:
                return l.SELLER_MIGRATION_BANNER;
            case 507277:
                return l.SCHOOL_TEEN_PROMPT;
            case 507278:
                return l.CREATIVE_ENHANCEMENTS_EDUCATIONAL_POPOVER;
            case 507307:
                return l.ANDROID_STICKER_COMMENT_TOOLTIP;
            case 507313:
                return l.MP_POINT_ESTIMATES_NUX_TOOLTIP;
            case 507319:
                return l.MP_PERF_PLUS_BANNER;
            case 507342:
                return l.PIN_NOTE_CLOSEUP_DEPRECATION_POPOVER;
            case 507353:
                return l.NRT_AUTO_ORG_UPSELL_MEDIA_MODAL_DOWNLOAD;
            case 507369:
                return l.CONVERSION_INSIGHTS_PURCHASER_METRICS_REMOVAL_BANNER_PRE_LAUNCH;
            case 507370:
                return l.CONVERSION_INSIGHTS_PURCHASER_METRICS_REMOVAL_BANNER_LAUNCH;
            case 507386:
                return l.ANDROID_PIN_OR_SPIN_MVP;
            case 507389:
                return l.SHOPIFY_CHURN_PREVENTION_CREDIT_2025;
            case 507418:
                return l.PINNACLE_AI_TAKEOVER_FRE;
            case 507420:
                return l.PINNACLE_AI_BUTTON_POPOVER;
            case 507421:
                return l.PINNACLE_AI_LOAD_PROMPTS_BUTTON_POPOVER;
            case 507422:
                return l.PINNACLE_AI_AGREEMENT_PANEL;
            case 507491:
                return l.ANDROID_PIN_SHARE_UPSELL_AFTER_REACT;
            case 507502:
                return l.AD_ACCOUNT_SPEND_LIMIT_REACHED;
            case 507503:
                return l.BIZMGR_ADS_SPEND_LIMIT_REACHED;
            case 507524:
                return l.ANDROID_PIN_SHARE_UPSELL_AFTER_LONG_CLICKTHROUGH;
            case 507536:
                return l.ANDROID_PIN_SHARE_UPSELL_AFTER_RABBITHOLE_CLOSEUP;
            case 507575:
                return l.CATALOG_FEED_URGENT_MESSAGES_BANNER;
            default:
                return null;
        }
    }
}
