package i32;

/* loaded from: classes2.dex */
public final class w0 {
    public static y0 a(int i13) {
        switch (i13) {
            case 1:
                return y0.NOOP;
            case 20000:
                return y0.ANDROID_NOOP;
            case 20002:
                return y0.ANDROID_GLOBAL_NAG;
            case 20003:
                return y0.ANDROID_BOARD_TAKEOVER;
            case 20004:
                return y0.ANDROID_USER_PROFILE_TAKEOVER;
            case 20005:
                return y0.ANDROID_PIN_CLOSEUP_TAKEOVER;
            case 20006:
                return y0.ANDROID_MAIN_USER_ED;
            case 20008:
                return y0.ANDROID_HOME_FEED_TAKEOVER;
            case 20009:
                return y0.ANDROID_NETWORK_STORY_NAG;
            case 20014:
                return y0.ANDROID_SHARE_SHEET;
            case 20015:
                return y0.ANDROID_ALL_PINS_VIEW_TAKEOVER;
            case 20016:
                return y0.ANDROID_COMMERCE_CHECKOUT_TAKEOVER;
            case 20019:
                return y0.ANDROID_COMMERCE_CHECKOUT_PAYMENT;
            case 20020:
                return y0.ANDROID_PIN_CLOSEUP_COMMERCE_TAKEOVER;
            case 20021:
                return y0.ANDROID_EXPLORE_TAB_TAKEOVER;
            case 20022:
                return y0.ANDROID_SEARCH_PIN_RESULTS_TAKEOVER;
            case 20023:
                return y0.ANDROID_CATEGORY_PIN_RESULTS_TAKEOVER;
            case 20024:
                return y0.ANDROID_REPIN_DIALOG_TAKEOVER;
            case 60001:
                return y0.ANALYTICS_HOME_TAKEOVER;
            case 60002:
                return y0.ANALYTICS_AUDIENCE_DASHBOARD_TAKEOVER;
            case 60003:
                return y0.ANALYTICS_HOME_HERO;
            case 70001:
                return y0.EMAIL_USER_ED_TIP;
            case 80001:
                return y0.BATCH_NUX_EMAILS;
            case 80002:
                return y0.BATCH_RECOMMENDATION_EMAILS;
            case 80003:
                return y0.BATCH_PUSH_NOTIFICATONS;
            case 80005:
                return y0.BATCH_NETWORK_STORY;
            case 80006:
                return y0.BATCH_TRIGGERED_EMAILS;
            case 110001:
                return y0.HOMEFEED_NEW_USER_STORY;
            case 1000000:
                return y0.ANDROID_PINCLOSEUP_IAB_TAKEOVER;
            case 1000001:
                return y0.ANDROID_INAPP_BROWSER_TAKEOVER;
            case 1000002:
                return y0.ANDROID_MENU_COMMERCE_ICON;
            case 1000003:
                return y0.CLICK_REDIRECT;
            case 1000008:
                return y0.ANDROID_TRIED_IT_SUCCESS;
            case 1000010:
                return y0.ANDROID_PIN_SUCCESS;
            case 1000021:
                return y0.ANDROID_PIN_CLOSEUP_TAKEOVER_AFTER_LIKE;
            case 1000022:
                return y0.ANDROID_PIN_CLOSEUP_TAKEOVER_AFTER_CLICKTHROUGH;
            case 1000027:
                return y0.ANDROID_PIN_GRID_ATTRIBUTION;
            case 1000030:
                return y0.ANDROID_PROMOTED_PIN_CELL_IN_GRID;
            case 1000033:
                return y0.ANDROID_NOTIFICATIONS_TAKEOVER;
            case 1000034:
                return y0.CAMERA_DISCOVERY;
            case 1000039:
                return y0.ANDROID_SEARCH_TYPEAHEAD_TAKEOVER;
            case 1000040:
                return y0.ANDROID_CAMERA_DISCOVERY;
            case 1000042:
                return y0.ANDROID_HOME_FEED_NUX_TAKEOVER;
            case 1000043:
                return y0.ANDROID_HOME_FEED_STORY_TAKEOVER;
            case 1000046:
                return y0.ANDROID_HOME_FEED_TAKEOVER_AFTER_SCROLL;
            case 1000051:
                return y0.ANDROID_NEWS_HUB_FIRST_STORY;
            case 1000058:
                return y0.ANDROID_TRIED_IT_CREATION;
            case 1000059:
                return y0.ANDROID_NEWS_HUB_DETAIL_TAKEOVER;
            case 1000061:
                return y0.HOMEFEED_STORY_SLOT_7;
            case 1000067:
                return y0.BACKEND_RELATED_PINS_CONTENT;
            case 1000075:
                return y0.HIDE_CLOSEUP_FIELDS_FEATURE;
            case 1000079:
                return y0.REMOVE_PIN_SWIPE_FEATURE;
            case 1000083:
                return y0.PIN_CLOSEUP_MORE_LIKE_THIS_BTN_FEATURE;
            case 1000085:
                return y0.PIN_CLOSEUP_HIDE_SHARE_BTN_FEATURE;
            case 1000091:
                return y0.ANDROID_NAVIGATION_TAB_BAR_TITLES;
            case 1000092:
                return y0.ANDROID_NAVIGATION_BAR_STYLES;
            case 1000093:
                return y0.NAV_BAR_AUTOHIDE_FEATURE;
            case 1000097:
                return y0.ANDROID_SECTION_ORGANIZE_TAKEOVER;
            case 1000099:
                return y0.ANDROID_SECTION_REORDER_TAKEOVER;
            case 1000100:
                return y0.ANDROID_SECTION_TAKEOVER;
            case 1000104:
                return y0.ANDROID_FOLLOWING_TAB_TAKEOVER;
            case 1000111:
                return y0.ANDROID_APP_TAKEOVER;
            case 1000113:
                return y0.SHOPPING_ADS_AUTOSCROLL_COUNTER;
            case 1000116:
                return y0.HOMEFEED_HIDE_PIN;
            case 1000119:
                return y0.ANDROID_OWN_BOARD_MORE_IDEAS_TAKEOVER;
            case 1000120:
                return y0.ANDROID_OWN_BOARD_SECTION_MORE_IDEAS_TAKEOVER;
            case 1000124:
                return y0.BOARD_MORE_IDEAS_CARDS;
            case 1000126:
                return y0.ANDROID_OWN_BOARD_YOUR_PINS_TAB;
            case 1000131:
                return y0.ANDROID_PIN_CLOSEUP_TAKEOVER_AFTER_SCREENSHOT;
            case 1000132:
                return y0.ANALYTICS_HEADER_BANNER;
            case 1000136:
                return y0.SEARCH_PINS_FEED_STORY_SLOT_0;
            case 1000139:
                return y0.RELATED_PINS_FEED_STORY;
            case 1000155:
                return y0.HOMEFEED_MORE_IDEAS_HEADER;
            case 1000156:
                return y0.ANDROID_PERSONALIZED_SHOPPING;
            case 1000158:
                return y0.ANDROID_FLASHLIGHT_TAKEOVER;
            case 1000159:
                return y0.ANDROID_NAV_BAR_TAKEOVER;
            case 1000166:
                return y0.HOMEFEED_DYNAMIC_INSERTION_STORY;
            case 1000174:
                return y0.SEARCH_PAGE_CURATION_PRODUCT_UPSELL;
            case 1000187:
                return y0.ANDROID_LENS_TAKEOVER;
            case 1000198:
                return y0.ANDROID_STORY_PIN_GRID_CELL;
            case 1000199:
                return y0.ANDROID_STORY_PIN_CLOSEUP;
            case 1000200:
                return y0.ANDROID_STORY_PIN_CREATION_CLOSEUP;
            case 1000201:
                return y0.ANDROID_STORY_PIN_CREATION_MENU;
            case 1000202:
                return y0.ANDROID_STORY_PIN_CLOSEUP_COVER;
            case 1000203:
                return y0.ANDROID_STORY_PIN_CREATION_CLOSEUP_COVER;
            case 1000204:
                return y0.ANDROID_STORY_PIN_CREATION_MENU_REORDER;
            case 1000207:
                return y0.ANDROID_HOMEFEED_TUNER_BOARDS;
            case 1000214:
                return y0.BOARD_MORE_IDEAS_FEED_STORY;
            case 1000219:
                return y0.INTEREST_FEED_STORY;
            case 1000229:
                return y0.EXPLORE_POSSBILITIES_FEED_STORY;
            case 1000231:
                return y0.ANDROID_EXPLORE_POSSIBILITIES_FEED_TAKEOVER;
            case 1000242:
                return y0.BOARD_FEED_STORY;
            case 1000246:
                return y0.ANDROID_TAKEOVER_AFTER_DOWNLOAD;
            case 1000247:
                return y0.ANDROID_QUICKSAVE;
            case 1000252:
                return y0.ANDROID_BUSINESS_HUB_TAKEOVER;
            case 1000257:
                return y0.ANDROID_BUSINESS_HUB_ACTIVATION_CARDS_MODULE;
            case 1000263:
                return y0.ANDROID_BUSINESS_HUB_RESOURCE_CARDS_MODULE;
            case 1000267:
                return y0.ANDROID_BOARD_NOTE_CLOSEUP;
            case 1000271:
                return y0.ANDROID_INBOX_CONVERSATION_TAKEOVER;
            case 1000272:
                return y0.ANALYTICS_FOOTER_UPSELL;
            case 1000275:
                return y0.ANDROID_BUSINESS_HUB_ACTION_CARDS_MODULE;
            case 1000279:
                return y0.HOMEFEED_MORE_IDEAS_FEED_STORY;
            case 1000280:
                return y0.ANDROID_USER_SETTINGS_TAKEOVER;
            case 1000282:
                return y0.ANDROID_SEARCH_TAB_LANDING_TAKEOVER;
            case 1000283:
                return y0.ANDROID_INBOX_TAKEOVER;
            case 1000286:
                return y0.ANALYTICS_TOP_UPSELL_SECTION;
            case 1000289:
                return y0.ANDROID_ANALYTICS_OVERVIEW_UPSELL;
            case 1000292:
                return y0.ANDROID_SHARESHEET_SEARCHMODAL_TAKEOVER;
            case 1000297:
                return y0.SEARCH_PINS_FEED_STORY;
            case 1000299:
                return y0.ANDROID_BUSINESS_HUB_STORY_PINS_ADOPTION;
            case 1000300:
                return y0.ANDROID_PIN_STATS_TAKEOVER;
            case 1000304:
                return y0.ANDROID_AFTER_COMMENT_LIKE_TAKEOVER;
            case 1000318:
                return y0.ANDROID_BUSINESS_HUB_SINGLE_EDIT_PROFILE_MODULE;
            case 1000330:
                return y0.ANDROID_BOARD_FILTER_ICON;
            case 1000334:
                return y0.ANDROID_BUSINESS_HUB_AFTER_LOAD;
            case 1000341:
                return y0.ANDROID_STORY_PIN_CREATION_TAKEOVER;
            case 1000345:
                return y0.LIVE_SESSIONS_TAB_FEED_STORY;
            case 1000349:
                return y0.ANDROID_STORY_PIN_PUBLISH_TAKEOVER;
            case 1000350:
                return y0.ANDROID_STORY_PIN_EDIT_TAKEOVER;
            case 1000354:
                return y0.ANDROID_STORY_PIN_CREATION_METADATA;
            case 1000355:
                return y0.ANALYTICS_AUDIENCE_INSIGHTS_TAKEOVER;
            case 1000357:
                return y0.ANDROID_IDEA_STREAM_TAKEOVER;
            case 1000364:
                return y0.ANDROID_CALL_TO_CREATE_LANDING_PAGE;
            case 1000366:
                return y0.ANDROID_STORY_PIN_RELATED_CONTENT_TAKEOVER;
            case 1000369:
                return y0.CREATOR_HUB_NEWS_MODULE;
            case 1000371:
                return y0.ANDROID_WATCH_TAB_STREAM_TAKEOVER;
            case 1000373:
                return y0.ANDROID_WATCH_TAB_STREAM_GRID_INDEX_0;
            case 1000377:
                return y0.ANDROID_CREATION_INTERSTITIAL;
            case 1000381:
                return y0.ANDROID_PERSONAL_BOUTIQUE_TAKEOVER;
            case 1000382:
                return y0.ANALYTICS_CONVERSION_INSIGHTS_UPSELL_BANNER;
            case 1000390:
                return y0.ANDROID_IDEA_PIN_TEMPLATE_PICKER;
            case 1000393:
                return y0.ANDROID_CREATOR_REWARDS_CHALLENGE_DETAILS;
            case 1000397:
                return y0.ANDROID_PRODUCT_SEARCH_PAGE_TAKEOVER;
            case 1000398:
                return y0.ANDROID_PROFILES_SEARCH_PAGE_TAKEOVER;
            case 1000399:
                return y0.ANDROID_CLOSEUP_TOPIC_PICKER_MODULE;
            case 1000400:
                return y0.ANDROID_IDEA_PIN_CREATION_CAMERA;
            case 1000401:
                return y0.ANDROID_IDEA_PIN_CREATION_ASSET_PICKER;
            case 1000405:
                return y0.ANDROID_IDEA_PIN_CREATION_ADVANCED_SETTINGS;
            case 1000408:
                return y0.ANDROID_IDEA_PIN_CREATION_FINISHING_TOUCHES;
            case 1000415:
                return y0.CREATION_INSPIRATION_TRENDS;
            case 1000419:
                return y0.ANDROID_PDPPLUS_CLOSEUP_TAKEOVER;
            case 1000420:
                return y0.ANDROID_IDEA_PIN_CREATION_PAGE_EDITOR;
            case 1000422:
                return y0.ANDROID_SURVEY_TAKEOVER;
            case 1000429:
                return y0.ANDROID_CREATOR_ONBOARDING_LANDING_PAGE;
            case 1000437:
                return y0.ANDROID_TV_CLOSEUP_VERTICAL_SCROLL_FEED;
            case 1000439:
                return y0.ANDROID_IDEA_PIN_CREATION_MUSIC_BROWSER;
            case 1000446:
                return y0.ANDROID_TV_LANDING_PAGE_TAKEOVER;
            case 1000448:
                return y0.ANDROID_IDEA_PIN_CREATION_MUSIC_EDITOR;
            case 1000450:
                return y0.ANDROID_IDEA_PIN_CREATION_DRAFTS;
            case 1000453:
                return y0.ANDROID_IDEA_PIN_CREATION_ASPECT_RATIO_EDITOR;
            case 1000459:
                return y0.ANDROID_INBOX_CONVERSATION_TAKEOVER_AFTER_CONTACT_REQ_ACCEPTED;
            case 1000461:
                return y0.ANDROID_SHARESHEET_TAKEOVER;
            case 1000465:
                return y0.ANDROID_ANALYTICS_CONTENT_TYPE_FILTER;
            case 1000472:
                return y0.ANDROID_WATCH_TAB_LIVESTREAM_UNIT;
            case 1000474:
                return y0.ANALYTICS_HOME_TOP_PRODUCT_GROUP_SECTION;
            case 1000475:
                return y0.ANDROID_STORY_PIN_CREATION_QUESTION_STICKER_EDITOR_AFTER_TYPING;
            case 1000493:
                return y0.ANDROID_PIN_CLOSEUP_AFTER_SAVE;
            case 1000496:
                return y0.ANDROID_PROFILE_BOARD_TAB_TAKEOVER;
            case 1000497:
                return y0.ANDROID_PIN_CLOSEUP_AFTER_DOWNLOAD;
            case 1000501:
                return y0.ANDROID_HOME_FEED_AFTER_SAVE;
            case 1000504:
                return y0.ANDROID_SEARCH_RESULTS_AFTER_SAVE;
            case 1000507:
                return y0.COLLAGE_COMPOSER;
            case 1000509:
                return y0.ANDROID_IDEA_PIN_CREATION_VIDEO_EDITOR;
            case 1000524:
                return y0.ANDROID_PIN_CLOSEUP_AFTER_SHOWING_MORE_LIKE_THIS;
            case 1000525:
                return y0.ANDROID_PIN_CLOSEUP_AFTER_SHOWING_RELATED_PINS;
            case 1000529:
                return y0.ANDROID_BOARD_MORE_IDEAS_FEED_AFTER_SAVE;
            case 1000531:
                return y0.ANDROID_TOPIC_LANDING_FEED_AFTER_SAVE;
            case 1000538:
                return y0.ANDROID_HOME_FEED_AFTER_CLICKTHROUGH;
            case 1000539:
                return y0.ANDROID_SEARCH_RESULTS_AFTER_CLICKTHROUGH;
            case 1000545:
                return y0.ANDROID_AD_CLOSEUP_AFTER_SAVE;
            case 1000546:
                return y0.ANDROID_AD_CLOSEUP_AFTER_CLICKTHROUGH;
            case 1000556:
                return y0.ANDROID_AD_CLOSEUP_AFTER_NO_ACTION;
            case 1000557:
                return y0.ANDROID_PIN_CLOSEUP_AFTER_NO_ACTION;
            case 1000561:
                return y0.ANDROID_COMMENT_FEED_TAKEOVER_AFTER_COMMENT_SUBMISSION;
            case 1000579:
                return y0.ANDROID_POST_GIFT_GUIDE_REPIN_TAKEOVER;
            case 1000583:
                return y0.ANDROID_PIN_CLOSEUP_PIN_STATS_TAKEOVER;
            case 1000584:
                return y0.NOTIFICATION_HIGHLIGHT;
            case 1000586:
                return y0.MEDIA_PLANER_SAVED_PLANS;
            case 1000588:
                return y0.ANDROID_HYBRID_SEARCH_RESULTS;
            case 1000591:
                return y0.ANDROID_HOME_FEED_AFTER_SAVE_TO_PROFILE_ON_PREVIOUS_SCREEN;
            case 1000592:
                return y0.ANDROID_BOARD_AFTER_AUTO_ORG;
            case 1000599:
                return y0.ANDROID_PIN_CLOSEUP_AFTER_REACT;
            case 1000600:
                return y0.ANDROID_PIN_CLOSEUP_AFTER_SHARE;
            case 1000601:
                return y0.ANDROID_PIN_CLOSEUP_AFTER_SCREENSHOT;
            case 1000607:
                return y0.ANDROID_COMMENT_FEED_TAKEOVER;
            case 1000608:
                return y0.MEDIA_PLANNER_CREATE_PLAN_SIDEBAR;
            case 1000610:
                return y0.MEDIA_PLANNER_HEADER;
            case 1000611:
                return y0.NOTIFICATION_PUSH;
            case 1000614:
                return y0.ANDROID_HOME_FEED_AFTER_DOWNLOAD;
            case 1000615:
                return y0.ANDROID_SEARCH_RESULTS_AFTER_DOWNLOAD;
            case 1000616:
                return y0.ANDROID_BOARD_AFTER_DOWNLOAD;
            case 1000617:
                return y0.ANDROID_USER_PROFILE_AFTER_DOWNLOAD;
            default:
                return null;
        }
    }
}
