package i32;

import com.pinterest.feature.core.view.RecyclerViewTypes;
import kotlin.NoWhenBranchMatchedException;
import org.jetbrains.annotations.NotNull;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes2.dex */
public final class y0 {
    private static final /* synthetic */ el2.a $ENTRIES;
    private static final /* synthetic */ y0[] $VALUES;

    @NotNull
    public static final w0 Companion;
    public static final y0 NOOP = new y0("NOOP", 0);
    public static final y0 ANDROID_NOOP = new y0("ANDROID_NOOP", 1);
    public static final y0 ANDROID_GLOBAL_NAG = new y0("ANDROID_GLOBAL_NAG", 2);
    public static final y0 ANDROID_BOARD_TAKEOVER = new y0("ANDROID_BOARD_TAKEOVER", 3);
    public static final y0 ANDROID_USER_PROFILE_TAKEOVER = new y0("ANDROID_USER_PROFILE_TAKEOVER", 4);
    public static final y0 ANDROID_PIN_CLOSEUP_TAKEOVER = new y0("ANDROID_PIN_CLOSEUP_TAKEOVER", 5);
    public static final y0 ANDROID_PDPPLUS_CLOSEUP_TAKEOVER = new y0("ANDROID_PDPPLUS_CLOSEUP_TAKEOVER", 6);
    public static final y0 ANDROID_MAIN_USER_ED = new y0("ANDROID_MAIN_USER_ED", 7);
    public static final y0 ANDROID_HOME_FEED_TAKEOVER = new y0("ANDROID_HOME_FEED_TAKEOVER", 8);
    public static final y0 ANDROID_NETWORK_STORY_NAG = new y0("ANDROID_NETWORK_STORY_NAG", 9);
    public static final y0 ANDROID_SHARE_SHEET = new y0("ANDROID_SHARE_SHEET", 10);
    public static final y0 ANDROID_ALL_PINS_VIEW_TAKEOVER = new y0("ANDROID_ALL_PINS_VIEW_TAKEOVER", 11);
    public static final y0 ANDROID_COMMERCE_CHECKOUT_TAKEOVER = new y0("ANDROID_COMMERCE_CHECKOUT_TAKEOVER", 12);
    public static final y0 ANDROID_FLASHLIGHT_TAKEOVER = new y0("ANDROID_FLASHLIGHT_TAKEOVER", 13);
    public static final y0 ANDROID_COMMERCE_CHECKOUT_PAYMENT = new y0("ANDROID_COMMERCE_CHECKOUT_PAYMENT", 14);
    public static final y0 ANDROID_PIN_CLOSEUP_COMMERCE_TAKEOVER = new y0("ANDROID_PIN_CLOSEUP_COMMERCE_TAKEOVER", 15);
    public static final y0 ANDROID_EXPLORE_TAB_TAKEOVER = new y0("ANDROID_EXPLORE_TAB_TAKEOVER", 16);
    public static final y0 ANDROID_SEARCH_PIN_RESULTS_TAKEOVER = new y0("ANDROID_SEARCH_PIN_RESULTS_TAKEOVER", 17);
    public static final y0 ANDROID_CATEGORY_PIN_RESULTS_TAKEOVER = new y0("ANDROID_CATEGORY_PIN_RESULTS_TAKEOVER", 18);
    public static final y0 ANDROID_REPIN_DIALOG_TAKEOVER = new y0("ANDROID_REPIN_DIALOG_TAKEOVER", 19);
    public static final y0 ANDROID_INAPP_BROWSER_TAKEOVER = new y0("ANDROID_INAPP_BROWSER_TAKEOVER", 20);
    public static final y0 ANDROID_PINCLOSEUP_IAB_TAKEOVER = new y0("ANDROID_PINCLOSEUP_IAB_TAKEOVER", 21);
    public static final y0 ANDROID_MENU_COMMERCE_ICON = new y0("ANDROID_MENU_COMMERCE_ICON", 22);
    public static final y0 ANDROID_PIN_SUCCESS = new y0("ANDROID_PIN_SUCCESS", 23);
    public static final y0 ANDROID_PIN_CLOSEUP_TAKEOVER_AFTER_LIKE = new y0("ANDROID_PIN_CLOSEUP_TAKEOVER_AFTER_LIKE", 24);
    public static final y0 ANDROID_PIN_CLOSEUP_TAKEOVER_AFTER_CLICKTHROUGH = new y0("ANDROID_PIN_CLOSEUP_TAKEOVER_AFTER_CLICKTHROUGH", 25);
    public static final y0 ANDROID_NOTIFICATIONS_TAKEOVER = new y0("ANDROID_NOTIFICATIONS_TAKEOVER", 26);
    public static final y0 ANDROID_SEARCH_TYPEAHEAD_TAKEOVER = new y0("ANDROID_SEARCH_TYPEAHEAD_TAKEOVER", 27);
    public static final y0 ANDROID_CAMERA_DISCOVERY = new y0("ANDROID_CAMERA_DISCOVERY", 28);
    public static final y0 ANDROID_HOME_FEED_NUX_TAKEOVER = new y0("ANDROID_HOME_FEED_NUX_TAKEOVER", 29);
    public static final y0 ANDROID_HOME_FEED_STORY_TAKEOVER = new y0("ANDROID_HOME_FEED_STORY_TAKEOVER", 30);
    public static final y0 ANDROID_HOME_FEED_TAKEOVER_AFTER_SCROLL = new y0("ANDROID_HOME_FEED_TAKEOVER_AFTER_SCROLL", 31);
    public static final y0 ANDROID_TRIED_IT_CREATION = new y0("ANDROID_TRIED_IT_CREATION", 32);
    public static final y0 ANDROID_NEWS_HUB_DETAIL_TAKEOVER = new y0("ANDROID_NEWS_HUB_DETAIL_TAKEOVER", 33);
    public static final y0 ANDROID_NAVIGATION_TAB_BAR_TITLES = new y0("ANDROID_NAVIGATION_TAB_BAR_TITLES", 34);
    public static final y0 ANDROID_NAVIGATION_BAR_STYLES = new y0("ANDROID_NAVIGATION_BAR_STYLES", 35);
    public static final y0 ANDROID_APP_TAKEOVER = new y0("ANDROID_APP_TAKEOVER", 36);
    public static final y0 ANDROID_PIN_CLOSEUP_TAKEOVER_AFTER_SCREENSHOT = new y0("ANDROID_PIN_CLOSEUP_TAKEOVER_AFTER_SCREENSHOT", 37);
    public static final y0 ANDROID_NAV_BAR_TAKEOVER = new y0("ANDROID_NAV_BAR_TAKEOVER", 38);
    public static final y0 ANDROID_LENS_TAKEOVER = new y0("ANDROID_LENS_TAKEOVER", 39);
    public static final y0 ANDROID_STORY_PIN_GRID_CELL = new y0("ANDROID_STORY_PIN_GRID_CELL", 40);
    public static final y0 ANDROID_STORY_PIN_CLOSEUP = new y0("ANDROID_STORY_PIN_CLOSEUP", 41);
    public static final y0 ANDROID_STORY_PIN_CREATION_CLOSEUP = new y0("ANDROID_STORY_PIN_CREATION_CLOSEUP", 42);
    public static final y0 ANDROID_STORY_PIN_CREATION_MENU = new y0("ANDROID_STORY_PIN_CREATION_MENU", 43);
    public static final y0 ANDROID_STORY_PIN_CLOSEUP_COVER = new y0("ANDROID_STORY_PIN_CLOSEUP_COVER", 44);
    public static final y0 ANDROID_STORY_PIN_CREATION_CLOSEUP_COVER = new y0("ANDROID_STORY_PIN_CREATION_CLOSEUP_COVER", 45);
    public static final y0 ANDROID_STORY_PIN_CREATION_MENU_REORDER = new y0("ANDROID_STORY_PIN_CREATION_MENU_REORDER", 46);
    public static final y0 ANDROID_TAKEOVER_AFTER_DOWNLOAD = new y0("ANDROID_TAKEOVER_AFTER_DOWNLOAD", 47);
    public static final y0 ANDROID_QUICKSAVE = new y0("ANDROID_QUICKSAVE", 48);
    public static final y0 ANDROID_BOARD_FILTER_ICON = new y0("ANDROID_BOARD_FILTER_ICON", 49);
    public static final y0 ANDROID_BOARD_NOTE_CLOSEUP = new y0("ANDROID_BOARD_NOTE_CLOSEUP", 50);
    public static final y0 ANDROID_SEARCH_TAB_LANDING_TAKEOVER = new y0("ANDROID_SEARCH_TAB_LANDING_TAKEOVER", 51);
    public static final y0 ANDROID_INBOX_TAKEOVER = new y0("ANDROID_INBOX_TAKEOVER", 52);
    public static final y0 ANDROID_SHARESHEET_SEARCHMODAL_TAKEOVER = new y0("ANDROID_SHARESHEET_SEARCHMODAL_TAKEOVER", 53);
    public static final y0 ANDROID_SHARESHEET_TAKEOVER = new y0("ANDROID_SHARESHEET_TAKEOVER", 54);
    public static final y0 ANDROID_STORY_PIN_CREATION_TAKEOVER = new y0("ANDROID_STORY_PIN_CREATION_TAKEOVER", 55);
    public static final y0 ANDROID_STORY_PIN_PUBLISH_TAKEOVER = new y0("ANDROID_STORY_PIN_PUBLISH_TAKEOVER", 56);
    public static final y0 ANDROID_STORY_PIN_EDIT_TAKEOVER = new y0("ANDROID_STORY_PIN_EDIT_TAKEOVER", 57);
    public static final y0 ANDROID_STORY_PIN_CREATION_METADATA = new y0("ANDROID_STORY_PIN_CREATION_METADATA", 58);
    public static final y0 ANDROID_IDEA_STREAM_TAKEOVER = new y0("ANDROID_IDEA_STREAM_TAKEOVER", 59);
    public static final y0 ANDROID_CALL_TO_CREATE_LANDING_PAGE = new y0("ANDROID_CALL_TO_CREATE_LANDING_PAGE", 60);
    public static final y0 ANDROID_WATCH_TAB_STREAM_TAKEOVER = new y0("ANDROID_WATCH_TAB_STREAM_TAKEOVER", 61);
    public static final y0 ANDROID_WATCH_TAB_STREAM_GRID_INDEX_0 = new y0("ANDROID_WATCH_TAB_STREAM_GRID_INDEX_0", 62);
    public static final y0 ANDROID_PERSONAL_BOUTIQUE_TAKEOVER = new y0("ANDROID_PERSONAL_BOUTIQUE_TAKEOVER", 63);
    public static final y0 ANDROID_IDEA_PIN_TEMPLATE_PICKER = new y0("ANDROID_IDEA_PIN_TEMPLATE_PICKER", 64);
    public static final y0 ANDROID_PRODUCT_SEARCH_PAGE_TAKEOVER = new y0("ANDROID_PRODUCT_SEARCH_PAGE_TAKEOVER", 65);
    public static final y0 ANDROID_PROFILES_SEARCH_PAGE_TAKEOVER = new y0("ANDROID_PROFILES_SEARCH_PAGE_TAKEOVER", 66);
    public static final y0 ANDROID_CLOSEUP_TOPIC_PICKER_MODULE = new y0("ANDROID_CLOSEUP_TOPIC_PICKER_MODULE", 67);
    public static final y0 ANDROID_IDEA_PIN_CREATION_CAMERA = new y0("ANDROID_IDEA_PIN_CREATION_CAMERA", 68);
    public static final y0 ANDROID_IDEA_PIN_CREATION_ADVANCED_SETTINGS = new y0("ANDROID_IDEA_PIN_CREATION_ADVANCED_SETTINGS", 69);
    public static final y0 ANDROID_IDEA_PIN_CREATION_FINISHING_TOUCHES = new y0("ANDROID_IDEA_PIN_CREATION_FINISHING_TOUCHES", 70);
    public static final y0 ANDROID_IDEA_PIN_CREATION_PAGE_EDITOR = new y0("ANDROID_IDEA_PIN_CREATION_PAGE_EDITOR", 71);
    public static final y0 ANDROID_IDEA_PIN_CREATION_VIDEO_EDITOR = new y0("ANDROID_IDEA_PIN_CREATION_VIDEO_EDITOR", 72);
    public static final y0 ANDROID_IDEA_PIN_CREATION_MUSIC_BROWSER = new y0("ANDROID_IDEA_PIN_CREATION_MUSIC_BROWSER", 73);
    public static final y0 ANDROID_IDEA_PIN_CREATION_MUSIC_EDITOR = new y0("ANDROID_IDEA_PIN_CREATION_MUSIC_EDITOR", 74);
    public static final y0 ANDROID_CREATOR_ONBOARDING_LANDING_PAGE = new y0("ANDROID_CREATOR_ONBOARDING_LANDING_PAGE", 75);
    public static final y0 ANDROID_IDEA_PIN_CREATION_ASSET_PICKER = new y0("ANDROID_IDEA_PIN_CREATION_ASSET_PICKER", 76);
    public static final y0 ANDROID_TV_CLOSEUP_VERTICAL_SCROLL_FEED = new y0("ANDROID_TV_CLOSEUP_VERTICAL_SCROLL_FEED", 77);
    public static final y0 ANDROID_TV_LANDING_PAGE_TAKEOVER = new y0("ANDROID_TV_LANDING_PAGE_TAKEOVER", 78);
    public static final y0 ANDROID_IDEA_PIN_CREATION_DRAFTS = new y0("ANDROID_IDEA_PIN_CREATION_DRAFTS", 79);
    public static final y0 ANDROID_IDEA_PIN_CREATION_ASPECT_RATIO_EDITOR = new y0("ANDROID_IDEA_PIN_CREATION_ASPECT_RATIO_EDITOR", 80);
    public static final y0 ANDROID_ANALYTICS_CONTENT_TYPE_FILTER = new y0("ANDROID_ANALYTICS_CONTENT_TYPE_FILTER", 81);
    public static final y0 ANDROID_WATCH_TAB_LIVESTREAM_UNIT = new y0("ANDROID_WATCH_TAB_LIVESTREAM_UNIT", 82);
    public static final y0 ANDROID_STORY_PIN_CREATION_QUESTION_STICKER_EDITOR_AFTER_TYPING = new y0("ANDROID_STORY_PIN_CREATION_QUESTION_STICKER_EDITOR_AFTER_TYPING", 83);
    public static final y0 ANDROID_PIN_CLOSEUP_AFTER_SHOWING_MORE_LIKE_THIS = new y0("ANDROID_PIN_CLOSEUP_AFTER_SHOWING_MORE_LIKE_THIS", 84);
    public static final y0 ANDROID_PIN_CLOSEUP_AFTER_SHOWING_RELATED_PINS = new y0("ANDROID_PIN_CLOSEUP_AFTER_SHOWING_RELATED_PINS", 85);
    public static final y0 ANDROID_BOARD_MORE_IDEAS_FEED_AFTER_SAVE = new y0("ANDROID_BOARD_MORE_IDEAS_FEED_AFTER_SAVE", 86);
    public static final y0 ANDROID_TOPIC_LANDING_FEED_AFTER_SAVE = new y0("ANDROID_TOPIC_LANDING_FEED_AFTER_SAVE", 87);
    public static final y0 ANDROID_COMMENT_FEED_TAKEOVER = new y0("ANDROID_COMMENT_FEED_TAKEOVER", 88);
    public static final y0 ANDROID_COMMENT_FEED_TAKEOVER_AFTER_COMMENT_SUBMISSION = new y0("ANDROID_COMMENT_FEED_TAKEOVER_AFTER_COMMENT_SUBMISSION", 89);
    public static final y0 ANDROID_HOME_FEED_AFTER_SAVE_TO_PROFILE_ON_PREVIOUS_SCREEN = new y0("ANDROID_HOME_FEED_AFTER_SAVE_TO_PROFILE_ON_PREVIOUS_SCREEN", 90);
    public static final y0 ANDROID_BOARD_AFTER_AUTO_ORG = new y0("ANDROID_BOARD_AFTER_AUTO_ORG", 91);
    public static final y0 ANALYTICS_HOME_TAKEOVER = new y0("ANALYTICS_HOME_TAKEOVER", 92);
    public static final y0 ANALYTICS_AUDIENCE_DASHBOARD_TAKEOVER = new y0("ANALYTICS_AUDIENCE_DASHBOARD_TAKEOVER", 93);
    public static final y0 ANALYTICS_HOME_HERO = new y0("ANALYTICS_HOME_HERO", 94);
    public static final y0 ANALYTICS_HEADER_BANNER = new y0("ANALYTICS_HEADER_BANNER", 95);
    public static final y0 ANALYTICS_FOOTER_UPSELL = new y0("ANALYTICS_FOOTER_UPSELL", 96);
    public static final y0 ANDROID_ANALYTICS_OVERVIEW_UPSELL = new y0("ANDROID_ANALYTICS_OVERVIEW_UPSELL", 97);
    public static final y0 ANDROID_PIN_STATS_TAKEOVER = new y0("ANDROID_PIN_STATS_TAKEOVER", 98);
    public static final y0 ANALYTICS_AUDIENCE_INSIGHTS_TAKEOVER = new y0("ANALYTICS_AUDIENCE_INSIGHTS_TAKEOVER", 99);
    public static final y0 ANALYTICS_CONVERSION_INSIGHTS_UPSELL_BANNER = new y0("ANALYTICS_CONVERSION_INSIGHTS_UPSELL_BANNER", 100);
    public static final y0 ANALYTICS_HOME_TOP_PRODUCT_GROUP_SECTION = new y0("ANALYTICS_HOME_TOP_PRODUCT_GROUP_SECTION", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_HAIR_PATTERN_QUERIES_MODULE);
    public static final y0 EMAIL_USER_ED_TIP = new y0("EMAIL_USER_ED_TIP", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_SHOPPING_MODULE);
    public static final y0 BATCH_NUX_EMAILS = new y0("BATCH_NUX_EMAILS", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_TEMPLATE_DETAILS_MODULE);
    public static final y0 BATCH_RECOMMENDATION_EMAILS = new y0("BATCH_RECOMMENDATION_EMAILS", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_PEAR_STYLES_MODULE);
    public static final y0 BATCH_PUSH_NOTIFICATONS = new y0("BATCH_PUSH_NOTIFICATONS", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_SEE_IT_STYLED_MODULE);
    public static final y0 BATCH_NETWORK_STORY = new y0("BATCH_NETWORK_STORY", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_PLACEHOLDER_LOADING_GRID);
    public static final y0 BATCH_TRIGGERED_EMAILS = new y0("BATCH_TRIGGERED_EMAILS", RecyclerViewTypes.VIEW_TYPE_PIN_PDP_MONOLITH_HEADER);
    public static final y0 HOMEFEED_NEW_USER_STORY = new y0("HOMEFEED_NEW_USER_STORY", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_STL_SHOPPING_MODULE);
    public static final y0 HOMEFEED_STORY_SLOT_7 = new y0("HOMEFEED_STORY_SLOT_7", RecyclerViewTypes.VIEW_TYPE_LIVE_SINGLE_COLUMN_UPSELL);
    public static final y0 CLICK_REDIRECT = new y0("CLICK_REDIRECT", RecyclerViewTypes.VIEW_TYPE_TV_CATEGORY_PICKER_CAROUSEL);
    public static final y0 ANDROID_TRIED_IT_SUCCESS = new y0("ANDROID_TRIED_IT_SUCCESS", RecyclerViewTypes.VIEW_TYPE_TV_SCHEDULE_EPISODE);
    public static final y0 ANDROID_PIN_GRID_ATTRIBUTION = new y0("ANDROID_PIN_GRID_ATTRIBUTION", RecyclerViewTypes.VIEW_TYPE_TV_CATEGORY_PAGE_HEADER);
    public static final y0 ANDROID_PROMOTED_PIN_CELL_IN_GRID = new y0("ANDROID_PROMOTED_PIN_CELL_IN_GRID", RecyclerViewTypes.VIEW_TYPE_SCHEDULED_PIN_CELL);
    public static final y0 HIDE_CLOSEUP_FIELDS_FEATURE = new y0("HIDE_CLOSEUP_FIELDS_FEATURE", RecyclerViewTypes.VIEW_TYPE_SCHEDULED_PIN_SECTION_HEADER);
    public static final y0 REMOVE_PIN_SWIPE_FEATURE = new y0("REMOVE_PIN_SWIPE_FEATURE", RecyclerViewTypes.VIEW_TYPE_ANNOUNCEMENT_MODAL_TYPE_ONE);
    public static final y0 PIN_CLOSEUP_MORE_LIKE_THIS_BTN_FEATURE = new y0("PIN_CLOSEUP_MORE_LIKE_THIS_BTN_FEATURE", RecyclerViewTypes.VIEW_TYPE_PROFILE_CREATED_TAB_SCHEDULED_PINS_PREVIEW);
    public static final y0 PIN_CLOSEUP_HIDE_SHARE_BTN_FEATURE = new y0("PIN_CLOSEUP_HIDE_SHARE_BTN_FEATURE", RecyclerViewTypes.VIEW_TYPE_CAROUSEL_SINGLE_COLUMN);
    public static final y0 NAV_BAR_AUTOHIDE_FEATURE = new y0("NAV_BAR_AUTOHIDE_FEATURE", RecyclerViewTypes.VIEW_TYPE_SIMPLE_IMAGE_CELL);
    public static final y0 ANDROID_SECTION_ORGANIZE_TAKEOVER = new y0("ANDROID_SECTION_ORGANIZE_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_CAROUSEL_VIDEO_CELL);
    public static final y0 ANDROID_SECTION_REORDER_TAKEOVER = new y0("ANDROID_SECTION_REORDER_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_GRID_CELL);
    public static final y0 ANDROID_SECTION_TAKEOVER = new y0("ANDROID_SECTION_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_VIDEO_GRID_CELL);
    public static final y0 HOMEFEED_HIDE_PIN = new y0("HOMEFEED_HIDE_PIN", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_VIDEO_GRID_CELL_FULL_SPAN);
    public static final y0 SEARCH_PINS_FEED_STORY_SLOT_0 = new y0("SEARCH_PINS_FEED_STORY_SLOT_0", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_CAROUSEL);
    public static final y0 SEARCH_PINS_FEED_STORY = new y0("SEARCH_PINS_FEED_STORY", RecyclerViewTypes.VIEW_TYPE_STORY_BOARD_IDEAS_PREVIEW_FOOTER);
    public static final y0 RELATED_PINS_FEED_STORY = new y0("RELATED_PINS_FEED_STORY", RecyclerViewTypes.VIEW_TYPE_STORY_BOARD_IDEAS_PREVIEW_DETAILED);
    public static final y0 HOMEFEED_DYNAMIC_INSERTION_STORY = new y0("HOMEFEED_DYNAMIC_INSERTION_STORY", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_GRID_CELL);
    public static final y0 ANALYTICS_TOP_UPSELL_SECTION = new y0("ANALYTICS_TOP_UPSELL_SECTION", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK);
    public static final y0 LIVE_SESSIONS_TAB_FEED_STORY = new y0("LIVE_SESSIONS_TAB_FEED_STORY", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK_FULL_SPAN);
    public static final y0 ANDROID_FOLLOWING_TAB_TAKEOVER = new y0("ANDROID_FOLLOWING_TAB_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK_SHOW_GRID_ACTIONS);
    public static final y0 CAMERA_DISCOVERY = new y0("CAMERA_DISCOVERY", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK_SHOW_GRID_ACTIONS_FULL_SPAN);
    public static final y0 BACKEND_RELATED_PINS_CONTENT = new y0("BACKEND_RELATED_PINS_CONTENT", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_VIDEO_GRID_CELL);
    public static final y0 SHOPPING_ADS_AUTOSCROLL_COUNTER = new y0("SHOPPING_ADS_AUTOSCROLL_COUNTER", RecyclerViewTypes.VIEW_TYPE_FEED_SECTION_TITLE);
    public static final y0 ANDROID_OWN_BOARD_MORE_IDEAS_TAKEOVER = new y0("ANDROID_OWN_BOARD_MORE_IDEAS_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_PIN_CAROUSEL);
    public static final y0 ANDROID_OWN_BOARD_SECTION_MORE_IDEAS_TAKEOVER = new y0("ANDROID_OWN_BOARD_SECTION_MORE_IDEAS_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_PIN_MINI_CELL);
    public static final y0 BOARD_MORE_IDEAS_CARDS = new y0("BOARD_MORE_IDEAS_CARDS", RecyclerViewTypes.VIEW_TYPE_FIXED_SIZE_PIN_CELL);
    public static final y0 ANDROID_OWN_BOARD_YOUR_PINS_TAB = new y0("ANDROID_OWN_BOARD_YOUR_PINS_TAB", RecyclerViewTypes.VIEW_TYPE_SEE_MORE_ACTION_CELL);
    public static final y0 HOMEFEED_MORE_IDEAS_HEADER = new y0("HOMEFEED_MORE_IDEAS_HEADER", RecyclerViewTypes.VIEW_TYPE_FIXED_SIZE_PIN_IMAGE);
    public static final y0 SEARCH_PAGE_CURATION_PRODUCT_UPSELL = new y0("SEARCH_PAGE_CURATION_PRODUCT_UPSELL", RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL);
    public static final y0 BOARD_MORE_IDEAS_FEED_STORY = new y0("BOARD_MORE_IDEAS_FEED_STORY", RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL_ITEM);
    public static final y0 INTEREST_FEED_STORY = new y0("INTEREST_FEED_STORY", RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL_ACTION_ITEM);
    public static final y0 ANDROID_EXPLORE_POSSIBILITIES_FEED_TAKEOVER = new y0("ANDROID_EXPLORE_POSSIBILITIES_FEED_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL_ITEM_HIDDEN);
    public static final y0 EXPLORE_POSSBILITIES_FEED_STORY = new y0("EXPLORE_POSSBILITIES_FEED_STORY", RecyclerViewTypes.VIEW_TYPE_ARTICLE_CAROUSEL);
    public static final y0 BOARD_FEED_STORY = new y0("BOARD_FEED_STORY", RecyclerViewTypes.VIEW_TYPE_ARTICLE_CAROUSEL_ITEM_IMAGE);
    public static final y0 HOMEFEED_MORE_IDEAS_FEED_STORY = new y0("HOMEFEED_MORE_IDEAS_FEED_STORY", RecyclerViewTypes.VIEW_TYPE_VTO_CAROUSEL_ITEM);
    public static final y0 ANDROID_PERSONALIZED_SHOPPING = new y0("ANDROID_PERSONALIZED_SHOPPING", RecyclerViewTypes.VIEW_TYPE_VTO_CAROUSEL_ITEM_TINTED);
    public static final y0 ANDROID_HOMEFEED_TUNER_BOARDS = new y0("ANDROID_HOMEFEED_TUNER_BOARDS", RecyclerViewTypes.VIEW_TYPE_ARTICLE_CAROUSEL_ITEM_VIDEO);
    public static final y0 ANDROID_BUSINESS_HUB_TAKEOVER = new y0("ANDROID_BUSINESS_HUB_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_SEARCH_PRODUCT_COLLAGE_STORY);
    public static final y0 ANDROID_BUSINESS_HUB_ACTIVATION_CARDS_MODULE = new y0("ANDROID_BUSINESS_HUB_ACTIVATION_CARDS_MODULE", RecyclerViewTypes.VIEW_TYPE_SHOPPING_BUBBLES_PACKAGE_GRID_MODULE);
    public static final y0 ANDROID_BUSINESS_HUB_RESOURCE_CARDS_MODULE = new y0("ANDROID_BUSINESS_HUB_RESOURCE_CARDS_MODULE", RecyclerViewTypes.VIEW_TYPE_SHOPPING_BRAND_PACKAGE_GRID_MODULE);
    public static final y0 ANDROID_BUSINESS_HUB_ACTION_CARDS_MODULE = new y0("ANDROID_BUSINESS_HUB_ACTION_CARDS_MODULE", RecyclerViewTypes.VIEW_TYPE_SHOPPING_CATEGORY);
    public static final y0 ANDROID_BUSINESS_HUB_STORY_PINS_ADOPTION = new y0("ANDROID_BUSINESS_HUB_STORY_PINS_ADOPTION", RecyclerViewTypes.VIEW_TYPE_SHOPPING_UNIFIED_FILTER_MULTI_SELECT_ITEM);
    public static final y0 ANDROID_BUSINESS_HUB_SINGLE_EDIT_PROFILE_MODULE = new y0("ANDROID_BUSINESS_HUB_SINGLE_EDIT_PROFILE_MODULE", RecyclerViewTypes.VIEW_TYPE_SHOPPING_PRICE_FILTER_ITEM);
    public static final y0 ANDROID_BUSINESS_HUB_AFTER_LOAD = new y0("ANDROID_BUSINESS_HUB_AFTER_LOAD", RecyclerViewTypes.VIEW_TYPE_STANDARD_FILTER_ITEM);
    public static final y0 ANDROID_NEWS_HUB_FIRST_STORY = new y0("ANDROID_NEWS_HUB_FIRST_STORY", RecyclerViewTypes.VIEW_TYPE_SHOPPING_PRODUCT_FILTER_HEADER);
    public static final y0 ANDROID_INBOX_CONVERSATION_TAKEOVER = new y0("ANDROID_INBOX_CONVERSATION_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_SHOPPING_COLOR_FILTER);
    public static final y0 ANDROID_INBOX_CONVERSATION_TAKEOVER_AFTER_CONTACT_REQ_ACCEPTED = new y0("ANDROID_INBOX_CONVERSATION_TAKEOVER_AFTER_CONTACT_REQ_ACCEPTED", RecyclerViewTypes.VIEW_TYPE_SHOPPING_CATEGORY_FILTER_ITEM);
    public static final y0 ANDROID_USER_SETTINGS_TAKEOVER = new y0("ANDROID_USER_SETTINGS_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_SHOPPING_SORT_FILTER);
    public static final y0 ANDROID_AFTER_COMMENT_LIKE_TAKEOVER = new y0("ANDROID_AFTER_COMMENT_LIKE_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_STELA_IN_FLASHLIGHT_ONE_COLUMN);
    public static final y0 ANDROID_STORY_PIN_RELATED_CONTENT_TAKEOVER = new y0("ANDROID_STORY_PIN_RELATED_CONTENT_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_EDUCATION_HEADER);
    public static final y0 CREATOR_HUB_NEWS_MODULE = new y0("CREATOR_HUB_NEWS_MODULE", 160);
    public static final y0 ANDROID_CREATION_INTERSTITIAL = new y0("ANDROID_CREATION_INTERSTITIAL", RecyclerViewTypes.VIEW_TYPE_PLACEHOLDER);
    public static final y0 ANDROID_CREATOR_REWARDS_CHALLENGE_DETAILS = new y0("ANDROID_CREATOR_REWARDS_CHALLENGE_DETAILS", RecyclerViewTypes.VIEW_TYPE_FULL_SPAN_PLACEHOLDER);
    public static final y0 CREATION_INSPIRATION_TRENDS = new y0("CREATION_INSPIRATION_TRENDS", RecyclerViewTypes.VIEW_TYPE_MAKEUP_CAROUSEL_ITEM);
    public static final y0 ANDROID_SURVEY_TAKEOVER = new y0("ANDROID_SURVEY_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_MAKEUP_CAROUSEL_ITEM_LOADING);
    public static final y0 COLLAGE_COMPOSER = new y0("COLLAGE_COMPOSER", RecyclerViewTypes.VIEW_TYPE_MAKEUP_CAROUSEL_ITEM_CLEAR);
    public static final y0 ANDROID_PIN_CLOSEUP_AFTER_DOWNLOAD = new y0("ANDROID_PIN_CLOSEUP_AFTER_DOWNLOAD", RecyclerViewTypes.VIEW_TYPE_LEGO_EMPTY_STATE_MESSAGE);
    public static final y0 ANDROID_PIN_CLOSEUP_AFTER_NO_ACTION = new y0("ANDROID_PIN_CLOSEUP_AFTER_NO_ACTION", RecyclerViewTypes.VIEW_TRY_ON_FEED_PRODUCT_CARD);
    public static final y0 ANDROID_PIN_CLOSEUP_AFTER_SAVE = new y0("ANDROID_PIN_CLOSEUP_AFTER_SAVE", RecyclerViewTypes.VIEW_TYPE_USER_PIN_REACTION);
    public static final y0 ANDROID_PIN_CLOSEUP_AFTER_REACT = new y0("ANDROID_PIN_CLOSEUP_AFTER_REACT", RecyclerViewTypes.VIEW_TYPE_SHOPPING_SPOTLIGHT);
    public static final y0 ANDROID_PIN_CLOSEUP_AFTER_SHARE = new y0("ANDROID_PIN_CLOSEUP_AFTER_SHARE", RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_IMAGE);
    public static final y0 ANDROID_PIN_CLOSEUP_AFTER_SCREENSHOT = new y0("ANDROID_PIN_CLOSEUP_AFTER_SCREENSHOT", RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_VIDEO);
    public static final y0 ANDROID_HOME_FEED_AFTER_SAVE = new y0("ANDROID_HOME_FEED_AFTER_SAVE", RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_APP_INSTALL_IMAGE);
    public static final y0 ANDROID_HOME_FEED_AFTER_CLICKTHROUGH = new y0("ANDROID_HOME_FEED_AFTER_CLICKTHROUGH", RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_APP_INSTALL_VIDEO);
    public static final y0 ANDROID_SEARCH_RESULTS_AFTER_SAVE = new y0("ANDROID_SEARCH_RESULTS_AFTER_SAVE", RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_IMAGE_FULL_SPAN);
    public static final y0 ANDROID_SEARCH_RESULTS_AFTER_CLICKTHROUGH = new y0("ANDROID_SEARCH_RESULTS_AFTER_CLICKTHROUGH", RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_VIDEO_FULL_SPAN);
    public static final y0 ANDROID_HYBRID_SEARCH_RESULTS = new y0("ANDROID_HYBRID_SEARCH_RESULTS", RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_APP_INSTALL_IMAGE_FULL_SPAN);
    public static final y0 ANDROID_AD_CLOSEUP_AFTER_CLICKTHROUGH = new y0("ANDROID_AD_CLOSEUP_AFTER_CLICKTHROUGH", RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_APP_INSTALL_VIDEO_FULL_SPAN);
    public static final y0 ANDROID_AD_CLOSEUP_AFTER_SAVE = new y0("ANDROID_AD_CLOSEUP_AFTER_SAVE", RecyclerViewTypes.VIEW_TYPE_GMA_INLINE_AD);
    public static final y0 ANDROID_AD_CLOSEUP_AFTER_NO_ACTION = new y0("ANDROID_AD_CLOSEUP_AFTER_NO_ACTION", RecyclerViewTypes.VIEW_TYPE_GMA_INLINE_AD_FULL_SPAN);
    public static final y0 ANDROID_PROFILE_BOARD_TAB_TAKEOVER = new y0("ANDROID_PROFILE_BOARD_TAB_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_BUBBLE_CATEGORY_REP);
    public static final y0 MEDIA_PLANER_SAVED_PLANS = new y0("MEDIA_PLANER_SAVED_PLANS", RecyclerViewTypes.VIEW_TYPE_BUBBLE_NAVIGATION_REP);
    public static final y0 MEDIA_PLANNER_CREATE_PLAN_SIDEBAR = new y0("MEDIA_PLANNER_CREATE_PLAN_SIDEBAR", RecyclerViewTypes.VIEW_TYPE_BUBBLE_DEFAULT_REP);
    public static final y0 MEDIA_PLANNER_HEADER = new y0("MEDIA_PLANNER_HEADER", RecyclerViewTypes.VIEW_TYPE_BUBBLE_STYLE_REP);
    public static final y0 ANDROID_POST_GIFT_GUIDE_REPIN_TAKEOVER = new y0("ANDROID_POST_GIFT_GUIDE_REPIN_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_BUBBLE_MULTI_IMAGE_REP);
    public static final y0 ANDROID_PIN_CLOSEUP_PIN_STATS_TAKEOVER = new y0("ANDROID_PIN_CLOSEUP_PIN_STATS_TAKEOVER", RecyclerViewTypes.VIEW_TYPE_BUBBLE_IMAGE_GRID_REP);
    public static final y0 NOTIFICATION_HIGHLIGHT = new y0("NOTIFICATION_HIGHLIGHT", RecyclerViewTypes.VIEW_TYPE_BUBBLE_MULTI_TOPIC_TILE);
    public static final y0 NOTIFICATION_PUSH = new y0("NOTIFICATION_PUSH", RecyclerViewTypes.VIEW_TYPE_BUBBLE_EDITORIAL_CARD);
    public static final y0 ANDROID_HOME_FEED_AFTER_DOWNLOAD = new y0("ANDROID_HOME_FEED_AFTER_DOWNLOAD", RecyclerViewTypes.VIEW_TYPE_BUBBLE_MULTI_IMAGE_EDITORIAL_CARD);
    public static final y0 ANDROID_SEARCH_RESULTS_AFTER_DOWNLOAD = new y0("ANDROID_SEARCH_RESULTS_AFTER_DOWNLOAD", RecyclerViewTypes.VIEW_TYPE_BUBBLE_IMAGE_WITH_TITLE_OVERLAY);
    public static final y0 ANDROID_BOARD_AFTER_DOWNLOAD = new y0("ANDROID_BOARD_AFTER_DOWNLOAD", RecyclerViewTypes.VIEW_TYPE_ICON_AND_TEXT_INLINE_BUBBLE);
    public static final y0 ANDROID_USER_PROFILE_AFTER_DOWNLOAD = new y0("ANDROID_USER_PROFILE_AFTER_DOWNLOAD", RecyclerViewTypes.VIEW_TYPE_LENS_PHOTO);

    private static final /* synthetic */ y0[] $values() {
        return new y0[]{NOOP, ANDROID_NOOP, ANDROID_GLOBAL_NAG, ANDROID_BOARD_TAKEOVER, ANDROID_USER_PROFILE_TAKEOVER, ANDROID_PIN_CLOSEUP_TAKEOVER, ANDROID_PDPPLUS_CLOSEUP_TAKEOVER, ANDROID_MAIN_USER_ED, ANDROID_HOME_FEED_TAKEOVER, ANDROID_NETWORK_STORY_NAG, ANDROID_SHARE_SHEET, ANDROID_ALL_PINS_VIEW_TAKEOVER, ANDROID_COMMERCE_CHECKOUT_TAKEOVER, ANDROID_FLASHLIGHT_TAKEOVER, ANDROID_COMMERCE_CHECKOUT_PAYMENT, ANDROID_PIN_CLOSEUP_COMMERCE_TAKEOVER, ANDROID_EXPLORE_TAB_TAKEOVER, ANDROID_SEARCH_PIN_RESULTS_TAKEOVER, ANDROID_CATEGORY_PIN_RESULTS_TAKEOVER, ANDROID_REPIN_DIALOG_TAKEOVER, ANDROID_INAPP_BROWSER_TAKEOVER, ANDROID_PINCLOSEUP_IAB_TAKEOVER, ANDROID_MENU_COMMERCE_ICON, ANDROID_PIN_SUCCESS, ANDROID_PIN_CLOSEUP_TAKEOVER_AFTER_LIKE, ANDROID_PIN_CLOSEUP_TAKEOVER_AFTER_CLICKTHROUGH, ANDROID_NOTIFICATIONS_TAKEOVER, ANDROID_SEARCH_TYPEAHEAD_TAKEOVER, ANDROID_CAMERA_DISCOVERY, ANDROID_HOME_FEED_NUX_TAKEOVER, ANDROID_HOME_FEED_STORY_TAKEOVER, ANDROID_HOME_FEED_TAKEOVER_AFTER_SCROLL, ANDROID_TRIED_IT_CREATION, ANDROID_NEWS_HUB_DETAIL_TAKEOVER, ANDROID_NAVIGATION_TAB_BAR_TITLES, ANDROID_NAVIGATION_BAR_STYLES, ANDROID_APP_TAKEOVER, ANDROID_PIN_CLOSEUP_TAKEOVER_AFTER_SCREENSHOT, ANDROID_NAV_BAR_TAKEOVER, ANDROID_LENS_TAKEOVER, ANDROID_STORY_PIN_GRID_CELL, ANDROID_STORY_PIN_CLOSEUP, ANDROID_STORY_PIN_CREATION_CLOSEUP, ANDROID_STORY_PIN_CREATION_MENU, ANDROID_STORY_PIN_CLOSEUP_COVER, ANDROID_STORY_PIN_CREATION_CLOSEUP_COVER, ANDROID_STORY_PIN_CREATION_MENU_REORDER, ANDROID_TAKEOVER_AFTER_DOWNLOAD, ANDROID_QUICKSAVE, ANDROID_BOARD_FILTER_ICON, ANDROID_BOARD_NOTE_CLOSEUP, ANDROID_SEARCH_TAB_LANDING_TAKEOVER, ANDROID_INBOX_TAKEOVER, ANDROID_SHARESHEET_SEARCHMODAL_TAKEOVER, ANDROID_SHARESHEET_TAKEOVER, ANDROID_STORY_PIN_CREATION_TAKEOVER, ANDROID_STORY_PIN_PUBLISH_TAKEOVER, ANDROID_STORY_PIN_EDIT_TAKEOVER, ANDROID_STORY_PIN_CREATION_METADATA, ANDROID_IDEA_STREAM_TAKEOVER, ANDROID_CALL_TO_CREATE_LANDING_PAGE, ANDROID_WATCH_TAB_STREAM_TAKEOVER, ANDROID_WATCH_TAB_STREAM_GRID_INDEX_0, ANDROID_PERSONAL_BOUTIQUE_TAKEOVER, ANDROID_IDEA_PIN_TEMPLATE_PICKER, ANDROID_PRODUCT_SEARCH_PAGE_TAKEOVER, ANDROID_PROFILES_SEARCH_PAGE_TAKEOVER, ANDROID_CLOSEUP_TOPIC_PICKER_MODULE, ANDROID_IDEA_PIN_CREATION_CAMERA, ANDROID_IDEA_PIN_CREATION_ADVANCED_SETTINGS, ANDROID_IDEA_PIN_CREATION_FINISHING_TOUCHES, ANDROID_IDEA_PIN_CREATION_PAGE_EDITOR, ANDROID_IDEA_PIN_CREATION_VIDEO_EDITOR, ANDROID_IDEA_PIN_CREATION_MUSIC_BROWSER, ANDROID_IDEA_PIN_CREATION_MUSIC_EDITOR, ANDROID_CREATOR_ONBOARDING_LANDING_PAGE, ANDROID_IDEA_PIN_CREATION_ASSET_PICKER, ANDROID_TV_CLOSEUP_VERTICAL_SCROLL_FEED, ANDROID_TV_LANDING_PAGE_TAKEOVER, ANDROID_IDEA_PIN_CREATION_DRAFTS, ANDROID_IDEA_PIN_CREATION_ASPECT_RATIO_EDITOR, ANDROID_ANALYTICS_CONTENT_TYPE_FILTER, ANDROID_WATCH_TAB_LIVESTREAM_UNIT, ANDROID_STORY_PIN_CREATION_QUESTION_STICKER_EDITOR_AFTER_TYPING, ANDROID_PIN_CLOSEUP_AFTER_SHOWING_MORE_LIKE_THIS, ANDROID_PIN_CLOSEUP_AFTER_SHOWING_RELATED_PINS, ANDROID_BOARD_MORE_IDEAS_FEED_AFTER_SAVE, ANDROID_TOPIC_LANDING_FEED_AFTER_SAVE, ANDROID_COMMENT_FEED_TAKEOVER, ANDROID_COMMENT_FEED_TAKEOVER_AFTER_COMMENT_SUBMISSION, ANDROID_HOME_FEED_AFTER_SAVE_TO_PROFILE_ON_PREVIOUS_SCREEN, ANDROID_BOARD_AFTER_AUTO_ORG, ANALYTICS_HOME_TAKEOVER, ANALYTICS_AUDIENCE_DASHBOARD_TAKEOVER, ANALYTICS_HOME_HERO, ANALYTICS_HEADER_BANNER, ANALYTICS_FOOTER_UPSELL, ANDROID_ANALYTICS_OVERVIEW_UPSELL, ANDROID_PIN_STATS_TAKEOVER, ANALYTICS_AUDIENCE_INSIGHTS_TAKEOVER, ANALYTICS_CONVERSION_INSIGHTS_UPSELL_BANNER, ANALYTICS_HOME_TOP_PRODUCT_GROUP_SECTION, EMAIL_USER_ED_TIP, BATCH_NUX_EMAILS, BATCH_RECOMMENDATION_EMAILS, BATCH_PUSH_NOTIFICATONS, BATCH_NETWORK_STORY, BATCH_TRIGGERED_EMAILS, HOMEFEED_NEW_USER_STORY, HOMEFEED_STORY_SLOT_7, CLICK_REDIRECT, ANDROID_TRIED_IT_SUCCESS, ANDROID_PIN_GRID_ATTRIBUTION, ANDROID_PROMOTED_PIN_CELL_IN_GRID, HIDE_CLOSEUP_FIELDS_FEATURE, REMOVE_PIN_SWIPE_FEATURE, PIN_CLOSEUP_MORE_LIKE_THIS_BTN_FEATURE, PIN_CLOSEUP_HIDE_SHARE_BTN_FEATURE, NAV_BAR_AUTOHIDE_FEATURE, ANDROID_SECTION_ORGANIZE_TAKEOVER, ANDROID_SECTION_REORDER_TAKEOVER, ANDROID_SECTION_TAKEOVER, HOMEFEED_HIDE_PIN, SEARCH_PINS_FEED_STORY_SLOT_0, SEARCH_PINS_FEED_STORY, RELATED_PINS_FEED_STORY, HOMEFEED_DYNAMIC_INSERTION_STORY, ANALYTICS_TOP_UPSELL_SECTION, LIVE_SESSIONS_TAB_FEED_STORY, ANDROID_FOLLOWING_TAB_TAKEOVER, CAMERA_DISCOVERY, BACKEND_RELATED_PINS_CONTENT, SHOPPING_ADS_AUTOSCROLL_COUNTER, ANDROID_OWN_BOARD_MORE_IDEAS_TAKEOVER, ANDROID_OWN_BOARD_SECTION_MORE_IDEAS_TAKEOVER, BOARD_MORE_IDEAS_CARDS, ANDROID_OWN_BOARD_YOUR_PINS_TAB, HOMEFEED_MORE_IDEAS_HEADER, SEARCH_PAGE_CURATION_PRODUCT_UPSELL, BOARD_MORE_IDEAS_FEED_STORY, INTEREST_FEED_STORY, ANDROID_EXPLORE_POSSIBILITIES_FEED_TAKEOVER, EXPLORE_POSSBILITIES_FEED_STORY, BOARD_FEED_STORY, HOMEFEED_MORE_IDEAS_FEED_STORY, ANDROID_PERSONALIZED_SHOPPING, ANDROID_HOMEFEED_TUNER_BOARDS, ANDROID_BUSINESS_HUB_TAKEOVER, ANDROID_BUSINESS_HUB_ACTIVATION_CARDS_MODULE, ANDROID_BUSINESS_HUB_RESOURCE_CARDS_MODULE, ANDROID_BUSINESS_HUB_ACTION_CARDS_MODULE, ANDROID_BUSINESS_HUB_STORY_PINS_ADOPTION, ANDROID_BUSINESS_HUB_SINGLE_EDIT_PROFILE_MODULE, ANDROID_BUSINESS_HUB_AFTER_LOAD, ANDROID_NEWS_HUB_FIRST_STORY, ANDROID_INBOX_CONVERSATION_TAKEOVER, ANDROID_INBOX_CONVERSATION_TAKEOVER_AFTER_CONTACT_REQ_ACCEPTED, ANDROID_USER_SETTINGS_TAKEOVER, ANDROID_AFTER_COMMENT_LIKE_TAKEOVER, ANDROID_STORY_PIN_RELATED_CONTENT_TAKEOVER, CREATOR_HUB_NEWS_MODULE, ANDROID_CREATION_INTERSTITIAL, ANDROID_CREATOR_REWARDS_CHALLENGE_DETAILS, CREATION_INSPIRATION_TRENDS, ANDROID_SURVEY_TAKEOVER, COLLAGE_COMPOSER, ANDROID_PIN_CLOSEUP_AFTER_DOWNLOAD, ANDROID_PIN_CLOSEUP_AFTER_NO_ACTION, ANDROID_PIN_CLOSEUP_AFTER_SAVE, ANDROID_PIN_CLOSEUP_AFTER_REACT, ANDROID_PIN_CLOSEUP_AFTER_SHARE, ANDROID_PIN_CLOSEUP_AFTER_SCREENSHOT, ANDROID_HOME_FEED_AFTER_SAVE, ANDROID_HOME_FEED_AFTER_CLICKTHROUGH, ANDROID_SEARCH_RESULTS_AFTER_SAVE, ANDROID_SEARCH_RESULTS_AFTER_CLICKTHROUGH, ANDROID_HYBRID_SEARCH_RESULTS, ANDROID_AD_CLOSEUP_AFTER_CLICKTHROUGH, ANDROID_AD_CLOSEUP_AFTER_SAVE, ANDROID_AD_CLOSEUP_AFTER_NO_ACTION, ANDROID_PROFILE_BOARD_TAB_TAKEOVER, MEDIA_PLANER_SAVED_PLANS, MEDIA_PLANNER_CREATE_PLAN_SIDEBAR, MEDIA_PLANNER_HEADER, ANDROID_POST_GIFT_GUIDE_REPIN_TAKEOVER, ANDROID_PIN_CLOSEUP_PIN_STATS_TAKEOVER, NOTIFICATION_HIGHLIGHT, NOTIFICATION_PUSH, ANDROID_HOME_FEED_AFTER_DOWNLOAD, ANDROID_SEARCH_RESULTS_AFTER_DOWNLOAD, ANDROID_BOARD_AFTER_DOWNLOAD, ANDROID_USER_PROFILE_AFTER_DOWNLOAD};
    }

    static {
        y0[] $values = $values();
        $VALUES = $values;
        $ENTRIES = lb.l0.b0($values);
        Companion = new w0();
    }

    private y0(String str, int i13) {
    }

    public static final y0 findByValue(int i13) {
        Companion.getClass();
        return w0.a(i13);
    }

    @NotNull
    public static el2.a getEntries() {
        return $ENTRIES;
    }

    public static y0 valueOf(String str) {
        return (y0) Enum.valueOf(y0.class, str);
    }

    public static y0[] values() {
        return (y0[]) $VALUES.clone();
    }

    public final int getValue() {
        return value();
    }

    public final int value() {
        switch (x0.f71497a[ordinal()]) {
            case 1:
                return 1;
            case 2:
                return 20000;
            case 3:
                return 20002;
            case 4:
                return 20003;
            case 5:
                return 20004;
            case 6:
                return 20005;
            case 7:
                return 1000419;
            case 8:
                return 20006;
            case 9:
                return 20008;
            case 10:
                return 20009;
            case 11:
                return 20014;
            case 12:
                return 20015;
            case 13:
                return 20016;
            case 14:
                return 1000158;
            case 15:
                return 20019;
            case 16:
                return 20020;
            case 17:
                return 20021;
            case 18:
                return 20022;
            case 19:
                return 20023;
            case 20:
                return 20024;
            case 21:
                return 1000001;
            case 22:
                return 1000000;
            case 23:
                return 1000002;
            case 24:
                return 1000010;
            case 25:
                return 1000021;
            case 26:
                return 1000022;
            case 27:
                return 1000033;
            case 28:
                return 1000039;
            case 29:
                return 1000040;
            case 30:
                return 1000042;
            case 31:
                return 1000043;
            case 32:
                return 1000046;
            case 33:
                return 1000058;
            case 34:
                return 1000059;
            case 35:
                return 1000091;
            case 36:
                return 1000092;
            case 37:
                return 1000111;
            case 38:
                return 1000131;
            case 39:
                return 1000159;
            case 40:
                return 1000187;
            case 41:
                return 1000198;
            case 42:
                return 1000199;
            case 43:
                return 1000200;
            case 44:
                return 1000201;
            case 45:
                return 1000202;
            case 46:
                return 1000203;
            case 47:
                return 1000204;
            case 48:
                return 1000246;
            case 49:
                return 1000247;
            case 50:
                return 1000330;
            case 51:
                return 1000267;
            case 52:
                return 1000282;
            case 53:
                return 1000283;
            case 54:
                return 1000292;
            case 55:
                return 1000461;
            case 56:
                return 1000341;
            case 57:
                return 1000349;
            case 58:
                return 1000350;
            case 59:
                return 1000354;
            case 60:
                return 1000357;
            case 61:
                return 1000364;
            case 62:
                return 1000371;
            case 63:
                return 1000373;
            case 64:
                return 1000381;
            case 65:
                return 1000390;
            case 66:
                return 1000397;
            case 67:
                return 1000398;
            case 68:
                return 1000399;
            case 69:
                return 1000400;
            case 70:
                return 1000405;
            case 71:
                return 1000408;
            case 72:
                return 1000420;
            case 73:
                return 1000509;
            case 74:
                return 1000439;
            case 75:
                return 1000448;
            case 76:
                return 1000429;
            case 77:
                return 1000401;
            case 78:
                return 1000437;
            case 79:
                return 1000446;
            case 80:
                return 1000450;
            case 81:
                return 1000453;
            case 82:
                return 1000465;
            case 83:
                return 1000472;
            case 84:
                return 1000475;
            case 85:
                return 1000524;
            case 86:
                return 1000525;
            case 87:
                return 1000529;
            case 88:
                return 1000531;
            case 89:
                return 1000607;
            case 90:
                return 1000561;
            case 91:
                return 1000591;
            case 92:
                return 1000592;
            case 93:
                return 60001;
            case 94:
                return 60002;
            case 95:
                return 60003;
            case 96:
                return 1000132;
            case 97:
                return 1000272;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_VIDEO_CREATOR_ANALYTICS_MODULE /* 98 */:
                return 1000289;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_NOTE_AND_FAVORITE_MODULE /* 99 */:
                return 1000300;
            case 100:
                return 1000355;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_HAIR_PATTERN_QUERIES_MODULE /* 101 */:
                return 1000382;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_SHOPPING_MODULE /* 102 */:
                return 1000474;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_TEMPLATE_DETAILS_MODULE /* 103 */:
                return 70001;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_PEAR_STYLES_MODULE /* 104 */:
                return 80001;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_SEE_IT_STYLED_MODULE /* 105 */:
                return 80002;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_PLACEHOLDER_LOADING_GRID /* 106 */:
                return 80003;
            case RecyclerViewTypes.VIEW_TYPE_PIN_PDP_MONOLITH_HEADER /* 107 */:
                return 80005;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_STL_SHOPPING_MODULE /* 108 */:
                return 80006;
            case RecyclerViewTypes.VIEW_TYPE_LIVE_SINGLE_COLUMN_UPSELL /* 109 */:
                return 110001;
            case RecyclerViewTypes.VIEW_TYPE_TV_CATEGORY_PICKER_CAROUSEL /* 110 */:
                return 1000061;
            case RecyclerViewTypes.VIEW_TYPE_TV_SCHEDULE_EPISODE /* 111 */:
                return 1000003;
            case RecyclerViewTypes.VIEW_TYPE_TV_CATEGORY_PAGE_HEADER /* 112 */:
                return 1000008;
            case RecyclerViewTypes.VIEW_TYPE_SCHEDULED_PIN_CELL /* 113 */:
                return 1000027;
            case RecyclerViewTypes.VIEW_TYPE_SCHEDULED_PIN_SECTION_HEADER /* 114 */:
                return 1000030;
            case RecyclerViewTypes.VIEW_TYPE_ANNOUNCEMENT_MODAL_TYPE_ONE /* 115 */:
                return 1000075;
            case RecyclerViewTypes.VIEW_TYPE_PROFILE_CREATED_TAB_SCHEDULED_PINS_PREVIEW /* 116 */:
                return 1000079;
            case RecyclerViewTypes.VIEW_TYPE_CAROUSEL_SINGLE_COLUMN /* 117 */:
                return 1000083;
            case RecyclerViewTypes.VIEW_TYPE_SIMPLE_IMAGE_CELL /* 118 */:
                return 1000085;
            case RecyclerViewTypes.VIEW_TYPE_CAROUSEL_VIDEO_CELL /* 119 */:
                return 1000093;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_GRID_CELL /* 120 */:
                return 1000097;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_VIDEO_GRID_CELL /* 121 */:
                return 1000099;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_VIDEO_GRID_CELL_FULL_SPAN /* 122 */:
                return 1000100;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_CAROUSEL /* 123 */:
                return 1000116;
            case RecyclerViewTypes.VIEW_TYPE_STORY_BOARD_IDEAS_PREVIEW_FOOTER /* 124 */:
                return 1000136;
            case RecyclerViewTypes.VIEW_TYPE_STORY_BOARD_IDEAS_PREVIEW_DETAILED /* 125 */:
                return 1000297;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_GRID_CELL /* 126 */:
                return 1000139;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK /* 127 */:
                return 1000166;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK_FULL_SPAN /* 128 */:
                return 1000286;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK_SHOW_GRID_ACTIONS /* 129 */:
                return 1000345;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK_SHOW_GRID_ACTIONS_FULL_SPAN /* 130 */:
                return 1000104;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_VIDEO_GRID_CELL /* 131 */:
                return 1000034;
            case RecyclerViewTypes.VIEW_TYPE_FEED_SECTION_TITLE /* 132 */:
                return 1000067;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CAROUSEL /* 133 */:
                return 1000113;
            case RecyclerViewTypes.VIEW_TYPE_PIN_MINI_CELL /* 134 */:
                return 1000119;
            case RecyclerViewTypes.VIEW_TYPE_FIXED_SIZE_PIN_CELL /* 135 */:
                return 1000120;
            case RecyclerViewTypes.VIEW_TYPE_SEE_MORE_ACTION_CELL /* 136 */:
                return 1000124;
            case RecyclerViewTypes.VIEW_TYPE_FIXED_SIZE_PIN_IMAGE /* 137 */:
                return 1000126;
            case RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL /* 138 */:
                return 1000155;
            case RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL_ITEM /* 139 */:
                return 1000174;
            case RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL_ACTION_ITEM /* 140 */:
                return 1000214;
            case RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL_ITEM_HIDDEN /* 141 */:
                return 1000219;
            case RecyclerViewTypes.VIEW_TYPE_ARTICLE_CAROUSEL /* 142 */:
                return 1000231;
            case RecyclerViewTypes.VIEW_TYPE_ARTICLE_CAROUSEL_ITEM_IMAGE /* 143 */:
                return 1000229;
            case RecyclerViewTypes.VIEW_TYPE_VTO_CAROUSEL_ITEM /* 144 */:
                return 1000242;
            case RecyclerViewTypes.VIEW_TYPE_VTO_CAROUSEL_ITEM_TINTED /* 145 */:
                return 1000279;
            case RecyclerViewTypes.VIEW_TYPE_ARTICLE_CAROUSEL_ITEM_VIDEO /* 146 */:
                return 1000156;
            case RecyclerViewTypes.VIEW_TYPE_SEARCH_PRODUCT_COLLAGE_STORY /* 147 */:
                return 1000207;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_BUBBLES_PACKAGE_GRID_MODULE /* 148 */:
                return 1000252;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_BRAND_PACKAGE_GRID_MODULE /* 149 */:
                return 1000257;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_CATEGORY /* 150 */:
                return 1000263;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_UNIFIED_FILTER_MULTI_SELECT_ITEM /* 151 */:
                return 1000275;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_PRICE_FILTER_ITEM /* 152 */:
                return 1000299;
            case RecyclerViewTypes.VIEW_TYPE_STANDARD_FILTER_ITEM /* 153 */:
                return 1000318;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_PRODUCT_FILTER_HEADER /* 154 */:
                return 1000334;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_COLOR_FILTER /* 155 */:
                return 1000051;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_CATEGORY_FILTER_ITEM /* 156 */:
                return 1000271;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_SORT_FILTER /* 157 */:
                return 1000459;
            case RecyclerViewTypes.VIEW_TYPE_STELA_IN_FLASHLIGHT_ONE_COLUMN /* 158 */:
                return 1000280;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_EDUCATION_HEADER /* 159 */:
                return 1000304;
            case 160:
                return 1000366;
            case RecyclerViewTypes.VIEW_TYPE_PLACEHOLDER /* 161 */:
                return 1000369;
            case RecyclerViewTypes.VIEW_TYPE_FULL_SPAN_PLACEHOLDER /* 162 */:
                return 1000377;
            case RecyclerViewTypes.VIEW_TYPE_MAKEUP_CAROUSEL_ITEM /* 163 */:
                return 1000393;
            case RecyclerViewTypes.VIEW_TYPE_MAKEUP_CAROUSEL_ITEM_LOADING /* 164 */:
                return 1000415;
            case RecyclerViewTypes.VIEW_TYPE_MAKEUP_CAROUSEL_ITEM_CLEAR /* 165 */:
                return 1000422;
            case RecyclerViewTypes.VIEW_TYPE_LEGO_EMPTY_STATE_MESSAGE /* 166 */:
                return 1000507;
            case RecyclerViewTypes.VIEW_TRY_ON_FEED_PRODUCT_CARD /* 167 */:
                return 1000497;
            case RecyclerViewTypes.VIEW_TYPE_USER_PIN_REACTION /* 168 */:
                return 1000557;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_SPOTLIGHT /* 169 */:
                return 1000493;
            case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_IMAGE /* 170 */:
                return 1000599;
            case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_VIDEO /* 171 */:
                return 1000600;
            case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_APP_INSTALL_IMAGE /* 172 */:
                return 1000601;
            case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_APP_INSTALL_VIDEO /* 173 */:
                return 1000501;
            case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_IMAGE_FULL_SPAN /* 174 */:
                return 1000538;
            case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_VIDEO_FULL_SPAN /* 175 */:
                return 1000504;
            case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_APP_INSTALL_IMAGE_FULL_SPAN /* 176 */:
                return 1000539;
            case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_APP_INSTALL_VIDEO_FULL_SPAN /* 177 */:
                return 1000588;
            case RecyclerViewTypes.VIEW_TYPE_GMA_INLINE_AD /* 178 */:
                return 1000546;
            case RecyclerViewTypes.VIEW_TYPE_GMA_INLINE_AD_FULL_SPAN /* 179 */:
                return 1000545;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_CATEGORY_REP /* 180 */:
                return 1000556;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_NAVIGATION_REP /* 181 */:
                return 1000496;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_DEFAULT_REP /* 182 */:
                return 1000586;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_STYLE_REP /* 183 */:
                return 1000608;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_MULTI_IMAGE_REP /* 184 */:
                return 1000610;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_IMAGE_GRID_REP /* 185 */:
                return 1000579;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_MULTI_TOPIC_TILE /* 186 */:
                return 1000583;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_EDITORIAL_CARD /* 187 */:
                return 1000584;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_MULTI_IMAGE_EDITORIAL_CARD /* 188 */:
                return 1000611;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_IMAGE_WITH_TITLE_OVERLAY /* 189 */:
                return 1000614;
            case RecyclerViewTypes.VIEW_TYPE_ICON_AND_TEXT_INLINE_BUBBLE /* 190 */:
                return 1000615;
            case RecyclerViewTypes.VIEW_TYPE_LENS_PHOTO /* 191 */:
                return 1000616;
            case RecyclerViewTypes.VIEW_TYPE_LENS_DIRECTORY /* 192 */:
                return 1000617;
            default:
                throw new NoWhenBranchMatchedException();
        }
    }
}
