package h32;

import com.pinterest.feature.core.view.RecyclerViewTypes;

/* loaded from: classes2.dex */
public final class d1 {
    public static f1 a(int i13) {
        switch (i13) {
            case 1:
                return f1.PIN_CREATE;
            case 2:
                return f1.PIN_EDIT;
            case 3:
                return f1.PIN_DELETE;
            case 5:
                return f1.PIN_REPIN;
            case 12:
                return f1.PIN_CLICKTHROUGH;
            case 13:
                return f1.VIEW;
            case 14:
                return f1.PIN_SEND;
            case 16:
                return f1.PIN_CLOSEUP;
            case 18:
                return f1.PIN_IMPRESSION_ONE_PIXEL;
            case 20:
                return f1.BOARD_CREATE;
            case 22:
                return f1.BOARD_DELETE;
            case 25:
                return f1.BOARD_REMOVE_COLLABORATOR;
            case 26:
                return f1.BOARD_FOLLOW;
            case 27:
                return f1.BOARD_UNFOLLOW;
            case 28:
                return f1.BOARD_INVITE_COLLABORATOR;
            case 34:
                return f1.BOARD_REQUEST_APPROVAL_INVITE_COLLABORATOR;
            case 35:
                return f1.BOARD_SEND;
            case 40:
                return f1.USER_CREATE;
            case 41:
                return f1.USER_EDIT;
            case 42:
                return f1.USER_DELETE;
            case 44:
                return f1.USER_REORDER_BOARDS;
            case 45:
                return f1.USER_FOLLOW;
            case 46:
                return f1.USER_UNFOLLOW;
            case 48:
                return f1.USER_DEACTIVATED;
            case 50:
                return f1.USER_LOGIN_ATTEMPT;
            case 51:
                return f1.USER_PASSWORD_RESET_REQUEST;
            case 52:
                return f1.USER_PASSWORD_RESET_COMPLETED;
            case 54:
                return f1.USER_BLOCK;
            case 55:
                return f1.USER_UNBLOCK;
            case 56:
                return f1.USER_REPORT;
            case 59:
                return f1.PIN_REPORT;
            case 60:
                return f1.SEARCH_PINS;
            case 61:
                return f1.SEARCH_BOARDS;
            case 62:
                return f1.SEARCH_USERS;
            case 63:
                return f1.SEARCH_MY_PINS;
            case 64:
                return f1.SEARCH_VIDEOS;
            case 81:
                return f1.REFRESH;
            case 82:
                return f1.PIN_SAVE_TO_DEVICE;
            case 87:
                return f1.USER_DISABLE_FACBOOK;
            case 93:
                return f1.USER_DISABLE_GPLUS;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_HAIR_PATTERN_QUERIES_MODULE /* 101 */:
                return f1.CLICK;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_SHOPPING_MODULE /* 102 */:
                return f1.TAP;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_TEMPLATE_DETAILS_MODULE /* 103 */:
                return f1.LONG_PRESS;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_PEAR_STYLES_MODULE /* 104 */:
                return f1.DRAG;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_SEE_IT_STYLED_MODULE /* 105 */:
                return f1.HOVER;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_PLACEHOLDER_LOADING_GRID /* 106 */:
                return f1.TOGGLE_ON;
            case RecyclerViewTypes.VIEW_TYPE_PIN_PDP_MONOLITH_HEADER /* 107 */:
                return f1.TOGGLE_OFF;
            case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_STL_SHOPPING_MODULE /* 108 */:
                return f1.SWIPE;
            case RecyclerViewTypes.VIEW_TYPE_TV_CATEGORY_PICKER_CAROUSEL /* 110 */:
                return f1.SCROLL;
            case RecyclerViewTypes.VIEW_TYPE_TV_CATEGORY_PAGE_HEADER /* 112 */:
                return f1.PUSH_NOTIFICATION_RECEIVED_BY;
            case RecyclerViewTypes.VIEW_TYPE_SCHEDULED_PIN_CELL /* 113 */:
                return f1.PUSH_NOTIFICATION_OPENED_BY;
            case RecyclerViewTypes.VIEW_TYPE_SIMPLE_IMAGE_CELL /* 118 */:
                return f1.CONTEXTUAL_MENU_OPEN;
            case RecyclerViewTypes.VIEW_TYPE_CAROUSEL_VIDEO_CELL /* 119 */:
                return f1.CONTEXTUAL_MENU_CLOSE;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_GRID_CELL /* 120 */:
                return f1.RENDER;
            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_CAROUSEL /* 123 */:
                return f1.DISMISS;
            case RecyclerViewTypes.VIEW_TYPE_FIXED_SIZE_PIN_IMAGE /* 137 */:
                return f1.PIN_SCREENSHOT;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_CATEGORY /* 150 */:
                return f1.USER_SEND;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_CATEGORY_FILTER_ITEM /* 156 */:
                return f1.USER_SEARCH_PRIVACY_CHANGED;
            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_SORT_FILTER /* 157 */:
                return f1.USER_PERSONALIZED_RECOMMENDATIONS_CHANGED;
            case RecyclerViewTypes.VIEW_TYPE_STELA_IN_FLASHLIGHT_ONE_COLUMN /* 158 */:
                return f1.PULL_TO_REFRESH;
            case RecyclerViewTypes.VIEW_TYPE_USER_PIN_REACTION /* 168 */:
                return f1.USER_LOGOUT_ATTEMPT;
            case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_IMAGE /* 170 */:
                return f1.STORY_IMPRESSION_ONE_PIXEL;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_CATEGORY_REP /* 180 */:
                return f1.CONVERSATION_MESSAGE_SEND;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_DEFAULT_REP /* 182 */:
                return f1.CONVERSATION_HIDE;
            case RecyclerViewTypes.VIEW_TYPE_BUBBLE_STYLE_REP /* 183 */:
                return f1.CONVERSATION_REPORT;
            case 406:
                return f1.APP_START;
            case 408:
                return f1.PULL_NOTIFICATION_OPENED_BY;
            case 422:
                return f1.APP_BACKGROUND;
            case 601:
                return f1.INTEREST_FOLLOW;
            case 602:
                return f1.INTEREST_UNFOLLOW;
            case 700:
                return f1.DEEP_LINK_PINTEREST;
            case 701:
                return f1.DEEP_LINK_HTTP;
            case 702:
                return f1.DEEP_LINK_OTHER;
            case 801:
                return f1.SERVICE_ENTRY;
            case 900:
                return f1.BULK_PIN_DELETE;
            case 901:
                return f1.BULK_PIN_MOVE;
            case 1012:
                return f1.REFERRER_APP_LOGIN;
            case 1013:
                return f1.REFERRER_APP_SIGNUP;
            case 1017:
                return f1.APP_START_ATTRIBUTED;
            case 2701:
                return f1.APP_CRASH_DETECTED;
            case 2702:
                return f1.APP_CRASH_OOM_DETECTED;
            case 2716:
                return f1.APP_DEADLOCK_CRASH_DETECTED;
            case 2900:
                return f1.SAVE_BROWSER_PIN_IMAGES_FOUND;
            case 2901:
                return f1.SAVE_BROWSER_PIN_IMAGES_NOT_FOUND;
            case 2905:
                return f1.SAVE_BROWSER_URL_NAVIGATE;
            case 3400:
                return f1.PIN_CARD_VIEW;
            case 3600:
                return f1.VIDEO_PLAYBACK;
            case 3606:
                return f1.VIDEO_PLAYBACK_PERFORMANCE;
            case 3621:
                return f1.VIDEO_START;
            case 3623:
                return f1.VIDEO_PLAYBACK_COMPLETION;
            case 3667:
                return f1.VIDEO_MANAGER_SETUP;
            case 3700:
                return f1.BOARD_IMPRESSION_ONE_PIXEL;
            case 3703:
                return f1.TOPIC_IMPRESSION_ONE_PIXEL;
            case 3704:
                return f1.USER_IMPRESSION_ONE_PIXEL;
            case 3800:
                return f1.SEARCH_PINS_BUYABLE;
            case 3803:
                return f1.SEARCH_IMPRESSION_ONE_PIXEL;
            case 3811:
                return f1.LOAD_URL;
            case 3828:
                return f1.DROPDOWN_CHANGE;
            case 3829:
                return f1.ARTICLE_IMPRESSION_ONE_PIXEL;
            case 3832:
                return f1.ARTICLE_SEND;
            case 4074:
                return f1.DID_IT_ACTIVITY_REPORT;
            case 4100:
                return f1.PIN_CLICKTHROUGH_END;
            case 4101:
                return f1.PIN_ZOOM;
            case 4104:
                return f1.NUX_START;
            case 4105:
                return f1.NUX_END;
            case 4110:
                return f1.NEWS_HUB_FEED_IMPRESSION_ONE_PIXEL;
            case 4111:
                return f1.NEWS_HUB_DETAIL_IMPRESSION_ONE_PIXEL;
            case 4113:
                return f1.SEARCH_SOCIAL_TYPEAHEAD;
            case 4503:
                return f1.EXPERIENCE_VIEWED;
            case 4700:
                return f1.TIMED_APP_FOREGROUND;
            case 4701:
                return f1.TIMED_APP_BACKGROUND;
            case 4702:
                return f1.TIMED_PAIR_BEGIN;
            case 4703:
                return f1.TIMED_PAIR_END;
            case 6353:
                return f1.FLASHLIGHT_CAMERA_TAP_SNAP;
            case 6566:
                return f1.GRID_PIN_LEVELING_APPLIED;
            case 6567:
                return f1.EXPERIENCE_COMPLETED;
            case 6568:
                return f1.EXPERIENCE_DISMISSED;
            case 6570:
                return f1.FPE_START;
            case 6571:
                return f1.FPE_END;
            case 6707:
                return f1.FLASHLIGHT_LENS_UNIVERSE_SEARCH;
            case 6716:
                return f1.FLASHLIGHT_LENS_GALLERY_SEARCH;
            case 6904:
                return f1.VIDEO_PLAYBACK_INTERVAL;
            case 6905:
                return f1.DID_IT_SHARE;
            case 6906:
                return f1.VIDEO_SINGLE_QUARTILE;
            case 6923:
                return f1.IMAGE_ERROR;
            case 6938:
                return f1.SEO_LANDING_PAGE_VIEW;
            case 6940:
                return f1.BUBBLE_OPEN;
            case 6943:
                return f1.SCROLL_UP_FROM_RELATED_PINS;
            case 7000:
                return f1.DEFERRED_DEEP_LINK_FACEBOOK;
            case 7060:
                return f1.URL_LOAD_STARTED;
            case 7064:
                return f1.URL_LOAD_FINISHED;
            case 7065:
                return f1.URL_LOAD_ERROR;
            case 7069:
                return f1.URL_LOAD_PERCENT;
            case 7070:
                return f1.SWIPE_UP;
            case 7071:
                return f1.SWIPE_DOWN;
            case 7076:
                return f1.PINCODE_URL_NAVIGATE;
            case 7078:
                return f1.PINCODE_CREATE;
            case 7100:
                return f1.BOARD_SECTION_CREATE;
            case 7101:
                return f1.BOARD_SECTION_EDIT;
            case 7102:
                return f1.BOARD_SECTION_DELETE;
            case 7108:
                return f1.BULK_SELECT_ALL_PIN_MOVE;
            case 7109:
                return f1.BULK_SELECT_ALL_PIN_DELETE;
            case 7111:
                return f1.VIEW_WEBSITE_ONE_PIXEL;
            case 7114:
                return f1.VIEW_WEBSITE_100;
            case 7118:
                return f1.USER_ENABLE_INSTAGRAM;
            case 7119:
                return f1.USER_DISABLE_INSTAGRAM;
            case 7120:
                return f1.SEND_SHARE_OPEN;
            case 7122:
                return f1.PIN_REORDER;
            case 7133:
                return f1.SECTION_REORDER;
            case 7137:
                return f1.USER_ACTIVE;
            case 7158:
                return f1.BOARD_SECTION_REMOVE_PINS;
            case 7160:
                return f1.CONVERSATION_VIEWED;
            case 7161:
                return f1.CONVERSATION_INBOX_VIEWED;
            case 7172:
                return f1.BOARD_MERGE;
            case 7173:
                return f1.BOARD_SECTION_MERGE;
            case 7188:
                return f1.PIN_CLOSEUP_IMPRESSION_ONE_PIXEL;
            case 7301:
                return f1.PIN_SELECTION;
            case 7350:
                return f1.BOARD_IDEAS_VIEW;
            case 7352:
                return f1.PIN_CAROUSEL_SLOT_IMPRESSION_ONE_PIXEL;
            case 7362:
                return f1.PIN_CAROUSEL_SLOT_CLICKTHROUGH;
            case 7379:
                return f1.INVITE_APP_LAND;
            case 7381:
                return f1.USER_ENABLE_ETSY;
            case 7382:
                return f1.USER_DISABLE_ETSY;
            case 7383:
                return f1.START_TYPING;
            case 7435:
                return f1.LOCATION_PERMISSIONS_PROMPT;
            case 7436:
                return f1.LOCATION_PERMISSIONS_DENY;
            case 7438:
                return f1.LOCATION_PERMISSIONS_ACCEPT_WHILE_IN_USE;
            case 7472:
                return f1.INPUT_CHANGE;
            case 7492:
                return f1.SHARE_SHEET_DISMISS_NO_SEND;
            case 7493:
                return f1.SHARE_SHEET_DISMISS_WITH_SEND;
            case 7511:
                return f1.SHARE_SHEET_VIEW_WITH_CONTACTS;
            case 7512:
                return f1.SHARE_SHEET_VIEW_WITH_NO_CONTACTS;
            case 7518:
                return f1.VIDEO_UPLOAD_ATTEMPTED;
            case 7519:
                return f1.VIDEO_UPLOAD_UPLOADED;
            case 7520:
                return f1.VIDEO_UPLOAD_PROCESSED;
            case 7521:
                return f1.VIDEO_UPLOAD_SUCCEEDED;
            case 7528:
                return f1.LOCATION_PERMISSIONS_CURRENT_STATUS;
            case 7564:
                return f1.PIN_CREATE_FAILURE;
            case 7573:
                return f1.GUIDE_IMPRESSION_ONE_PIXEL;
            case 7574:
                return f1.BACKGROUND_REFRESH_WARM_START;
            case 7579:
                return f1.PIN_TAGS_LOAD;
            case 7588:
                return f1.STORY_PIN_BEGIN;
            case 7590:
                return f1.STORY_PIN_CREATE;
            case 7598:
                return f1.USER_SWITCH_SUCCESS;
            case 7603:
                return f1.FLASHLIGHT_CROPPER_MOVE;
            case 7604:
                return f1.FLASHLIGHT_CROPPER_RESIZE;
            case 7606:
                return f1.VISUAL_SEARCH_IMAGE_ZOOM;
            case 7607:
                return f1.VISUAL_SEARCH_IMAGE_PAN;
            case 7684:
                return f1.VIDEO_UPLOAD_CANCELLED;
            case 7714:
                return f1.USER_DELETE_REQUEST;
            case 7715:
                return f1.USER_SWITCH_INTENT;
            case 7716:
                return f1.USER_SWITCH_ATTEMPT;
            case 7726:
                return f1.STORY_PIN_CREATE_FAILURE;
            case 7759:
                return f1.BOARD_REPORT;
            case 7760:
                return f1.COLLECTION_ITEM_IMPRESSION_ONE_PIXEL;
            case 7761:
                return f1.COLLECTION_ITEM_CLICKTHROUGH;
            case 7762:
                return f1.COLLECTION_PIN_CLICKTHROUGH;
            case 7777:
                return f1.COLLECTION_ITEM_CLICKTHROUGH_END;
            case 7804:
                return f1.SCENE_3D_ROTATE;
            case 7806:
                return f1.SCENE_3D_TRANSLATE;
            case 7843:
                return f1.COLLECTION_PIN_CLICKTHROUGH_END;
            case 7883:
                return f1.STORY_PIN_EDIT;
            case 7884:
                return f1.STORY_PIN_EDIT_FAILURE;
            case 7946:
                return f1.DESTINATION_VIEW;
            case 8100:
                return f1.CONVERSATION_PIN_QUICK_REPLIES_VIEWED;
            case 8101:
                return f1.CONVERSATION_PIN_QUICK_REPLY_SEND;
            case 8105:
                return f1.CONVERSATION_PIN_REPLY;
            case 8112:
                return f1.USER_LOGOUT_SUCCESS;
            case 8151:
                return f1.CONVERSATION_EMPTY_INBOX_SEARCH_BAR_TAP_TARGET;
            case 8152:
                return f1.ACCEPT_CONTACT_REQUEST_CLICK;
            case 8153:
                return f1.DECLINE_CONTACT_REQUEST_CLICK;
            case 8154:
                return f1.REPORT_CONTACT_REQUEST_CLICK;
            case 8155:
                return f1.BLOCK_CONTACT_REQUEST_CLICK;
            case 8156:
                return f1.UNBLOCK_CONTACT_REQUEST_CLICK;
            case 8157:
                return f1.REPORT_CONTACT_REQUEST_MESSAGE_CONFIRM_CLICK;
            case 8158:
                return f1.REPORT_AND_BLOCK_CONTACT_REQUEST_MESSAGE_CONFIRM_CLICK;
            case 8159:
                return f1.DECLINE_CONTACT_REQUEST_UNDO_CLICK;
            case 8160:
                return f1.BLOCK_CONTACT_REQUEST_CONFIRM_CLICK;
            case 8210:
                return f1.PIN_LINK_REPORT;
            case 8212:
                return f1.BRAND_SURVEY_FALLBACK_TO_LEGACY;
            case 8213:
                return f1.BOTTOM_SHEET_SNAP_FULLY_OPEN;
            case 8214:
                return f1.BOTTOM_SHEET_SNAP_DEFAULT;
            case 8215:
                return f1.BOTTOM_SHEET_SNAP_MINIMIZED;
            case 8216:
                return f1.BOTTOM_SHEET_SNAP_UNKNOWN;
            case 8222:
                return f1.UPDATE;
            case 8319:
                return f1.GROUP_BOARDS_REACTION_BAR_OPEN;
            case 8363:
                return f1.APP_THEME_CHANGED;
            case 8379:
                return f1.VIRTUAL_TRY_ON_RENDERER_INITIALIZED_SUCCESS;
            case 8380:
                return f1.VIRTUAL_TRY_ON_RENDERER_INITIALIZED_FAILURE;
            case 8433:
                return f1.VIRTUAL_TRY_ON_PIN_APPLY;
            case 8519:
                return f1.PIN_INTEREST_TAG_SELECT;
            case 8520:
                return f1.PIN_INTEREST_TAG_DESELECT;
            case 8521:
                return f1.TAG_PIN_INTERESTS_SUCCESS;
            case 8522:
                return f1.TAG_PIN_INTERESTS_FAILURE;
            case 8528:
                return f1.GROUP_BOARDS_REACTION_SET;
            case 8540:
                return f1.COLLECTION_ITEM_REPIN;
            case 8569:
                return f1.TODAY_ARTICLE_IMPRESSION_ONE_PIXEL;
            case 8570:
                return f1.APPSFLYER_INIT;
            case 8571:
                return f1.APPSFLYER_FIRST_LAUNCH;
            case 8572:
                return f1.APPSFLYER_COLD_START_TASK;
            case 8573:
                return f1.APPSFLYER_RUNNABLE_START;
            case 8606:
                return f1.BOARD_SECTION_SUGGESTION_COMPLETED;
            case 8608:
                return f1.APPSFLYER_INIT_IMMEDIATE;
            case 8617:
                return f1.COLLECTION_ITEM_CLOSEUP;
            case 8631:
                return f1.BUSINESS_ACCOUNT_CREATE_COMPLETE;
            case 8710:
                return f1.USER_PROFILE_OVERFLOW_ACTIONS;
            case 8711:
                return f1.USER_PROFILE_OVERFLOW_ACTIONS_REPORT_SPAM;
            case 8712:
                return f1.USER_PROFILE_OVERFLOW_ACTIONS_REPORT_SPAM_CONFIRM;
            case 8721:
                return f1.SELECT;
            case 8722:
                return f1.UNSELECT;
            case 8754:
                return f1.PIN_IAB_DURATION;
            case 8780:
                return f1.IMAGE_UPLOAD_ATTEMPTED;
            case 8781:
                return f1.IMAGE_UPLOAD_UPLOADED;
            case 8784:
                return f1.IMAGE_UPLOAD_CANCELLED;
            case 8785:
                return f1.IMAGE_UPLOAD_FAILED;
            case 8786:
                return f1.VIDEO_UPLOAD_FAILED;
            case 8787:
                return f1.STORY_PIN_CREATE_ATTEMPTED;
            case 8788:
                return f1.PREVIEW_CONTACT_REQUEST_CLICK;
            case 8789:
                return f1.STORY_PIN_CREATE_CANCELLED;
            case 8839:
                return f1.STORY_PIN_CREATION_BEGIN;
            case 8841:
                return f1.BOARD_PERMISSION_SETTING_UPDATE;
            case 8877:
                return f1.STORY_PIN_EDIT_CANCELLED;
            case 8900:
                return f1.NUX_STEP_END;
            case 8905:
                return f1.MENTION_SELECT;
            case 8906:
                return f1.MENTION_REMOVE;
            case 8907:
                return f1.MENTION_SEARCH_BEGIN;
            case 8908:
                return f1.MENTION_SEARCH_CANCEL;
            case 8909:
                return f1.MENTION_UNLINK;
            case 8948:
                return f1.PIN_CLICK;
            case 8950:
                return f1.STORY_PIN_LOGGING_ERROR;
            case 8980:
                return f1.STORY_PIN_FONT_LIST_DOWNLOAD_FAILED;
            case 8981:
                return f1.STORY_PIN_FONT_DOWNLOAD_FAILED;
            case 8983:
                return f1.COMMENTS_COMPOSER_OPENED;
            case 8984:
                return f1.COMMENTS_COMPOSER_CLOSED_WITH_POST;
            case 8985:
                return f1.COMMENTS_COMPOSER_CLOSED_WITHOUT_POST;
            case 8986:
                return f1.GENERIC_STAT_LOG_EVENT;
            case 8999:
                return f1.STORY_PIN_MUSIC_PLAY;
            case 9030:
                return f1.STORY_PIN_VIDEO_EXPORT_ATTEMPTED;
            case 9031:
                return f1.STORY_PIN_VIDEO_EXPORT_SUCCEEDED;
            case 9032:
                return f1.STORY_PIN_VIDEO_EXPORT_FAILED;
            case 9033:
                return f1.STORY_PIN_VIDEO_EXPORT_CANCELLED;
            case 9034:
                return f1.VIRTUAL_TRY_ON_CHANGE_SWATCH;
            case 9068:
                return f1.VIDEO_INVALID_INTERVAL;
            case 9073:
                return f1.REGULAR_NUX_START;
            case 9074:
                return f1.REGULAR_NUX_END;
            case 9077:
                return f1.NUX_VIEW_GENDER;
            case 9078:
                return f1.NUX_DONE_GENDER;
            case 9079:
                return f1.NUX_VIEW_LOCALE;
            case 9080:
                return f1.NUX_DONE_LOCALE;
            case 9081:
                return f1.NUX_VIEW_TOPIC_PICKER;
            case 9082:
                return f1.NUX_DONE_TOPIC_PICKER;
            case 9083:
                return f1.STORY_PIN_VIDEO_EXPORT_INCOMPATIBLE_MEDIA;
            case 9093:
                return f1.VIDEO_INVALID_QUARTILE;
            case 9099:
                return f1.STORY_PIN_MULTI_DRAFTS_APPROACH_LIMIT;
            case 9100:
                return f1.STORY_PIN_MULTI_DRAFTS_REACH_LIMIT;
            case 9127:
                return f1.COMMENT_IMPRESSION_ONE_PIXEL;
            case 9226:
                return f1.STORY_PIN_IMAGE_TO_VIDEO_CONVERSION_ATTEMPTED;
            case 9227:
                return f1.STORY_PIN_IMAGE_TO_VIDEO_CONVERSION_SUCCEEDED;
            case 9228:
                return f1.STORY_PIN_IMAGE_TO_VIDEO_CONVERSION_FAILED;
            case 9229:
                return f1.STORY_PIN_IMAGE_TO_VIDEO_CONVERSION_CANCELLED;
            case 9251:
                return f1.STORY_PIN_MULTI_DRAFTS_MISSING_COVER;
            case 9252:
                return f1.LENS_PERMISSIONS_REQUEST;
            case 9273:
                return f1.AGGREGATED_COMMENT_COMMUNITY_GUIDELINE_BANNER_CLICK;
            case 9285:
                return f1.STORY_PIN_MULTI_DRAFTS_SAVE_COVER;
            case 9314:
                return f1.FULL_SCREEN_VIEW;
            case 9315:
                return f1.SWIPE_LEFT;
            case 9316:
                return f1.SWIPE_RIGHT;
            case 9317:
                return f1.TAP_LEFT;
            case 9318:
                return f1.TAP_RIGHT;
            case 9323:
                return f1.STORY_PIN_RESUME;
            case 9324:
                return f1.STORY_PIN_PAUSE;
            case 9355:
                return f1.MEDIA_GALLERY_PERFORMANCE_STATS;
            case 9361:
                return f1.STORY_PIN_ELEMENT_MOVE;
            case 9362:
                return f1.STORY_PIN_ELEMENT_SCALE;
            case 9363:
                return f1.STORY_PIN_ELEMENT_ROTATE;
            case 9364:
                return f1.STORY_PIN_ELEMENT_DELETE_ATTEMPT;
            case 9365:
                return f1.STORY_PIN_ELEMENT_DELETED;
            case 9366:
                return f1.STORY_PIN_FONT_SIZE_CHANGE;
            case 9371:
                return f1.NAVIGATION;
            case 9394:
                return f1.PUSH_NOTIFICATION_SOURCE_MISMATCH;
            case 9406:
                return f1.COMMENT_OVERFLOW_BLOCK_USER_TAP;
            case 9408:
                return f1.COMMENT_BLOCK_USER_CONFIRMATION_CANCEL_TAP;
            case 9409:
                return f1.COMMENT_BLOCK_USER_TOAST_UNDO_TAP;
            case 9454:
                return f1.STORY_PIN_CREATE_USER_FAILURE;
            case 9504:
                return f1.BACKEND_STORY_PIN_DELETE;
            case 9527:
                return f1.STORY_PIN_VIDEO_PLAY;
            case 9528:
                return f1.STORY_PIN_VIDEO_PAUSE;
            case 9529:
                return f1.STORY_PIN_REORDER;
            case 9530:
                return f1.STORY_PIN_DELETE;
            case 9533:
                return f1.STORY_PIN_LOAD_DRAFT_FAILED;
            case 9535:
                return f1.APP_SOUND_SETTING_CHANGED;
            case 9542:
                return f1.MANUAL_FILTERS_VISIT;
            case 9565:
                return f1.STORY_PIN_START_TIME_CHANGE;
            case 9566:
                return f1.STORY_PIN_END_TIME_CHANGE;
            case 9569:
                return f1.PIN_OPEN_IN_NATIVE_WEB_BROWSER;
            case 9605:
                return f1.PRODUCT_TAG_VISIT;
            case 9609:
                return f1.UNLINK_ACCOUNT;
            case 9610:
                return f1.UNLINK_ACCOUNT_FAILED;
            case 9612:
                return f1.IDEA_PIN_PRODUCT_TAG_REPIN;
            case 9661:
                return f1.COMMENT_CODE_VIEWED;
            case 9662:
                return f1.COMMENT_CODE_DISMISSED;
            case 9663:
                return f1.COMMENT_CODE_ACCEPTED;
            case 9681:
                return f1.COMMENT_REPLY_TAG_VISIT;
            case 9682:
                return f1.COMMENT_HELPER_VIEWED;
            case 9683:
                return f1.COMMENT_HELPER_SELECTED;
            case 9684:
                return f1.COMMENT_HELPER_SENT;
            case 9690:
                return f1.PORTAL_IMPRESSION_ONE_PIXEL;
            case 9700:
                return f1.SHARE_SHEET_IG_STORIES_EXPORT_SUCCESS;
            case 9701:
                return f1.SHARE_SHEET_IG_STORIES_EXPORT_FAILED;
            case 9702:
                return f1.SHARE_SHEET_IG_STORIES_EXPORT_CANCELLED;
            case 9703:
                return f1.SHARE_SHEET_FB_STORIES_EXPORT_SUCCESS;
            case 9704:
                return f1.SHARE_SHEET_FB_STORIES_EXPORT_FAILED;
            case 9705:
                return f1.SHARE_SHEET_FB_STORIES_EXPORT_CANCELLED;
            case 9706:
                return f1.SHARE_SHEET_DOWNLOAD_EXPORT_SUCCESS;
            case 9707:
                return f1.SHARE_SHEET_DOWNLOAD_EXPORT_FAILED;
            case 9708:
                return f1.SHARE_SHEET_DOWNLOAD_EXPORT_CANCELLED;
            case 9718:
                return f1.SEARCH_IDEA_PIN_STICKERS;
            case 9834:
                return f1.IDEA_PIN_VIDEO_STILL_PROCESSING_DISPLAYED;
            case 9838:
                return f1.AR_MODEL_LOAD_REQUESTED;
            case 9839:
                return f1.AR_MODEL_LOAD_COMPLETE;
            case 9840:
                return f1.AR_MODEL_LOAD_FAILED;
            case 9841:
                return f1.AR_OBJECT_PLACED;
            case 9843:
                return f1.ANDROID_ARCORE_DOWNLOAD_REQUESTED;
            case 9844:
                return f1.ANDROID_ARCORE_DOWNLOAD_REJECTED;
            case 9845:
                return f1.ANDROID_ARCORE_DOWNLOAD_COMPLETE;
            case 9848:
                return f1.STORY_PIN_CREATE_EXTERNAL_DEEP_LINK_SUCCESS;
            case 9849:
                return f1.STORY_PIN_CREATE_EXTERNAL_DEEP_LINK_FAILED;
            case 9903:
                return f1.RAW_IPD_LOG_SUCCESS;
            case 9904:
                return f1.RAW_IPD_LOG_FAILURE;
            case 9906:
                return f1.COMMENT_USER_REACTIONS_VIEWED;
            case 9949:
                return f1.IDEA_PIN_DRAFT_COMPATIBILITY_CONVERSION;
            case 9972:
                return f1.LIVE_SESSION_PRODUCT_IMPRESSION_ONE_PIXEL;
            case 9973:
                return f1.LIVE_SESSION_COMMENT_IMPRESSION_ONE_PIXEL;
            case 9987:
                return f1.SHARE_SHEET_CONTACT_SEND;
            case 9988:
                return f1.SHARE_SHEET_SENDING_CANCEL;
            case 9989:
                return f1.SHARE_SHEET_SENDING_ERROR;
            case 9990:
                return f1.MFA_ENABLE_SUCCESS;
            case 9991:
                return f1.MFA_DISABLE_SUCCESS;
            case 9992:
                return f1.MFA_LOGIN_SUCCESS;
            case 9993:
                return f1.ONEBAR_IMPRESSION_ONE_PIXEL;
            case 10030:
                return f1.SEEK;
            case 10031:
                return f1.PAID_SEARCH_LAND;
            case 10039:
                return f1.LOGIN_ATTEMPT_LIMIT_REACHED;
            case 10040:
                return f1.MAGIC_LINK_LOGIN_SUCCESS;
            case 10041:
                return f1.MAGIC_LINK_LOGIN_FAILURE;
            case 10054:
                return f1.MORE_IDEAS_FEED_UPSELL_IMPRESSION_ONE_PIXEL;
            case 10064:
                return f1.ANDROID_DFM_DOWNLOAD_STATUS;
            case 10065:
                return f1.ANDROID_DFM_TOAST_SHOWN;
            case 10087:
                return f1.CREATOR_ONBOARDING_LANDING_DEEPLINK;
            case 10088:
                return f1.CREATOR_ONBOARDING_LANDING_DEEPLINK_SUCCESS;
            case 10089:
                return f1.CREATOR_ONBOARDING_LANDING_DEEPLINK_FAILURE;
            case 10096:
                return f1.SEARCH_IDEA_PIN_MUSIC;
            case 10101:
                return f1.PERMISSIONS_REQUEST;
            case 10102:
                return f1.PERMISSIONS_RESULT;
            case 10104:
                return f1.IDEA_PIN_CAMERA_VIEW_APPEAR;
            case 10239:
                return f1.IDEA_PIN_CREATION_PERFORMANCE;
            case 10241:
                return f1.CONVERSION_UPSELL_ACTIVE;
            case 10246:
                return f1.SHUFFLE_IMPRESSION_ONE_PIXEL;
            case 10247:
                return f1.MFA_SUCCESS_EMAIL_VERIFICATION;
            case 10352:
                return f1.ADDRESS_BOOK_SYNC_ALLOWED;
            case 10353:
                return f1.ADDRESS_BOOK_SYNC_DECLINED;
            case 10354:
                return f1.ADDRESS_BOOK_SYNC_DECLINED_PERMANENTLY;
            case 10363:
                return f1.LEAD_FORM_OPEN;
            case 10364:
                return f1.IDEA_PIN_MULTI_DRAFT_EXPIRATION;
            case 10367:
                return f1.LEAD_FORM_TYPING;
            case 10368:
                return f1.LEAD_FORM_SUBMIT;
            case 10369:
                return f1.LEAD_FORM_CLOSE;
            case 10370:
                return f1.LEAD_FORM_SUBMIT_ERROR;
            case 10416:
                return f1.SEE_TRANSLATION_VIEWED;
            case 10417:
                return f1.SEE_TRANSLATION_TAP;
            case 10418:
                return f1.SEE_ORIGINAL_TAP;
            case 10436:
                return f1.CONVERSATION_INBOX_EMPTY_STATE_VIEW_DISPLAYED;
            case 10437:
                return f1.CONVERSATION_EMPTY_INBOX_NEW_MESSAGE_BTN_DISPLAYED;
            case 10438:
                return f1.CONVERSATION_INBOX_CONTACT_SYNC_BTN_DISPLAYED;
            case 10458:
                return f1.SHOWCASE_SUBPAGE_CLICKTHROUGH;
            case 10459:
                return f1.SHOWCASE_SUBPAGE_CLICKTHROUGH_END;
            case 10460:
                return f1.SHOWCASE_SUBPAGE_IMPRESSION_ONE_PIXEL;
            case 10461:
                return f1.SHOWCASE_SUBPAGE_CLOSEUP;
            case 10462:
                return f1.SHOWCASE_SUBPAGE_REPIN;
            case 10463:
                return f1.SHOWCASE_SUBPAGE_SWIPE_LEFT;
            case 10464:
                return f1.SHOWCASE_SUBPAGE_SWIPE_RIGHT;
            case 10465:
                return f1.SHOWCASE_SUBPIN_CLICKTHROUGH;
            case 10466:
                return f1.SHOWCASE_SUBPIN_CLICKTHROUGH_END;
            case 10467:
                return f1.SHOWCASE_SUBPIN_IMPRESSION_ONE_PIXEL;
            case 10469:
                return f1.SHOWCASE_SUBPIN_REPIN;
            case 10470:
                return f1.SHOWCASE_SUBPIN_SWIPE_LEFT;
            case 10471:
                return f1.SHOWCASE_SUBPIN_SWIPE_RIGHT;
            case 10472:
                return f1.SHOWCASE_PIN_CLICKTHROUGH;
            case 10473:
                return f1.SHOWCASE_PIN_CLICKTHROUGH_END;
            case 10476:
                return f1.CONTACT_SEARCH_MODAL_DISPLAYED;
            case 10485:
                return f1.QUIZ_PIN_RESPONSE;
            case 10486:
                return f1.QUIZ_PIN_COMPLETION;
            case 10487:
                return f1.QUIZ_PIN_RESULT_OPEN;
            case 10488:
                return f1.QUIZ_PIN_RESULT_CLOSE;
            case 10491:
                return f1.QUIZ_PIN_BACK;
            case 10500:
                return f1.USER_SET_DSA_OPT_OUT;
            case 10554:
                return f1.COMMUNITY_VIEW_INTENT;
            case 10559:
                return f1.SHOWCASE_SUBPAGE_THUMBNAIL_SWIPE_LEFT;
            case 10560:
                return f1.SHOWCASE_SUBPAGE_THUMBNAIL_SWIPE_RIGHT;
            case 14563:
                return f1.SAVE_BROWSER_PIN_IMAGES_REQUESTED;
            case 14564:
                return f1.PIN_CREATE_ATTEMPTED;
            case 14565:
                return f1.AUTO_ORGANIZE_BUTTON_TAPPED;
            case 14567:
                return f1.AUTO_CLUSTER_SELECTED;
            case 14568:
                return f1.AUTO_REFINE_BOARD_VIEW_BEGIN;
            case 14569:
                return f1.AUTO_REFINE_BOARD_PIN_SELECTED;
            case 14570:
                return f1.AUTO_REFINE_BOARD_PIN_DESELECTED;
            case 14571:
                return f1.AUTO_BOARD_NAME_INPUT_VIEW_BEGIN;
            case 14572:
                return f1.AUTO_BOARD_NAME_INPUTTED;
            case 14573:
                return f1.AUTO_BOARD_CREATED;
            case 14574:
                return f1.IDEA_PIN_PRODUCT_TAG_ADDED;
            case 14575:
                return f1.IDEA_PIN_PRODUCT_TAG_DELETED;
            case 14588:
                return f1.PASSCODE_BACKUP_EMAIL_EQUAL_TO_CURRENT;
            case 14589:
                return f1.SAVE_PASSCODE_SUCCESS;
            case 14590:
                return f1.SAVE_SETTING_WITH_PASSCODE_ERROR;
            case 14591:
                return f1.SAVE_SETTING_WITH_PASSCODE_SUCCESS;
            case 14592:
                return f1.LEAD_FORM_CACHE_SAVE;
            case 14593:
                return f1.LEAD_FORM_CACHE_LOAD_SUCCESS;
            case 14594:
                return f1.LEAD_FORM_CACHE_LOAD_EXPIRED;
            case 14595:
                return f1.LEAD_FORM_AUTOFILL;
            case 14596:
                return f1.MUSIC_PLAYLIST_OPEN;
            case 14597:
                return f1.MUSIC_PLAYLIST_DISMISS;
            case 14598:
                return f1.STORY_PIN_EMBEDDED_MUSIC_PLAY;
            case 14599:
                return f1.PIN_EMBEDDED_MUSIC_PLAY;
            case 14600:
                return f1.VIDEO_MUTE;
            case 14601:
                return f1.VIDEO_NO_MUTE;
            case 14602:
                return f1.PHOTO_COMMENT_PICKER_VIEWED;
            case 14603:
                return f1.PHOTO_COMMENT_PICKER_PHOTO_SELECTED;
            case 14604:
                return f1.PHOTO_COMMENT_PICKER_PHOTO_SELECTION_FAILED;
            case 14605:
                return f1.PHOTO_COMMENT_PICKER_CANCELED;
            case 14606:
                return f1.AUTO_SPARKLE_ORGANIZE_VIEW_BEGIN;
            case 14611:
                return f1.IDEA_PIN_VIDEO_CONTROLS_IN;
            case 14612:
                return f1.IDEA_PIN_VIDEO_CONTROLS_OUT;
            case 14615:
                return f1.PIN_CLOSEUP_MT_TRANSLATE;
            case 14616:
                return f1.PIN_CLOSEUP_MT_RESTORE;
            case 14625:
                return f1.PIN_CLOSEUP_NUDGE;
            case 14626:
                return f1.SHOWCASE_SUBPAGE_NUDGE;
            case 14627:
                return f1.PIN_IAB_START;
            case 14628:
                return f1.STORY_PIN_MUTE;
            case 14629:
                return f1.STORY_PIN_UNMUTE;
            case 14630:
                return f1.PRODUCT_SEARCH_BACK_BUTTON_EXIT;
            case 14651:
                return f1.INSTAGRAM_ACCT_CLAIMING_SUCCESS;
            case 14652:
                return f1.INSTAGRAM_ACCT_CLAIMING_FAILURE;
            case 14653:
                return f1.INSTAGRAM_ACCT_RECLAIMING_SUCCESS;
            case 14654:
                return f1.INSTAGRAM_ACCT_RECLAIMING_FAILURE;
            case 14655:
                return f1.INSTAGRAM_ACCT_UNCLAIMING_SUCCESS;
            case 14656:
                return f1.INSTAGRAM_ACCT_UNCLAIMING_FAILURE;
            case 14657:
                return f1.INSTAGRAM_ACCT_CLAIMING_AUTOPUBLISH_SUCCESS;
            case 14658:
                return f1.INSTAGRAM_ACCT_CLAIMING_AUTOPUBLISH_FAILURE;
            case 14660:
                return f1.DISABLE_PASSCODE_SUCCESS;
            case 14661:
                return f1.DISABLE_PASSCODE_FAILURE;
            case 14667:
                return f1.PIN_DESELECTION;
            case 14679:
                return f1.USER_PROFILE_REMOVE;
            case 14703:
                return f1.OFFSITE_SAVE_ENTER;
            case 14704:
                return f1.FILTER_NO_DATA;
            case 14721:
                return f1.AGGREGATED_PIN_COMMENT_LINK_TAP;
            case 14722:
                return f1.DATA_REQUEST_SUCCESS;
            case 14723:
                return f1.DATA_REQUEST_FAILURE;
            case 14858:
                return f1.INVITE_CODE_FOLLOW_SUCCESSFUL;
            case 14860:
                return f1.CLIENT_AUTH_INITIATED;
            case 14861:
                return f1.CLIENT_REGISTER_ATTEMPT;
            case 14862:
                return f1.CLIENT_REGISTER_SUCCESS;
            case 14863:
                return f1.CLIENT_REGISTER_FAILED;
            case 14864:
                return f1.CLIENT_SIGN_IN_ATTEMPT;
            case 14865:
                return f1.CLIENT_SIGN_IN_SUCCESS;
            case 14866:
                return f1.CLIENT_SIGN_IN_FAILED;
            case 14876:
                return f1.PEAR_SCREENSHOT;
            case 14887:
                return f1.ONE_BAR_MODULE_CLICK;
            case 14888:
                return f1.JOURNEY_BACK_BUTTON_CLICK;
            case 14892:
                return f1.COLLAGE_COMPOSER_LAYER_REORDER;
            case 14893:
                return f1.COLLAGE_COMPOSER_CUTOUT_ADDED;
            case 14895:
                return f1.COLLAGE_COMPOSER_TEXT_ADDED;
            case 14896:
                return f1.COLLAGE_COMPOSER_DRAWING_ADDED;
            case 14917:
                return f1.RELATED_PINS_FILTER_IMPRESSION_ONE_PIXEL;
            case 14925:
                return f1.BOARD_SCREENSHOT;
            case 14989:
                return f1.COLLAGE_COMPOSER_DRAFT_FIRST_SAVE;
            case 15054:
                return f1.IDEA_PIN_CREATE_WARN;
            case 15074:
                return f1.ARA_VIEW;
            case 15075:
                return f1.ARA_CLICK;
            case 15122:
                return f1.WIDGET_UPSELL_DISMISS;
            case 15123:
                return f1.WIDGET_UPSELL_STEPS_SHOWN;
            case 15125:
                return f1.WIDGET_PRE_UPSELL_SHOWN;
            case 15138:
                return f1.GMA_SDK_LOAD;
            case 15139:
                return f1.GMA_QUERY_INFO_FETCHED;
            case 15140:
                return f1.GMA_QUERY_INFO_SENT;
            case 15141:
                return f1.GMA_AD_LOADED;
            case 15142:
                return f1.GMA_AD_RENDERED;
            case 15143:
                return f1.MENTION_SETTINGS_TOGGLE;
            case 15144:
                return f1.MENTION_SETTINGS_VISIT;
            case 15145:
                return f1.BOARD_END;
            case 15146:
                return f1.GMA_AD_LOAD_FAILED;
            case 15165:
                return f1.AUTO_CLUSTERS_IMPRESSION;
            case 15251:
                return f1.GMA_SDK_QUARANTINE_FAILED;
            case 15262:
                return f1.HOME_FEED_INITIAL_LOAD_ERROR;
            case 15270:
                return f1.COMMENT_PUSH_NOTIFICATION_NUDGE_VIEWED;
            case 15271:
                return f1.COMMENT_PUSH_NOTIFICATION_NUDGE_DISMISSED;
            case 15288:
                return f1.SAMSUNG_PRELOAD_METADATA_SUCCESS;
            case 15289:
                return f1.SAMSUNG_PRELOAD_FAILED;
            case 15339:
                return f1.SAMSUNG_PRELOAD_METADATA_ATTEMPT;
            case 15359:
                return f1.GMA_QUERY_INFO_FAILED;
            case 15365:
                return f1.GMA_REQUEST_HEADER_MISSING;
            case 15377:
                return f1.BOARD_VIEW_UPSELL_MODAL_INVITE_COLLABORATORS_DISMISS;
            case 15378:
                return f1.BOARD_VIEW_UPSELL_MODAL_INVITE_COLLABORATORS_DISMISS_WITH_INVITE;
            case 15392:
                return f1.AUTH_COLLECTION_CLICK;
            case 15393:
                return f1.AUTH_COLLECTION_VIEW;
            case 15394:
                return f1.AUTH_COLLECTION_DISMISS;
            case 15395:
                return f1.AUTH_COLLECTION_SUCCESS;
            case 15396:
                return f1.AUTH_COLLECTION_REQUEST;
            case 15397:
                return f1.AUTH_COLLECTION_FAIL;
            case 15398:
                return f1.AUTH_COLLECTION_EDIT;
            case 15405:
                return f1.POST_SAVE_UPSELL_INVITE_COLLABORATORS_DISMISS_WITH_INVITE;
            case 15407:
                return f1.POST_SAVE_IMAGE_UPSELL_INVITE_COLLABORATORS_DISMISS_WITH_INVITE;
            case 15408:
                return f1.GRID_PIN_LEVELING_GAP;
            case 15423:
                return f1.UNIDIRECTIONAL_PASSCODE_ACKNOWLEDGED;
            case 15424:
                return f1.UNIDIRECTIONAL_PASSCODE_CANCELED;
            case 15425:
                return f1.AMAZON_ACCT_UNCLAIMING_SUCCESS;
            case 15426:
                return f1.AMAZON_ACCT_UNCLAIMING_FAILURE;
            case 15453:
                return f1.COLLAGE_COMPOSER_ITEM_SWAPPED;
            case 15454:
                return f1.PUSH_NOTIFICATION_BOARD_INVITE_TO_BE_CREATED;
            case 15455:
                return f1.PUSH_NOTIFICATION_BOARD_INVITE_CREATED;
            case 15461:
                return f1.COLLAGE_COMPOSER_COLLAGE_REMIXED;
            case 15484:
                return f1.PIN_HANDSHAKE_WEBVIEW_ERROR;
            case 15485:
                return f1.PIN_HANDSHAKE_ERROR;
            case 15486:
                return f1.PIN_HANDSHAKE_STEP;
            case 15497:
                return f1.AUTO_BOARD_PINS_ADD_TO_EXISTING_BOARD;
            case 15536:
                return f1.PIN_SUPPORTS_CLICKTHROUGH;
            case 15549:
                return f1.SH_BOARD_ADVISORY_VIEW;
            case 15550:
                return f1.SH_BOARD_SECTION_ADVISORY_VIEW;
            case 15553:
                return f1.ALL_FILTERS_DESELECTED;
            case 15559:
                return f1.GMA_SDK_MOBILE_CRASH;
            case 15592:
                return f1.GMA_IMP_AD_VALUES_RECEIVED;
            case 15646:
                return f1.PIN_REPIN_SUCCESS;
            case 15658:
                return f1.BOARD_SHARE_VIDEO_EXPORT_ATTEMPTED;
            case 15659:
                return f1.BOARD_SHARE_VIDEO_EXPORT_CODEC_CREATED;
            case 15660:
                return f1.BOARD_SHARE_VIDEO_EXPORT_CODEC_FAILED;
            case 15661:
                return f1.BOARD_SHARE_VIDEO_EXPORT_SUCCEEDED;
            case 15722:
                return f1.COMMENT_PUSH_NOTIFICATION_NUDGE_ACCEPTED;
            case 15745:
                return f1.END_SESSION_SUCCESS;
            case 15746:
                return f1.END_SESSION_FAILURE;
            case 15748:
                return f1.USE_CASES_SELECTED;
            case 15809:
                return f1.GMA_IMP_DATA_RECEIVED;
            case 15810:
                return f1.CONVERSATION_SETTINGS_VIEWED;
            case 15811:
                return f1.CONVERSATION_NOTIFICATIONS_SET_ALWAYS_ON;
            case 15812:
                return f1.CONVERSATION_NOTIFICATIONS_SET_MUTE_ONE_HOUR;
            case 15813:
                return f1.CONVERSATION_NOTIFICATIONS_SET_MUTE_EIGHT_HOURS;
            case 15814:
                return f1.CONVERSATION_NOTIFICATIONS_SET_MUTE_ONE_WEEK;
            case 15815:
                return f1.CONVERSATION_NOTIFICATIONS_SET_MUTE_INDEFINITELY;
            case 15816:
                return f1.GRID_PIN_LEVELING_GAP_FILLED;
            case 15818:
                return f1.CONVERSATION_THREAD_CLOSEUP_VIEWED;
            case 15821:
                return f1.ONE_BAR_MODULE_DESELECT;
            case 15822:
                return f1.NUX_DROP_OFF;
            case 15823:
                return f1.GRID_PIN_LEVELING_GAP_150;
            case 15870:
                return f1.SOCIAL_PERMISSION_SETTINGS_VISIT;
            case 15873:
                return f1.ADS_STL_ERROR;
            case 15875:
                return f1.COLLAGE_COMPOSER_CAMERA_ADDED;
            case 15876:
                return f1.COLLAGE_COMPOSER_USER_PHOTO_ADDED;
            case 16053:
                return f1.VIDEO_PREFETCH_START;
            case 16054:
                return f1.VIDEO_PREFETCH_END;
            case 16244:
                return f1.UNAUTH_EX_PRELOAD_CONTROL;
            case 16245:
                return f1.UNAUTH_EX_PRELOAD_ENABLED;
            case 16246:
                return f1.MOVE_GOOGLE_LINK_SUCCESS;
            case 16247:
                return f1.MOVE_GOOGLE_LINK_FAILURE;
            case 16248:
                return f1.USE_CASE_IMPRESSION_ONE_PIXEL;
            case 16258:
                return f1.COMMENT_FEED_CLOSED;
            case 16260:
                return f1.AD_DISCLOSURE_CLICKTHROUGH;
            case 16263:
                return f1.PIN_CLOSEUP_RICH_MT_TRANSLATE;
            case 16264:
                return f1.PIN_CLOSEUP_RICH_MT_RESTORE;
            case 16267:
                return f1.SEARCH_ONE_BAR_FILTER_NO_DATA;
            case 16268:
                return f1.SEARCH_ONE_BAR_FILTER_MODULE_NO_DATA;
            case 16269:
                return f1.INSTAGRAM_ACCT_CLAIMING_RETRY;
            case 16270:
                return f1.VOICE_PERMISSIONS_PROMPT;
            case 16282:
                return f1.EMAIL_OTP_VERIFICIATION_SUCCESS;
            case 16283:
                return f1.EMAIL_OTP_VERIFICIATION_FAILURE;
            case 16284:
                return f1.EMAIL_OTP_VERIFICATION_SUCCESS;
            case 16285:
                return f1.EMAIL_OTP_VERIFICATION_FAILURE;
            case 16291:
                return f1.UNAUTH_ACCOUNT_RECOVERY_SUCCESS;
            case 16292:
                return f1.UNAUTH_ACCOUNT_RECOVERY_FAILURE;
            case 16303:
                return f1.PIN_CLOSEUP_BOARD_CONVERSATION_THREAD_MODULE;
            case 16307:
                return f1.COMMUNITY_CONTENT_MODULE_VIEWED;
            case 16312:
                return f1.GMA_AD_STEP;
            case 16316:
                return f1.FLASHLIGHT_CROPPER_DISMISS;
            case 16431:
                return f1.PIN_IAB_END;
            case 16432:
                return f1.BROWSER_SCREENSHOT;
            case 16434:
                return f1.COMPLETE_EU_PROMPT;
            case 16445:
                return f1.DISMISS_EU_PROMPT;
            case 16446:
                return f1.HEADER_ACCOUNTS_CLAIM_BANNER_DISMISS;
            case 16447:
                return f1.URL_TIME_SPENT;
            case 16481:
                return f1.UNAUTH_ACCOUNT_RECOVERY_FIND_USER_BY_EMAIL_REQUEST;
            case 16482:
                return f1.UNAUTH_ACCOUNT_RECOVERY_FIND_USER_BY_EMAIL_SUCCESS;
            case 16483:
                return f1.UNAUTH_ACCOUNT_RECOVERY_FIND_USER_BY_NAME_REQUEST;
            case 16484:
                return f1.UNAUTH_ACCOUNT_RECOVERY_FIND_USER_BY_NAME_SUCCESS;
            case 16485:
                return f1.UNAUTH_ACCOUNT_RECOVERY_FB_ACCOUNT_RETRIEVAL;
            case 16486:
                return f1.UNAUTH_ACCOUNT_RECOVERY_FB_BANNER_CLICK;
            case 16487:
                return f1.PIN_SEE_MORE;
            case 16488:
                return f1.PIN_SEE_MORE_UNDO;
            case 16489:
                return f1.STORY_SEE_MORE;
            case 16490:
                return f1.STORY_SEE_MORE_UNDO;
            case 16491:
                return f1.STORY_SEE_LESS;
            case 16492:
                return f1.STORY_SEE_LESS_UNDO;
            case 16493:
                return f1.WL_SUBMIT;
            case 16495:
                return f1.LOGIN_OPTION_ENABLED_SUCCESS;
            case 16496:
                return f1.LOGIN_OPTION_ENABLED_FAILURE;
            case 16498:
                return f1.NRT_AUTO_ORG_VIEW;
            case 16499:
                return f1.NRT_AUTO_ORG_DISMISS;
            case 16500:
                return f1.NRT_AUTO_ORG_TIMEOUT;
            case 16540:
                return f1.PIN_SEE_LESS;
            case 16541:
                return f1.PIN_SEE_LESS_UNDO;
            case 16542:
                return f1.COLLAGE_CUTOUT_ITEM_CLICK;
            case 16543:
                return f1.COLLAGE_CUTOUT_ITEM_CLICKTHROUGH;
            case 16544:
                return f1.COLLAGE_CUTOUT_ITEM_CLICKTHROUGH_END;
            case 16545:
                return f1.COLLAGE_CUTOUT_ITEM_SWIPE_LEFT;
            case 16546:
                return f1.COLLAGE_CUTOUT_ITEM_SWIPE_RIGHT;
            case 16547:
                return f1.COLLAGE_CUTOUT_DRAWER_OPEN;
            case 16548:
                return f1.COLLAGE_CUTOUT_DRAWER_CLOSE;
            case 16567:
                return f1.END_OF_FEED;
            case 16585:
                return f1.FLASHLIGHT_CROPPER_NON_OBJECT_CROP;
            case 16586:
                return f1.FLASHLIGHT_CROPPER_PIN_LEVEL_CROP;
            case 16601:
                return f1.COLLAGE_CUTOUT_ITEM_VIEW;
            case 16605:
                return f1.INITIAL_FEED_LOAD_ABORT;
            case 16606:
                return f1.AMAZON_ACCT_CLAIMING_SEEN;
            case 16607:
                return f1.AMAZON_ACCT_LINK_BUTTON;
            case 16608:
                return f1.AMAZON_ACCT_CLAIMING_SUCCESS;
            case 16609:
                return f1.AMAZON_ACCT_CLAIMING_FAILURE;
            case 16610:
                return f1.AMAZON_ACCT_UNCLAIMING_SEEN;
            case 16611:
                return f1.AMAZON_ACCT_UNLINK_BUTTON;
            case 16612:
                return f1.FACEBOOK_HELP_CENTER_LINK;
            case 16613:
                return f1.SHOPPING_SKELETON_FALSE_POSITIVE;
            case 16614:
                return f1.SHOPPING_SKELETON_FALSE_NEGATIVE;
            case 16616:
                return f1.WIDGET_UPSELL_TRY_IT_CLICK;
            case 16617:
                return f1.WIDGET_UPSELL_WIDGET_PINNED;
            case 16673:
                return f1.COLLAGE_QUICK_SWAP_CAROUSEL_SWAP;
            case 16674:
                return f1.COLLAGE_QUICK_SWAP_CUTOUT_CAROUSEL_SWAP;
            case 16679:
                return f1.COMPLIANCE_REQUIREMENTS_SUCCESS;
            case 16680:
                return f1.COMPLIANCE_REQUIREMENTS_FAILURE;
            case 16681:
                return f1.COMPLIANCE_REQUIREMENTS_TIMEOUT;
            case 16682:
                return f1.COMPLIANCE_FEATURE_CHECK_NOT_LOADED;
            case 16683:
                return f1.VOICE_SEARCH_FAILURE;
            case 16684:
                return f1.AD_CLOSEUP_RP_VIEW;
            case 16685:
                return f1.DL_AD_CLOSEUP_OVERLAY_IMPRESSION;
            case 16686:
                return f1.DL_AD_CLOSEUP_OVERLAY_CLICKTHROUGH;
            case 16687:
                return f1.DL_AD_CLOSEUP_OVERLAY_CLICKTHROUGH_END;
            case 16760:
                return f1.FULFILLED_BY_SEARCH_FEATURES;
            case 16761:
                return f1.HANDSHAKE_ACCT_LINKING_SUCCESS;
            case 16762:
                return f1.HANDSHAKE_ACCT_LINKING_FAILURE;
            case 16763:
                return f1.HANDSHAKE_ACCT_UNLINKING_SUCCESS;
            case 16764:
                return f1.HANDSHAKE_ACCT_UNLINKING_FAILURE;
            case 16766:
                return f1.USER_SEARCH_ADVISORY;
            case 16820:
                return f1.CLOSEUP_PIN_LOAD_CACHE_HIT;
            case 16821:
                return f1.CLOSEUP_PIN_LOAD_CACHE_MISS;
            case 16826:
                return f1.PIN_OR_SPIN_VIEW_INTENT;
            case 16827:
                return f1.PIN_OR_SPIN_EXIT;
            case 16828:
                return f1.PIN_OR_SPIN_REFRESH;
            case 16829:
                return f1.PIN_OR_SPIN_PIN_SELECTED;
            case 16830:
                return f1.PIN_OR_SPIN_CHOSEN_PIN_SELECTED;
            case 16831:
                return f1.PIN_OR_SPIN_EXIT_REVEAL_REWARD_PAGE;
            case 16832:
                return f1.PIN_OR_SPIN_REVEAL_REWARD_VIEW_INTENT;
            case 16833:
                return f1.PIN_OR_SPIN_REVEAL_REWARD;
            case 16834:
                return f1.PIN_OR_SPIN_REWARD_VIEW_INTENT;
            case 16835:
                return f1.PIN_OR_SPIN_RESTART;
            case 16836:
                return f1.PIN_OR_SPIN_REWARD_SAVE_BOARD;
            case 16837:
                return f1.PIN_OR_SPIN_INSTAGRAM_SHARE;
            case 16893:
                return f1.OM_SDK_FUNNEL_STEP;
            case 16894:
                return f1.OM_SDK_FUNNEL_ERROR;
            case 16896:
                return f1.SUBMIT_NEW_PASSWORD;
            case 16897:
                return f1.REMOTE_PASSWORD_VALIDATION_SUCCESS;
            case 16898:
                return f1.REMOTE_PASSWORD_VALIDATION_FAILURE;
            case 16899:
                return f1.MQTT_CONNECTED_SUCCESS;
            case 16900:
                return f1.MQTT_CONNECTED_FAILURE;
            case 16901:
                return f1.MQTT_DISCONNECTED;
            case 16902:
                return f1.MQTT_RECONNECTED;
            case 16903:
                return f1.MQTT_MESSAGE_SENT;
            case 16913:
                return f1.QR_AUTH_VERIFY_TOKEN;
            case 16914:
                return f1.QR_AUTH_APPROVE;
            case 16920:
                return f1.PIN_OR_SPIN_SHARE_SHEET_CLICKED;
            case 16921:
                return f1.PIN_OR_SPIN_DOWNLOAD;
            case 16928:
                return f1.AUTOMAGICAL_BOARD_PIN_IMPRESSIONS;
            case 16929:
                return f1.AUTOMAGICAL_BOARD_PIN_REPINS;
            case 16930:
                return f1.AUTOMAGICAL_BOARD_PIN_5S_OUTBOUND_CLICKS;
            case 16931:
                return f1.AUTOMAGICAL_BOARD_PIN_OUTBOUND_CLICKS;
            case 16932:
                return f1.AUTOMAGICAL_BOARD_PIN_CLICKS;
            case 16933:
                return f1.AUTOMAGICAL_BOARD_PIN_GRID_CLICKS;
            case 16934:
                return f1.AUTOMAGICAL_BOARD_PIN_SAVES;
            case 16935:
                return f1.AUTOMAGICAL_BOARD_PIN_SHARES_COMPLETED;
            case 16936:
                return f1.AUTOMAGICAL_BOARD_TP_PIN_IMPRESSIONS;
            case 16937:
                return f1.AUTOMAGICAL_BOARD_TP_PIN_REPINS;
            case 16938:
                return f1.AUTOMAGICAL_BOARD_TP_PIN_5S_OUTBOUND_CLICKS;
            case 16939:
                return f1.AUTOMAGICAL_BOARD_TP_PIN_OUTBOUND_CLICKS;
            case 16940:
                return f1.AUTOMAGICAL_BOARD_TP_PIN_CLICKS;
            case 16941:
                return f1.AUTOMAGICAL_BOARD_TP_PIN_GRID_CLICKS;
            case 16942:
                return f1.AUTOMAGICAL_BOARD_TP_PIN_SAVES;
            case 16943:
                return f1.AUTOMAGICAL_BOARD_TP_PIN_SHARES_COMPLETED;
            case 16944:
                return f1.AUTOMAGICAL_BOARD_SESSIONS;
            case 16945:
                return f1.AUTOMAGICAL_BOARD_SESSIONS_REPIN;
            case 16946:
                return f1.AUTOMAGICAL_BOARD_SESSIONS_PIN_CLICK;
            case 16947:
                return f1.AUTOMAGICAL_BOARD_SESSIONS_PIN_SAVES;
            case 16948:
                return f1.AUTOMAGICAL_BOARD_SESSIONS_PIN_SHARES_COMPLETED;
            case 16949:
                return f1.AUTOMAGICAL_BOARD_BOARDS_VISITED;
            case 16950:
                return f1.AUTOMAGICAL_BOARD_BOARDS_PIN_REPIN;
            case 16951:
                return f1.AUTOMAGICAL_BOARD_BOARDS_PIN_CLICK;
            case 16952:
                return f1.AUTOMAGICAL_BOARD_BOARDS_PIN_5S_OUTBOUND_CLICKS;
            case 16953:
                return f1.AUTOMAGICAL_BOARD_BOARDS_PIN_OUTBOUND_CLICKS;
            case 16954:
                return f1.AUTOMAGICAL_BOARD_BOARDS_PIN_SAVES;
            case 16955:
                return f1.AUTOMAGICAL_BOARD_BOARDS_PIN_SHARES_COMPLETED;
            case 16956:
                return f1.AUTOMAGICAL_BOARD_BOARDS_TP_PIN_REPIN;
            case 16957:
                return f1.AUTOMAGICAL_BOARD_BOARDS_TP_PIN_CLICKS;
            case 16958:
                return f1.AUTOMAGICAL_BOARD_BOARDS_TP_PIN_5S_OUTBOUND_CLICKS;
            case 16959:
                return f1.AUTOMAGICAL_BOARD_BOARDS_TP_PIN_OUTBOUND_CLICKS;
            case 16960:
                return f1.AUTOMAGICAL_BOARD_BOARDS_TP_PIN_SAVES;
            case 16961:
                return f1.AUTOMAGICAL_BOARD_BOARDS_TP_PIN_SHARES_COMPLETED;
            case 16962:
                return f1.PIN_REP_EVENT_QUEUE_FALLBACK;
            case 16963:
                return f1.PIN_REP_EVENT_QUEUE_INTERRUPTED;
            case 16964:
                return f1.PIN_REP_EVENT_QUEUE_FULL;
            case 16965:
                return f1.NETWORK_OFFLINE;
            case 16966:
                return f1.NETWORK_ONLINE;
            case 16998:
                return f1.QCM_PIN_IMPRESSION_ONE_PIEXAL;
            case 16999:
                return f1.PIN_REP_EVENT_QUEUE_NULL;
            case 17004:
                return f1.NRT_AUTO_ORG_FAILURE;
            case 17021:
                return f1.PIN_CARTING_SHEET_LOAD;
            case 17022:
                return f1.PIN_CARTING_API_FAILURE;
            case 17041:
                return f1.QCM_PIN_IMPRESSION_ONE_PIXEL;
            case 17166:
                return f1.PIN_CARTING_RETAILER_CLICK;
            case 17170:
                return f1.CUSTOM_CHROME_TAB_ENGAGEMENT_SIGNAL;
            case 17171:
                return f1.QCM_METADATA_CLICK;
            case 17172:
                return f1.QCM_CTA_CLICK;
            case 17173:
                return f1.IDEA_PIN_METADATA_EXTRACTION_ATTEMPTED;
            case 17174:
                return f1.IDEA_PIN_METADATA_EXTRACTION_SUCCESS;
            case 17175:
                return f1.IDEA_PIN_METADATA_EXTRACTION_FAILURE;
            case 17176:
                return f1.PIN_CARTING_MDL_SUCCEEDED;
            case 17178:
                return f1.LOCAL_NOTIFICATION_SCHEDULE;
            case 17179:
                return f1.LOCAL_NOTIFICATION_DELETE;
            case 17180:
                return f1.LOCAL_NOTIFICATION_OPEN;
            case 17186:
                return f1.PIN_AD_DELIVERED;
            case 17187:
                return f1.PIN_AD_RENDERED;
            case 17188:
                return f1.PIN_IAB_INITIAL_URL_LOAD;
            case 17189:
                return f1.INSTAGRAM_ACCT_AUTO_ORG_PIN_SUCCESS;
            case 17190:
                return f1.INSTAGRAM_ACCT_AUTO_ORG_PIN_FAILURE;
            default:
                return null;
        }
    }
}
