package h32;

import com.pinterest.feature.core.view.RecyclerViewTypes;

/* loaded from: classes2.dex */
public final class e0 {
    public static g0 a(int i13) {
        if (i13 == 0) {
            return g0.FLOWED_PIN;
        }
        if (i13 == 1) {
            return g0.FLOWED_BOARD;
        }
        if (i13 == 3) {
            return g0.NEWS_FEED;
        }
        if (i13 == 4) {
            return g0.MODAL_PIN;
        }
        if (i13 == 69) {
            return g0.BOARD_INFO_BAR;
        }
        if (i13 == 70) {
            return g0.RELATED_PIN;
        }
        if (i13 == 85) {
            return g0.PIN_CLOSEUP_BODY;
        }
        if (i13 == 86) {
            return g0.PIN_CLOSEUP_RELATED_PINS;
        }
        if (i13 == 101) {
            return g0.CLOSEUP_INLINE_CAROUSEL;
        }
        if (i13 == 102) {
            return g0.CLOSEUP_LINK_MODULE;
        }
        if (i13 == 134) {
            return g0.PIN_CLOSEUP_RECIPE;
        }
        if (i13 == 135) {
            return g0.PIN_CLOSEUP_SOURCE_DESCRIPTION;
        }
        switch (i13) {
            case 7:
                return g0.MODAL_ADD_PIN;
            case 8:
                return g0.NAVIGATION;
            case 9:
                return g0.MODAL_DIALOG;
            case 10:
                return g0.USER_FEED;
            default:
                switch (i13) {
                    case 12:
                        return g0.MODAL_CREATE_BOARD;
                    case 13:
                        return g0.SHEET;
                    case 14:
                        return g0.EDUCATION;
                    default:
                        if (i13 == 172) {
                            return g0.USER_DID_IT_ACTIVITY;
                        }
                        if (i13 == 173) {
                            return g0.PIN_DID_IT_AGGREGATED_ACTIVITY;
                        }
                        if (i13 == 13028) {
                            return g0.MODAL_CONVERSATION_DISCOVERY;
                        }
                        if (i13 == 13029) {
                            return g0.SOCIAL_TYPEAHEAD_SUGGESTIONS;
                        }
                        if (i13 == 13048) {
                            return g0.HOMEFEED_REDO_NUX_NAVIGATION_HEADER;
                        }
                        if (i13 == 13049) {
                            return g0.PIN_CLOSEUP_RATING;
                        }
                        if (i13 == 13249) {
                            return g0.ANALYTICS_PIN_TABLE;
                        }
                        if (i13 == 13250) {
                            return g0.ANALYTICS_TIMESERIES_GRAPH;
                        }
                        switch (i13) {
                            case 17:
                                return g0.BROWSER;
                            case 18:
                                return g0.CONTEXTUAL_MENU;
                            case 19:
                                return g0.NAG;
                            case 20:
                                return g0.TOAST;
                            case 21:
                                return g0.WIDGET_ACTION_BAR;
                            default:
                                switch (i13) {
                                    case 27:
                                        return g0.LIST_HEADER;
                                    case 29:
                                        return g0.BOARD_PINS_GRID;
                                    case 35:
                                        return g0.TYPEAHEAD_SUGGESTIONS;
                                    case 43:
                                        return g0.SEARCH_BOX;
                                    case 50:
                                        return g0.PINNER_CAROUSEL;
                                    case 55:
                                        return g0.CONVERSATION_MESSAGES;
                                    case 58:
                                        return g0.PIN_FEEDBACK_DIALOG_PFY;
                                    case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_NOTE_AND_FAVORITE_MODULE /* 99 */:
                                        return g0.BUYABLE_PINS_CAROUSEL;
                                    case RecyclerViewTypes.VIEW_TYPE_PIN_PDP_MONOLITH_HEADER /* 107 */:
                                        return g0.PIN_FEEDBACK_DIALOG_FOLLOWING;
                                    case RecyclerViewTypes.VIEW_TYPE_TV_SCHEDULE_EPISODE /* 111 */:
                                        return g0.PIN_FEEDBACK_DIALOG_INTEREST;
                                    case RecyclerViewTypes.VIEW_TYPE_SCHEDULED_PIN_CELL /* 113 */:
                                        return g0.PIN_FEEDBACK_DIALOG_BOARD;
                                    case RecyclerViewTypes.VIEW_TYPE_CAROUSEL_SINGLE_COLUMN /* 117 */:
                                        return g0.EDUCATION_TOOLTIP_POPUP;
                                    case RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL /* 138 */:
                                        return g0.PIN_CLOSEUP_TITLE;
                                    case RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL_ITEM_HIDDEN /* 141 */:
                                        return g0.PASSWORD_RESET_PAGE;
                                    case RecyclerViewTypes.VIEW_TYPE_ARTICLE_CAROUSEL_ITEM_IMAGE /* 143 */:
                                        return g0.PIN_CLOSEUP_VARIANT_SELECTOR;
                                    case RecyclerViewTypes.VIEW_TYPE_STANDARD_FILTER_ITEM /* 153 */:
                                        return g0.SEND_SHARE;
                                    case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_VIDEO_FULL_SPAN /* 175 */:
                                        return g0.PIN_CLOSEUP_DID_IT;
                                    case RecyclerViewTypes.VIEW_TYPE_GMA_INLINE_AD_FULL_SPAN /* 179 */:
                                        return g0.PIN_CLOSEUP_VIDEO;
                                    case RecyclerViewTypes.VIEW_TYPE_LENS_DIRECTORY /* 192 */:
                                        return g0.DID_IT_MODAL_FULL_SHEET;
                                    case RecyclerViewTypes.VIEW_TYPE_OVERSCROLL_SEARCH_CELL /* 194 */:
                                        return g0.PIN_CLOSEUP_ACTION;
                                    case 200:
                                        return g0.DYNAMIC_GRID_STORY;
                                    case RecyclerViewTypes.VIEW_TYPE_COUNTRY_CODE /* 223 */:
                                        return g0.USER_FOLLOWERS;
                                    case RecyclerViewTypes.VIEW_TYPE_STORY_SELECT_OR_REORDER_PINS /* 225 */:
                                        return g0.TILTED_PINS_HEADER;
                                    case RecyclerViewTypes.VIEW_TYPE_BOARD_MORE_IDEAS_UPSELL_CARD /* 236 */:
                                        return g0.PIN_STORY_PIN_OOPS_PAGE;
                                    case RecyclerViewTypes.VIEW_TYPE_HOME_FEED_TUNER_SETTINGS_NOTIFICATION /* 244 */:
                                        return g0.BUSINESS_HUB_LINK;
                                    case 13011:
                                        return g0.PIN_CLOSEUP_COMMERCE_HEADER;
                                    case 13025:
                                        return g0.PIN_CREATE_BOARD_PICKER;
                                    case 13039:
                                        return g0.SHOWCASE;
                                    case 13056:
                                        return g0.PROFILE_HEADER;
                                    case 13065:
                                        return g0.PIN_CLOSEUP_USER_BOARD_NOTE_ATTRIBUTION;
                                    case 13077:
                                        return g0.PIN_CLOSEUP_PIN_ANALYTICS;
                                    case 13134:
                                        return g0.INSIGHTS_INTEREST_TABLE;
                                    case 13140:
                                        return g0.OVERFLOW_MENU;
                                    case 13176:
                                        return g0.PIN_CLOSEUP_RELATED_PRODUCTS;
                                    case 13179:
                                        return g0.MODAL_REPORT_MENU;
                                    case 13182:
                                        return g0.PROFILE_PIN_REP_VIEW_TYPE_TOGGLE;
                                    case 13184:
                                        return g0.TAB_CAROUSEL;
                                    case 13195:
                                        return g0.INSIGHTS_LOCATION_TABLE;
                                    case 13204:
                                        return g0.BOARD_IDEAS;
                                    case 13255:
                                        return g0.ANALYTICS_DATE_MENU;
                                    case 13256:
                                        return g0.ANALYTICS_PREVIEW_PIN_TABLE;
                                    case 13257:
                                        return g0.ANALYTICS_FILTER_MENU;
                                    case 13258:
                                        return g0.ANALYTICS_MOBILE_HEADER;
                                    case 13259:
                                        return g0.ANALYTICS_TOPLINE_METRIC;
                                    case 13260:
                                        return g0.ANALYTICS_TABS;
                                    case 13283:
                                        return g0.PIN_CLOSEUP;
                                    case 13320:
                                        return g0.ADD_ACCOUNT_BUTTON;
                                    case 13321:
                                        return g0.PIN_CLOSEUP_RELATED_RECIPES;
                                    case 13322:
                                        return g0.USER_STORY_PINS;
                                    case 13327:
                                        return g0.PIN_CLOSEUP_BRAND_CATALOG;
                                    case 13367:
                                        return g0.NOTICE;
                                    case 13369:
                                        return g0.ACCOUNT_SWITCHER;
                                    case 13391:
                                        return g0.VIDEO_END_OVERLAY;
                                    case 13430:
                                        return g0.HOMEFEED_RELEVANCE_MULTIPIN_QUESTION;
                                    case 13458:
                                        return g0.PIN_CLOSEUP_REACTION_COUNTS;
                                    case 13464:
                                        return g0.PIN_CLOSEUP_COMMENTS;
                                    case 13468:
                                        return g0.SHOPPING_PRICE_FILTER;
                                    case 13469:
                                        return g0.SHOPPING_BRAND_FILTER;
                                    case 13470:
                                        return g0.PIN_CLOSEUP_RELATED_PRODUCTS_VIRTUAL_TRY_ON;
                                    case 13471:
                                        return g0.LOCATION_PRE_PERMISSION_FULL_SCREEN_COMPONENT;
                                    case 13474:
                                        return g0.PIN_CLOSEUP_STL_MODULE;
                                    case 13475:
                                        return g0.SORT_BOARD_PINS_SELECTLIST;
                                    case 13477:
                                        return g0.ANALYTICS_TOP_BOARDS;
                                    case 13480:
                                        return g0.BIZ_ONBOARDING_BUILD_PROFILE;
                                    case 13481:
                                        return g0.BIZ_ONBOARDING_CREATE_PIN;
                                    case 13482:
                                        return g0.BIZ_ONBOARDING_CREATE_AD;
                                    case 13487:
                                        return g0.SHOPPING_BRAND_AFFINITY_STORY_GRID;
                                    case 13488:
                                        return g0.SHOPPING_BRAND_AFFINITY_STORY_CARD;
                                    case 13525:
                                        return g0.TODAY_ARTICLE;
                                    case 13535:
                                        return g0.SHOPPING_CATEGORY_FILTER;
                                    case 13557:
                                        return g0.PIN_IDEA_STREAM;
                                    case 13583:
                                        return g0.NEWS_HUB_BACK_TO_HOMEFEED_BUTTON;
                                    case 13585:
                                        return g0.CONVERSATION_GIF_REACTION_TRAY;
                                    case 13586:
                                        return g0.CONVERSATION_SEND_A_PIN_USER_EMPTY_STATE;
                                    case 13587:
                                        return g0.CONVERSATION_SEND_A_PIN_RELATED_PINS_EMPTY_STATE;
                                    case 13596:
                                        return g0.PIN_THUMBNAIL_CAROUSEL;
                                    case 13597:
                                        return g0.PIN_CLOSEUP_PRODUCT_DETAILS;
                                    case 13598:
                                        return g0.SHOPPING_SORT_FILTER;
                                    case 13601:
                                        return g0.MODULE_IDEA_STREAM;
                                    case 13617:
                                        return g0.INBOX_NOTIFS_OPT_IN_BANNER_VIEW_UPSELL;
                                    case 13620:
                                        return g0.SHARESHEET_NOTIFS_OPT_IN_BANNER_VIEW_UPSELL;
                                    case 13661:
                                        return g0.TODAY_ARTICLE_FOLLOWING_MODULE;
                                    case 13662:
                                        return g0.TODAY_ARTICLE_SECTION_FOLLOWING_MODULE;
                                    case 13668:
                                        return g0.CREATED_TAB;
                                    case 13669:
                                        return g0.SAVED_TAB;
                                    case 13670:
                                        return g0.SHOP_TAB;
                                    case 13671:
                                        return g0.TRIES_TAB;
                                    case 13672:
                                        return g0.USER_FOLLOW;
                                    case 13673:
                                        return g0.USER_CONTACT;
                                    case 13674:
                                        return g0.CONTACT_SHEET;
                                    case 13675:
                                        return g0.USER_SEND;
                                    case 13676:
                                        return g0.ALL_PINS_REP;
                                    case 13680:
                                        return g0.PIN_CLOSEUP_RELATED_MODULE;
                                    case 13696:
                                        return g0.AGGREGATED_COMMENT_NONREPLY;
                                    case 13697:
                                        return g0.AGGREGATED_COMMENT_REPLY;
                                    case 13713:
                                        return g0.ENGAGEMENT_LIST;
                                    case 13717:
                                        return g0.SHOPPING_SURVEY_BANNER;
                                    case 13718:
                                        return g0.BOARD_TOOLS_CONTAINER;
                                    case 13737:
                                        return g0.SHOPPING_SURVEY_BANNER_FOLLOW_UP;
                                    case 13738:
                                        return g0.SHOPPING_SURVEY_BANNER_THANK_YOU;
                                    case 13739:
                                        return g0.VIRTUAL_TRY_ON_LIPSTICK;
                                    case 13740:
                                        return g0.VIRTUAL_TRY_ON_EYESHADOW;
                                    case 13756:
                                        return g0.PIN_AD_TARGETING_REASONS_DIALOG;
                                    case 13760:
                                        return g0.CLICKTHROUGH_SATIFACTION_EXPERIENCE;
                                    case 13765:
                                        return g0.EDIT_SETTINGS_PAGE;
                                    case 13769:
                                        return g0.PIN_CLOSEUP_PIN_NOTE;
                                    case 13772:
                                        return g0.BOARD_SECTION_TEMPLATE_SUGGESTION;
                                    case 13773:
                                        return g0.BOARD_SECTION_TEMPLATE_PIN_PICKER_DONE_BUTTON;
                                    case 13777:
                                        return g0.PROFILE_STORY_PIN_FEED;
                                    case 13781:
                                        return g0.AGGREGATED_COMMENT_DIDIT;
                                    case 13789:
                                        return g0.CAMERA_PERMISSIONS;
                                    case 13790:
                                        return g0.PHOTO_LIBRARY_PERMISSIONS;
                                    case 13791:
                                        return g0.PIN_CLOSEUP_BOARD_FAVORITE_MODULE;
                                    case 13798:
                                        return g0.USER_REP;
                                    case 13801:
                                        return g0.PIN_STORY_PIN_BODY;
                                    case 13802:
                                        return g0.STORY_PIN_STATS_MODULE;
                                    case 13803:
                                        return g0.PIN_CLOSEUP_SKIN_TONE_FILTER;
                                    case 13804:
                                        return g0.SAVING_REPIN_TOAST;
                                    case 13806:
                                        return g0.NOTIFICATION_FILTERS_EMPTY_STATE;
                                    case 13810:
                                        return g0.PIN_CLOSEUP_NOTE_AND_FAVORITE_MODULE;
                                    case 13811:
                                        return g0.WISHLIST_SHOP_YOUR_PRODUCTS_STORY;
                                    case 13812:
                                        return g0.CREATOR_BUBBLE_EDUCATION_PAGE;
                                    case 13814:
                                        return g0.STORY_PIN_MISSING_PERMISSIONS_VIEW;
                                    case 13839:
                                        return g0.STORY_PIN_CREATE_FINISHING_TOUCHES;
                                    case 13840:
                                        return g0.DISCOVER_CREATORS_PORTAL;
                                    case 13843:
                                        return g0.USER_RECENTLY_VIEWED_PINS_STORY;
                                    case 13844:
                                        return g0.USER_RECENTLY_SAVED_PINS_STORY;
                                    case 13860:
                                        return g0.SENSITIVITY_SCREEN;
                                    case 13861:
                                        return g0.SENSITIVITY_SCREEN_PROFILE_BOARD;
                                    case 13862:
                                        return g0.EDIT_COVER;
                                    case 13863:
                                        return g0.SKIN_TONE_FILTERS;
                                    case 13864:
                                        return g0.HAIR_PATTERN_FILTERS;
                                    case 13865:
                                        return g0.CURATED_ARTICLE;
                                    case 13868:
                                        return g0.RECENTLY_VIEWED_PRODUCTS_STORY;
                                    case 13875:
                                        return g0.USER_MENTION;
                                    case 13876:
                                        return g0.SPONSOR_TAG;
                                    case 13877:
                                        return g0.REMOVE_SPONSORSHIP_MODAL;
                                    case 13887:
                                        return g0.LIVE_SESSIONS_UPCOMING_SESSIONS_CAROUSEL;
                                    case 13891:
                                        return g0.SUGGESTED_CREATORS_MODULE;
                                    case 13892:
                                        return g0.USER_UNFOLLOW_MODAL;
                                    case 13895:
                                        return g0.FLOATING_COMMENT_VIEW;
                                    case 13902:
                                        return g0.LIVE_SESSIONS_SEARCH_UPSELL_CAROUSEL;
                                    case 13912:
                                        return g0.PIN_STORY_PIN_AD_PAGE;
                                    case 13923:
                                        return g0.CREATOR_HUB_NEWS_ITEM;
                                    case 13924:
                                        return g0.CREATOR_HUB_PIN;
                                    case 13925:
                                        return g0.HIGHLIGHTED_TAKES_EMPTY_STATE;
                                    case 13926:
                                        return g0.HIGHLIGHTED_TAKES;
                                    case 13938:
                                        return g0.WATCH_TAB_EMPTY_STATE;
                                    case 13946:
                                        return g0.MESSAGE_FLYOUT;
                                    case 13947:
                                        return g0.PIN_LIVE_SESSION_BODY;
                                    case 13963:
                                        return g0.IDEA_PIN_STICKER_TOP_PICKS;
                                    case 13964:
                                        return g0.IDEA_PIN_STICKER_INTERACTIVE;
                                    case 13965:
                                        return g0.IDEA_PIN_STICKER_CATEGORY;
                                    case 13966:
                                        return g0.IDEA_PIN_STICKER_EVERGREEN;
                                    case 13967:
                                        return g0.IDEA_PIN_STICKER_RECENTLY_USED;
                                    case 13969:
                                        return g0.CALL_TO_CREATE_TAKES_CAROUSEL;
                                    case 13970:
                                        return g0.CALL_TO_CREATE_TAKES_STACK;
                                    case 13975:
                                        return g0.IDEA_PIN_COMMENT_REPLY_STACK;
                                    case 13988:
                                        return g0.HEADER;
                                    case 13991:
                                        return g0.STRUCTURED_FEED_DEFAULT_COMPONENT_TYPE;
                                    case 13992:
                                        return g0.ITEM_REP_DEFAULT_COMPONENT_TYPE;
                                    case 14005:
                                        return g0.CREATOR_FUND_ELIGIBILITY_PATHWAY;
                                    case 14011:
                                        return g0.ABOUT_DRAWER;
                                    case 14012:
                                        return g0.PIN_CLOSEUP_PRODUCT_VIDEO;
                                    case 14016:
                                        return g0.USER_SIGNALS_MODAL;
                                    case 14017:
                                        return g0.USER_SIGNALS_FULL_SCREEN;
                                    case 14023:
                                        return g0.USER_PROFILE_EDIT_FIELD_CARD;
                                    case 14026:
                                        return g0.SHOP_TAB_UPSELL;
                                    case 14039:
                                        return g0.IDEA_PIN_BOARD_STICKER_PICKER;
                                    case 14045:
                                        return g0.LIVE_SESSION_PRODUCT_REVEAL;
                                    case 14046:
                                        return g0.ONEBAR_CONTAINER;
                                    case 14047:
                                        return g0.ONEBAR_MODULE;
                                    case 14048:
                                        return g0.ONEBAR_DRAWER;
                                    case 14050:
                                        return g0.MULTI_FACTOR_AUTHENTICATION;
                                    case 14055:
                                        return g0.USER_BIRTHDAY_PROMPT;
                                    case 14056:
                                        return g0.USER_BIRTHDAY_COLLECTION;
                                    case 14074:
                                        return g0.STRUCTURED_FEED_MORE_IDEAS_CAROUSEL;
                                    case 14108:
                                        return g0.YOUR_SHOP_EXPLODED_SPOTLIGHT_MODULE;
                                    case 14121:
                                        return g0.SEND_SHARE_MAIN;
                                    case 14122:
                                        return g0.SEND_SHARE_CONTEXTUAL;
                                    case 14123:
                                        return g0.SEND_SHARE_UPSELL;
                                    case 14128:
                                        return g0.CONFIRM_USER_BIRTHDAY_PROMPT;
                                    case 14129:
                                        return g0.USER_POST_DELETION_PROMPT;
                                    case 14144:
                                        return g0.LANGUAGE_MAIN_MENU;
                                    case 14145:
                                        return g0.LANGUAGE_DEFAULT_MENU;
                                    case 14146:
                                        return g0.LANGUAGE_ADDITIONAL_MENU;
                                    case 14147:
                                        return g0.SEND_SHARE_DIRECT;
                                    case 14170:
                                        return g0.PIN_LIVE_SESSION_STREAM;
                                    case 14173:
                                        return g0.TV_REPLAY_EPISODE;
                                    case 14174:
                                        return g0.TV_UPCOMING_EPISODE;
                                    case 14175:
                                        return g0.TV_LIVE_EPISODE;
                                    case 14183:
                                        return g0.EMPTY_SEARCH_RESULT;
                                    case 14186:
                                        return g0.PIN_CLOSEUP_PRODUCT_CAROUSEL;
                                    case 14200:
                                        return g0.BOARD_MORE_IDEAS_HEADER;
                                    case 14201:
                                        return g0.LIVE_SESSIONS_FEATURED_LIVE_CAROUSEL;
                                    case 14202:
                                        return g0.LIVE_SESSIONS_FEATURED_REPLAYS_CAROUSEL;
                                    case 14203:
                                        return g0.LIVE_SESSIONS_FEATURED_SECONDARY_REPLAYS_CAROUSEL;
                                    case 14209:
                                        return g0.CREATOR_HUB_RECENT_PINS_EMPTY_STATE;
                                    case 14266:
                                        return g0.ADS_ONLY_CAROUSEL;
                                    case 14270:
                                        return g0.MESSAGING_PERMISSIONS_FRIENDS;
                                    case 14271:
                                        return g0.MESSAGING_PERMISSIONS_FOLLOWERS;
                                    case 14272:
                                        return g0.MESSAGING_PERMISSIONS_FOLLOWEES;
                                    case 14273:
                                        return g0.MESSAGING_PERMISSIONS_CONTACTS;
                                    case 14274:
                                        return g0.MESSAGING_PERMISSIONS_OTHERS;
                                    case 14284:
                                        return g0.PIN_CLOSEUP_PRODUCT_TITLE;
                                    case 14285:
                                        return g0.HAIR_PATTERN_FILTERS_REMEBER_DIALOG;
                                    case 14286:
                                        return g0.SKIN_TONE_FILTERS_REMEBER_DIALOG;
                                    case 14307:
                                        return g0.AD_LEAD_FORM_SIGNUP;
                                    case 14308:
                                        return g0.AD_LEAD_FORM_SIGNUP_SUCCESS;
                                    case 14315:
                                        return g0.SEND_SHARE_CONTACT_SUGGESTIONS;
                                    case 14324:
                                        return g0.RANGE_FILTER;
                                    case 14325:
                                        return g0.MULTI_SELECT_FILTER;
                                    case 14326:
                                        return g0.SINGLE_SELECT_FILTER;
                                    case 14328:
                                        return g0.PIN_CLOSEUP_DETAILS;
                                    case 14332:
                                        return g0.AD_QUIZ_PIN_QUESTIONNAIRE;
                                    case 14333:
                                        return g0.AD_QUIZ_PIN_RESULT;
                                    case 14334:
                                        return g0.AD_QUIZ_PIN_FALLBACK;
                                    case 14339:
                                        return g0.STELA_PRODUCTS;
                                    case 14341:
                                        return g0.PIN_CLOSEUP_YOUTUBE;
                                    case 14347:
                                        return g0.DEEP_LINK;
                                    case 14348:
                                        return g0.COMMENT_COMPOSER;
                                    case 14354:
                                        return g0.HOME_FEED_EMPTY_STATE;
                                    case 14364:
                                        return g0.MULTI_TOPIC_INTEREST_RECOMMENDATIONS_STORY;
                                    case 14365:
                                        return g0.RVC_APPEAL_MODAL;
                                    case 14366:
                                        return g0.RVC_ENFORCEMENT_ACTION_ROW;
                                    case 14367:
                                        return g0.RVC_ENFORCEMENT_ACTION_CONTEXT_MENU;
                                    case 14372:
                                        return g0.PARENTAL_PASSCODE_SETTINGS_EDIT;
                                    case 14373:
                                        return g0.PARENTAL_PASSCODE_SETTINGS_VIEW;
                                    case 14374:
                                        return g0.PASSCODE_REQUIRED_MODAL;
                                    case 14381:
                                        return g0.COMMENT_FEED;
                                    case 14384:
                                        return g0.LIVE_SESSION_PIN_PREVIEW;
                                    case 14395:
                                        return g0.PIN_CLOSEUP_MACHINE_TRANSLATIONS;
                                    case 14396:
                                        return g0.RECENTLY_SAVED_PRODUCTS_STORY;
                                    case 14405:
                                        return g0.BEST_SELLING_FOLLOWING_BRAND_PRODUCTS_STORY;
                                    case 14409:
                                        return g0.QUICK_SAVE_TOAST;
                                    case 14413:
                                        return g0.SAVES_USER_COMPREHENSION_FIRST_DIALOG;
                                    case 14414:
                                        return g0.SAVES_USER_COMPREHENSION_GOT_IT;
                                    case 14415:
                                        return g0.SAVES_USER_COMPREHENSION_SECOND_DIALOG;
                                    case 14416:
                                        return g0.SAVES_USER_COMPREHENSION_MAYBE_LATER;
                                    case 14417:
                                        return g0.SAVES_USER_COMPREHENSION_CREATE_BOARD;
                                    case 14418:
                                        return g0.SAVES_USER_COMPREHENSION_PICK_PINS;
                                    case 14419:
                                        return g0.NEWSHUB_SEARCH_RECOMMENDATIONS_STORY;
                                    case 14420:
                                        return g0.NEWSHUB_BOARD_RECOMMENDATIONS_STORY;
                                    case 14451:
                                        return g0.BEST_SELLING_RECOMMENDED_BRAND_PRODUCTS_STORY;
                                    case 14456:
                                        return g0.PARENTAL_PASSCODE_DISABLING;
                                    case 14460:
                                        return g0.PINS_TAB;
                                    case 14461:
                                        return g0.BOARDS_TAB;
                                    case 14462:
                                        return g0.PROFILE_VISIBILITY_INFO_MODAL;
                                    case 14463:
                                        return g0.PROFILE_VISIBILITY_EDUCATION_POPUP;
                                    case 14464:
                                        return g0.IDEA_PIN_DISPLAY;
                                    case 14485:
                                        return g0.BODY_TYPE_FILTERS_REMEMBER_DIALOG;
                                    case 14486:
                                        return g0.PIN_EDIT_LINK_ENGAGEMENT_METRICS_RESET_MODAL;
                                    case 14766:
                                        return g0.PEAR_SURVEY;
                                    case 14767:
                                        return g0.SHOP_THE_BOARD_PRODUCTS_STORY;
                                    case 14768:
                                        return g0.ON_SALE_PRODUCTS_STORY;
                                    case 14769:
                                        return g0.PRODUCT_CATEGORY_BASED_PRODUCTS_STORY;
                                    case 14780:
                                        return g0.REQUEST_DATA_UI;
                                    case 14786:
                                        return g0.BUSINESS_PRIVATE_PROFILE_MODAL;
                                    case 14787:
                                        return g0.PEAR_STYLE_PILLS;
                                    case 14792:
                                        return g0.PEAR_STYLE_PIVOT;
                                    case 14793:
                                        return g0.PEAR_BOARD;
                                    case 14794:
                                        return g0.SEND_SHARE_INVITE_PRIVATE_PROFILE;
                                    case 14795:
                                        return g0.PRIVATE_PROFILE_HEADER;
                                    case 14796:
                                        return g0.PRIVATE_PROFILE_POST_FOLLOW_MODAL_SHARE_PROFILE;
                                    case 14797:
                                        return g0.PRIVATE_PROFILE_POST_FOLLOW_MODAL_SEND_MESSAGE;
                                    case 14801:
                                        return g0.COLLAGE_DRAFTS_LARGE_PROMPT;
                                    case 14811:
                                        return g0.COLLAGE_COMPOSER_ONBOARDING;
                                    case 14815:
                                        return g0.SHOP_SEARCH_PRODUCTS_STORY;
                                    case 14823:
                                        return g0.RELATED_PINS_FILTERS_CAROUSEL;
                                    case 14824:
                                        return g0.RELATED_PINS_FILTERED_FEED_FOOTER;
                                    case 14828:
                                        return g0.COMPLETE_THE_LOOK_STORY;
                                    case 14866:
                                        return g0.PEAR_RELATED_TOPIC;
                                    case 14868:
                                        return g0.COLLAGE_COMPOSER_CUTOUT_PICKER_PIN_CLOSEUP;
                                    case 14869:
                                        return g0.COLLAGE_COMPOSER_CUTOUT_PICKER_PIN_CLOSEUP_RELATED_PINS;
                                    case 14870:
                                        return g0.SEND_SHARE_INSTAGRAM;
                                    case 14871:
                                        return g0.ANKET_MODAL_SURVEY;
                                    case 14872:
                                        return g0.ANKET_INLINE_SURVEY;
                                    case 14883:
                                        return g0.PIN_DOUBLE_TAP_DELETE_SHEET;
                                    case 14926:
                                        return g0.TOOLBAR;
                                    case 14934:
                                        return g0.REPIN_ANIMATION;
                                    case 14935:
                                        return g0.PIN_CLOSEUP_HAIR_PATTERN_FILTER;
                                    case 14937:
                                        return g0.PEAR_QUIZ_ENTRY_POINT;
                                    case 14938:
                                        return g0.PEAR_RELATED_AESTHETICS;
                                    case 14939:
                                        return g0.PEAR_SIGNATURE_PIECES;
                                    case 14940:
                                        return g0.PEAR_QUIZ_RESULTS_HERO_SECTION;
                                    case 14941:
                                        return g0.PEAR_MORE_IDEAS_SECTION;
                                    case 14949:
                                        return g0.VIDEO_PICTURE_IN_PICTURE;
                                    case 14950:
                                        return g0.RECOMMENDED_BOARDS;
                                    case 14953:
                                        return g0.SHARE_SCREEN_EDIT_PIN_PICKER;
                                    case 14958:
                                        return g0.BOUNCED_EMAIL_COLLECTION_MODAL;
                                    case 14959:
                                        return g0.LINK_GOOGLE_MODAL;
                                    case 14960:
                                        return g0.CREATE_PASSWORD_MODAL;
                                    case 14964:
                                        return g0.SHARE_SCREEN_EDIT_TEMPLATE;
                                    case 14971:
                                        return g0.PARENTAL_PASSCODE_UNIDIRECTIONAL_ALERT;
                                    case 14980:
                                        return g0.COLLAGE_COMPOSER_CAROUSEL;
                                    case 14982:
                                        return g0.COLLAGE_COMPOSER_ITEM_OPTIONS_MENU;
                                    case 14984:
                                        return g0.MERCHANT_MULTI_SELECT;
                                    case 14988:
                                        return g0.COLLAGE_COMPOSER_REMIXES_UPSELL_MODAL;
                                    case 14997:
                                        return g0.BOARD_MORE_IDEAS_ENDLESS_SCROLL;
                                    case 14998:
                                        return g0.RECONSIDERATION_PRODUCTS_STORY;
                                    case 14999:
                                        return g0.PRODUCT_CATEGORY_ON_SALE_PRODUCTS_STORY;
                                    case 15000:
                                        return g0.BEST_SELLING_PRODUCT_CATEGORY_PRODUCTS_STORY;
                                    case 15002:
                                        return g0.MORE_IDEAS_ONE_BAR;
                                    case 15004:
                                        return g0.SEE_IT_STYLED;
                                    case 15012:
                                        return g0.STYLE_AND_PC_STORY;
                                    case 15016:
                                        return g0.RELATED_PINS_FILTERED_FEED_EMPTY_STATE;
                                    case 15018:
                                        return g0.BRAND_MULTI_SELECT;
                                    case 15035:
                                        return g0.CURATED_BOARD;
                                    case 15036:
                                        return g0.LINK_GOOGLE_PERSISTENT_BANNER;
                                    case 15037:
                                        return g0.CREATE_PASSWORD_PERSISTENT_BANNER;
                                    case 15044:
                                        return g0.CONFIRM_DELETE_BOARD_HEADER_SHEET;
                                    case 15053:
                                        return g0.RECOMMENDED_BOARD_MODULE;
                                    case 15064:
                                        return g0.ON_SALE_CLOSEUP_PRODUCTS_STORY;
                                    case 15065:
                                        return g0.ON_SALE_SEARCH_PRODUCTS_STORY;
                                    case 15068:
                                        return g0.PIN_CLOSEUP_SOCIAL_INSIGHT;
                                    case 15085:
                                        return g0.COLLAGES_TAB;
                                    case 15088:
                                        return g0.BOARD_SHOP_MODULE;
                                    case 15089:
                                        return g0.SHOP_TOOL_STL_MODULE;
                                    case 15111:
                                        return g0.RELATED_QUERY_SHOP_UPSELL;
                                    case 15121:
                                        return g0.FILTER_ERROR_STATE;
                                    case 15127:
                                        return g0.ONE_TAP_SAVE_TOAST;
                                    case 15128:
                                        return g0.ONE_TAP_DELETE_TOAST;
                                    case 15131:
                                        return g0.FILTER_ERROR_STATE_EOF;
                                    case 15136:
                                        return g0.ADS_STL_CATEGORY;
                                    case 15137:
                                        return g0.ADS_STL_HEADER;
                                    case 15139:
                                        return g0.PIN_CLOSEUP_ADS_STL_MODULE;
                                    case 15140:
                                        return g0.ADS_STL_SHEET;
                                    case 15141:
                                        return g0.AD_ACCOUNT_SETTINGS_URL_BUILDER;
                                    case 15142:
                                        return g0.AD_GROUP_URL_BUILDER;
                                    case 15143:
                                        return g0.PERFORMANCE_PLUS_AD_GROUP_URL_PARAMS_SECTION;
                                    case 15144:
                                        return g0.SAVE_AND_APPLY_URL_PARAMS_MODAL;
                                    case 15146:
                                        return g0.PERFORMANCE_PLUS_AD_GROUP_TARGETING_SECTION;
                                    case 15147:
                                        return g0.PIN_STATS_PIN_PERFORMANCE_CONTAINER;
                                    case 15148:
                                        return g0.PIN_STATS_TAGGED_PRODUCTS_TABLE;
                                    case 15153:
                                        return g0.BUSINESS_ACCESS_SELECT_PEOPLE_FOR_EMPLOYEES_SHEET;
                                    case 15154:
                                        return g0.BUSINESS_ACCESS_SELECT_ASSETS_OWNERS_SHEET;
                                    case 15155:
                                        return g0.BUSINESS_ACCESS_SELECT_ASSETS__SHEET;
                                    case 15156:
                                        return g0.BUSINESS_ACCESS_RELATIONSHIP_ASSET_SUMMARY_SHEET;
                                    case 15160:
                                        return g0.RICH_COMMENT_MENU;
                                    case 15162:
                                        return g0.SHOP_TOOL_SAVED_PRODUCTS_MODULE;
                                    case 15163:
                                        return g0.PERFORMANCE_PLUS_AD_GROUP_NAME_SECTION;
                                    case 15164:
                                        return g0.COLLAGE_COMPOSER_TAB_CAROUSEL;
                                    case 15165:
                                        return g0.LANDING_PAGE_HERO_HEADER;
                                    case 15166:
                                        return g0.WEB_AD_DL_COLLECTION;
                                    case 15167:
                                        return g0.MOVE_GOOGLE_LOGIN;
                                    case 15168:
                                        return g0.BOARD_ALLOW_SHOP_MODULE;
                                    case 15170:
                                        return g0.CONFIRM_EMAIL_UPDATE_MODAL;
                                    case 15171:
                                        return g0.EMAIL_UPDATE_MODAL;
                                    case 15173:
                                        return g0.PINNY_RELATED_QUESTION_OPTION;
                                    case 15174:
                                        return g0.PINNY_RELATED_QUESTIONS_CONTAINER;
                                    case 15175:
                                        return g0.PINNY_RELATED_QUESTION_DRILLDOWN;
                                    case 15176:
                                        return g0.PINNY_RELATED_QUESTIONS_DROPDOWN;
                                    case 15180:
                                        return g0.USE_CASE_FEED;
                                    case 15181:
                                        return g0.CAMPAIGN_URL_BUILDER;
                                    case 15182:
                                        return g0.CREATE_FLOW_CAMPAIGN_URL_PARAMETER_SECTION;
                                    case 15183:
                                        return g0.PEAR_QUIZ_BOARD_FEED;
                                    case 15191:
                                        return g0.PROMOTIONS_UPSELL_MODAL;
                                    case 15192:
                                        return g0.PROMOTIONS_UPSELL_BANNER;
                                    case 15193:
                                        return g0.COLLAGE_COMPOSER_LAYERS_TOOLBAR_MENU;
                                    case 15197:
                                        return g0.NUVEM_CONNECT;
                                    case 15198:
                                        return g0.NUVEM_SETTINGS;
                                    case 15204:
                                        return g0.WELCOME_EXPERIENCE_HEADING;
                                    case 15205:
                                        return g0.WELCOME_EXPERIENCE_TOOLTIP;
                                    case 15206:
                                        return g0.FEATURED_HOLIDAY_BOARD_MODULE;
                                    case 15207:
                                        return g0.RECOVER_ACCOUNT_VIEW;
                                    case 15208:
                                        return g0.EU_PERSONALIZED_ADS_PROMPT;
                                    case 15209:
                                        return g0.UPSELL_URL_BUILDER;
                                    case 15210:
                                        return g0.URL_PARAMETER_UPSELL_BANNER;
                                    case 15213:
                                        return g0.SHOP_TOOL_PRODUCT_CATEGORY_MODULE;
                                    case 15214:
                                        return g0.FB_RECOVER_LOGIN_FORM;
                                    case 15215:
                                        return g0.RESET_CONFIRMATION_MODAL;
                                    case 15219:
                                        return g0.SEND_SHARE_FACEBOOK;
                                    case 15220:
                                        return g0.PIN_CLOSEUP_AFFILIATE_DISCLAIMER;
                                    case 15221:
                                        return g0.PROMO_SUCCESSFULLY_APPLIED_TOAST;
                                    case 15222:
                                        return g0.PROMO_SUCCESSFULLY_CREATED_TOAST;
                                    case 15223:
                                        return g0.PROMO_APPLY_FAILURE_TOAST;
                                    case 15224:
                                        return g0.PROMO_CREATE_FAILURE_TOAST;
                                    case 15225:
                                        return g0.STRUCTURED_FEED_FULL_FEED_EMPTY_STATE;
                                    case 15226:
                                        return g0.STRUCTURED_FEED_END_OF_FEED_EMPTY_STATE;
                                    case 15230:
                                        return g0.CATALOGS_OVERVIEW_PAGE;
                                    case 15231:
                                        return g0.CATALOGS_OVERVIEW_PAGE_ADS_CREDIT_UPSELL;
                                    case 15232:
                                        return g0.CATALOGS_OVERVIEW_PAGE_BEST_PRACTICES_CARD;
                                    case 15233:
                                        return g0.CATALOGS_OVERVIEW_CONVERSION_UPSELL;
                                    case 15234:
                                        return g0.CATALOGS_OVERVIEW_DIAGNOSTICS_WIDGET;
                                    case 15235:
                                        return g0.CATALOGS_OVERVIEW_ANALYTICS_WIDGET;
                                    case 15236:
                                        return g0.CATALOGS_OVERVIEW_APPROVED_PAGE;
                                    case 15237:
                                        return g0.CATALOGS_OVERVIEW_NOT_APPROVED_PAGE;
                                    case 15238:
                                        return g0.CATALOGS_OVERVIEW_ONBOARDING_PAGE;
                                    case 15239:
                                        return g0.CATALOGS_OVERVIEW_UNDER_REVIEW_PAGE;
                                    case 15240:
                                        return g0.CATALOGS_OVERVIEW_PROMOTE_YOUR_PRODUCTS_WIDGET;
                                    case 15241:
                                        return g0.CATALOGS_OVERVIEW_SHOPPING_SUCCESS_STORY_CARD;
                                    case 15242:
                                        return g0.ORDERLINE_MIGRATION_EDIT_SCHEDULE_OVERLAY;
                                    case 15243:
                                        return g0.ORDERLINE_MIGRATION_CANCEL_SCHEDULE_MODAL;
                                    case 15244:
                                        return g0.ORDERLINE_MIGRATION_INFO_BANNER;
                                    case 15245:
                                        return g0.BUSINESS_HUB_UNMANAGED_SMB_CREDIT_BANNER;
                                    case 15246:
                                        return g0.ANALYTICS_UNMANAGED_SMB_CREDIT_MODAL;
                                    case 15248:
                                        return g0.AMAZON_SHOPPING_RECOMMENDATION_MODULE;
                                    case 15249:
                                        return g0.PIN_AD_WL_CONTROL_MODAL;
                                    case 15252:
                                        return g0.CATALOGS_OVERVIEW_PAGE_GENERIC_ADS_UPSELL;
                                    case 15253:
                                        return g0.CATALOGS_OVERVIEW_ADS_RECOMMENDATION_BANNER;
                                    case 15254:
                                        return g0.IMAGE_GENERATION_STYLE_PICKER;
                                    case 15255:
                                        return g0.CATALOGS_OVERVIEW_HERO_CAROUSEL;
                                    case 15256:
                                        return g0.CATALOGS_OVERVIEW_HERO_CAROUSEL_VIDEO_SHOPPING_ADS;
                                    case 15257:
                                        return g0.CATALOGS_OVERVIEW_HERO_CAROUSEL_JOIN_VMP;
                                    case 15258:
                                        return g0.AUTOMAGICAL_BOARDS_MODULE;
                                    case 15259:
                                        return g0.PRODUCT_FILTERED_HOMEFEED_MODULE;
                                    case 15272:
                                        return g0.PIN_CLOSEUP_LOADING_GRID;
                                    case 15273:
                                        return g0.BOARD_AUTO_COLLAGES_MODULE;
                                    case 15274:
                                        return g0.PEAR_INSIGHT_HERO_SECTION;
                                    case 15275:
                                        return g0.ACCOUNT_AMAZON_LINKING_VIEW;
                                    case 15276:
                                        return g0.ACCOUNT_AMAZON_UNLINKING_VIEW;
                                    case 15277:
                                        return g0.ACCOUNT_LINKING_BUTTON;
                                    case 15278:
                                        return g0.ACCOUNT_UNLINKING_BUTTON;
                                    case 15279:
                                        return g0.BOARD_ALL_SAVES_MODULE;
                                    case 15280:
                                        return g0.CONTEXTUAL_MENU_FLASHLIGHT;
                                    case 15281:
                                        return g0.CONTEXTUAL_MENU_DESCRIPTOR;
                                    case 15282:
                                        return g0.VOICE_PERMISSIONS_PROMPT;
                                    case 15283:
                                        return g0.BUSINESS_ACCESS_SYSTEM_USERS_PAGE;
                                    case 15284:
                                        return g0.STRUCTURED_FEED_INCLUSIVE_FALLBACK_RELATED_SEARCHES;
                                    case 15285:
                                        return g0.COMMAND_CENTER_PAGE;
                                    case 15286:
                                        return g0.COMMAND_CENTER_TABLE;
                                    case 15287:
                                        return g0.COMMAND_CENTER_INPUT_TEXT;
                                    case 15288:
                                        return g0.COMMAND_CENTER_BUTTON;
                                    case 15289:
                                        return g0.COMMAND_CENTER_SWITCH;
                                    case 15290:
                                        return g0.COMMAND_CENTER_DATE_PICKER;
                                    case 15291:
                                        return g0.COMMAND_CENTER_MODAL;
                                    case 15292:
                                        return g0.COMMAND_CENTER_SHEET;
                                    case 15293:
                                        return g0.CONTEXTUAL_VISUAL_SEARCH;
                                    case 15294:
                                        return g0.HANDSHAKE_ACCT_LINKING_VIEW;
                                    case 15295:
                                        return g0.HANDSHAKE_ACCT_UNLINKING_VIEW;
                                    case 15296:
                                        return g0.HANDSHAKE_ACCT_LINKING_BUTTON;
                                    case 15297:
                                        return g0.HANDSHAKE_ACCT_UNLINKING_BUTTON;
                                    case 15298:
                                        return g0.PIN_REP_CREATOR_ATTRIBUTION;
                                    case 15303:
                                        return g0.BUSINESS_ACCESS_APPS_PAGE;
                                    case 15304:
                                        return g0.PINNACLE_PAGE;
                                    case 15305:
                                        return g0.PINNACLE_TABLE;
                                    case 15306:
                                        return g0.PINNACLE_INPUT_TEXT;
                                    case 15307:
                                        return g0.PINNACLE_BUTTON;
                                    case 15308:
                                        return g0.PINNACLE_SWITCH;
                                    case 15309:
                                        return g0.PINNACLE_DATE_PICKER;
                                    case 15310:
                                        return g0.PINNACLE_MODAL;
                                    case 15311:
                                        return g0.PINNACLE_SHEET;
                                    case 15316:
                                        return g0.BUSINESS_ACCESS_SELECT_PEOPLE_FOR_SYSTEM_USERS_SHEET;
                                    case 15318:
                                        return g0.PINNACLE_LINK;
                                    case 15319:
                                        return g0.PINNACLE_TAG;
                                    case 15320:
                                        return g0.PINNACLE_TAB;
                                    case 15321:
                                        return g0.PINNACLE_CHECKBOX;
                                    case 15322:
                                        return g0.PINNACLE_DROPDOWN;
                                    case 15326:
                                        return g0.PIN_CLOSEUP_ADS_QCM_MODULE;
                                    case 15327:
                                        return g0.ADS_QCM_DRAWER;
                                    case 15328:
                                        return g0.QR_CODE_CONFIRMATION_MODAL;
                                    case 15329:
                                        return g0.QR_CODE_VERIFICATION_ERROR_MODAL;
                                    case 15333:
                                        return g0.PIN_BUILDER_LAYOUT_PICKER;
                                    case 15338:
                                        return g0.PEAR_INSIGHT_STORY_ENTRY_POINT_CONTAINER;
                                    case 15340:
                                        return g0.REPORT_HEADER;
                                    case 15341:
                                        return g0.REPORT_TEST_DETAILS;
                                    case 15342:
                                        return g0.REPORT_RESULTS;
                                    case 15343:
                                        return g0.REPORT_LIVE_METRICS;
                                    case 15345:
                                        return g0.AI_COMPANION_BUTTON;
                                    case 15346:
                                        return g0.AI_COMPANION_TAB;
                                    case 15347:
                                        return g0.AI_COMPANION_RICH_EDITOR;
                                    case 15348:
                                        return g0.AI_COMPANION_VARIABLE_SUGGESTION_POPOVER;
                                    case 15349:
                                        return g0.AI_COMPANION_VARIABLE_SUGGESTION_POPOVER_ITEM;
                                    case 15350:
                                        return g0.AI_COMPANION_RICH_EDITOR_DATA_PICKUP_POPOVER;
                                    case 15351:
                                        return g0.AI_COMPANION_LINK;
                                    case 15352:
                                        return g0.AI_COMPANION_CHCKBOX;
                                    case 15353:
                                        return g0.AI_COMPANION_DROPDOWN;
                                    case 15354:
                                        return g0.AI_COMPANION_SWITCH;
                                    case 15355:
                                        return g0.AI_COMPANION_EXPAND_DATA_TABLE;
                                    case 15356:
                                        return g0.AI_COMPANION_FEEDBACK_MODAL;
                                    case 15357:
                                        return g0.AI_COMPANION_SURVEY;
                                    case 15360:
                                        return g0.BASECAMP_POPOVER_SURVEY;
                                    case 15364:
                                        return g0.BUSINESS_ACCESS_EDIT_SYSTEM_USER_SHEET;
                                    case 15366:
                                        return g0.SHOP_YOUR_SAVES_MODULE;
                                    case 15367:
                                        return g0.SHOP_YOUR_SAVES_STL;
                                    case 15368:
                                        return g0.COLLAGE_DRAFTS_AND_TEMPLATES;
                                    case 15369:
                                        return g0.BUSINESS_ACCESS_CONVERSIONS_PAGE;
                                    case 15370:
                                        return g0.TRENDS_EDITORIAL_MODULE;
                                    case 15371:
                                        return g0.TRENDS_EDITORIAL_DETAILS;
                                    case 15372:
                                        return g0.TRENDS_EDITORIAL_CARD;
                                    case 15373:
                                        return g0.TRENDS_EDITORIAL_SPONSORSHIP_MODAL;
                                    case 15374:
                                        return g0.TRENDS_EDITORIAL_CAROUSEL;
                                    case 15539:
                                        return g0.PIN_CLOSEUP_COMMENTS_POST;
                                    default:
                                        switch (i13) {
                                            case RecyclerViewTypes.VIEW_TYPE_TODAY_TAB_ARTICLE_SECTION /* 208 */:
                                                return g0.PIN_EDIT_MODAL;
                                            case RecyclerViewTypes.VIEW_TYPE_TODAY_ARTICLE_BOARD_SECTION_HEADER /* 209 */:
                                                return g0.USER_BOARDS;
                                            case RecyclerViewTypes.VIEW_TYPE_TODAY_TAB_RELATED_ARTICLES_HEADER /* 210 */:
                                                return g0.USER_PINS;
                                            case RecyclerViewTypes.VIEW_TYPE_GO_TO_HOME_FEED_FOOTER /* 211 */:
                                                return g0.USER_LIKES;
                                            default:
                                                switch (i13) {
                                                    case RecyclerViewTypes.VIEW_TYPE_VTO_BUBBLE_CONTAINER /* 227 */:
                                                        return g0.PIN_STORY_PIN_COVER;
                                                    case RecyclerViewTypes.VIEW_TYPE_PROFILE_BOARDLESS_PINS_HEADER /* 228 */:
                                                        return g0.PIN_STORY_PIN_PAGE;
                                                    case RecyclerViewTypes.VIEW_TYPE_IN_LINE_VTO /* 229 */:
                                                        return g0.PIN_STORY_PIN_CHROME;
                                                    case RecyclerViewTypes.VIEW_TYPE_AFFILIATE_LINK_IMAGE /* 230 */:
                                                        return g0.PIN_STORY_PIN_ATTRIBUTION;
                                                    default:
                                                        switch (i13) {
                                                            case RecyclerViewTypes.VIEW_TYPE_SHOPPING_COLOR_LIST_FILTER_ITEM /* 232 */:
                                                                return g0.PIN_CLOSEUP_RELATED_CREATOR_PINS;
                                                            case RecyclerViewTypes.VIEW_TYPE_SEARCH_BOARD_CELL /* 233 */:
                                                                return g0.RELATED_CREATOR_PINS_FEED;
                                                            case RecyclerViewTypes.VIEW_TYPE_SHARESHEET_APP /* 234 */:
                                                                return g0.FULL_SCREEN_VIDEO;
                                                            default:
                                                                switch (i13) {
                                                                    case 13264:
                                                                        return g0.ANALYTICS_FEEDBACK_MODAL;
                                                                    case 13265:
                                                                        return g0.ANALYTICS_AUDIENCE_MOBILE_SECTION;
                                                                    case 13266:
                                                                        return g0.ANALYTICS_AUDIENCE_LOCATION_TABS;
                                                                    default:
                                                                        switch (i13) {
                                                                            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_GRID_CELL /* 126 */:
                                                                                return g0.PIN_CLOSEUP_FOLLOW;
                                                                            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK /* 127 */:
                                                                                return g0.PIN_CLOSEUP_GALLERY;
                                                                            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK_FULL_SPAN /* 128 */:
                                                                                return g0.PIN_CLOSEUP_IMAGE;
                                                                            case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK_SHOW_GRID_ACTIONS /* 129 */:
                                                                                return g0.PIN_CLOSEUP_LINK;
                                                                            default:
                                                                                return null;
                                                                        }
                                                                }
                                                        }
                                                }
                                        }
                                }
                        }
                }
        }
    }
}
