package h32;

import ads_mobile_sdk.wb;
import com.pinterest.feature.core.view.RecyclerViewTypes;

/* loaded from: classes2.dex */
public final class s0 {
    public static u0 a(int i13) {
        if (i13 == 0) {
            return u0.PIN_REPIN_BUTTON;
        }
        if (i13 != 5) {
            if (i13 == 2) {
                return u0.PIN_COMMENT_BUTTON;
            }
            if (i13 == 3) {
                return u0.PIN_EDIT_BUTTON;
            }
            if (i13 == 26) {
                return u0.PIN_USER;
            }
            if (i13 == 27) {
                return u0.PIN_ATTRIBUTION;
            }
            if (i13 == 39) {
                return u0.NEWS_FEED_BOARD;
            }
            if (i13 == 40) {
                return u0.PROFILE_BUTTON;
            }
            if (i13 == 56) {
                return u0.FIND_IMAGES_BUTTON;
            }
            if (i13 == 57) {
                return u0.SETTINGS_BUTTON;
            }
            if (i13 == 67) {
                return u0.BOARD_PICKER;
            }
            if (i13 == 68) {
                return u0.FACEBOOK_CONNECT;
            }
            switch (i13) {
                case 5:
                    break;
                case 19:
                    return u0.LOGOUT_BUTTON;
                case 30:
                    return u0.LOGIN_BUTTON;
                case 33:
                    return u0.RESET_BUTTON;
                case 34:
                    return u0.BACK_BUTTON;
                case 35:
                    return u0.PIN_SOURCE_IMAGE;
                case 36:
                    return u0.BOARD_COVER;
                case 37:
                    return u0.BOARD_FOLLOW;
                case 52:
                    return u0.BOARD_NAME;
                case 54:
                    return u0.CAMERA_BUTTON;
                case 72:
                    return u0.PIN_SHARE_BUTTON;
                case 73:
                    return u0.CANCEL_BUTTON;
                case 75:
                    return u0.CLOSE_BUTTON;
                case 76:
                    return u0.DONE_BUTTON;
                case 81:
                    return u0.BOARD_EDIT_BUTTON;
                case 86:
                    return u0.DECLINE_BUTTON;
                case 87:
                    return u0.USER_BLOCK_BUTTON;
                case 88:
                    return u0.USER_UNBLOCK_BUTTON;
                case 94:
                    return u0.USER_EDIT_BUTTON;
                case 96:
                    return u0.NEXT_BUTTON;
                case 97:
                    return u0.BOARD_LEAVE_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_VIDEO_CREATOR_ANALYTICS_MODULE /* 98 */:
                    return u0.PIN_SEND_BUTTON;
                case 100:
                    return u0.COPY_LINK_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_HAIR_PATTERN_QUERIES_MODULE /* 101 */:
                    return u0.CLIPBOARD_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_TEMPLATE_DETAILS_MODULE /* 103 */:
                    return u0.SEND_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_PEAR_STYLES_MODULE /* 104 */:
                    return u0.AUTOCOMPLETE_SUGGESTION;
                case RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_PLACEHOLDER_LOADING_GRID /* 106 */:
                    return u0.GET_STARTED_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_PIN_PDP_MONOLITH_HEADER /* 107 */:
                    return u0.REMOVE_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_TV_CATEGORY_PAGE_HEADER /* 112 */:
                    return u0.USER_LIST_USER;
                case RecyclerViewTypes.VIEW_TYPE_SCHEDULED_PIN_CELL /* 113 */:
                    return u0.UNDO_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_PROFILE_CREATED_TAB_SCHEDULED_PINS_PREVIEW /* 116 */:
                    return u0.PIN_DESCRIPTION;
                case RecyclerViewTypes.VIEW_TYPE_SIMPLE_IMAGE_CELL /* 118 */:
                    return u0.FOLLOW_BOARDS_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_VIDEO_GRID_CELL /* 121 */:
                    return u0.SUGGESTED_EMAIL;
                case RecyclerViewTypes.VIEW_TYPE_STORY_BOARD_IDEAS_PREVIEW_FOOTER /* 124 */:
                    return u0.COUNTRY_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_GRID_CELL /* 126 */:
                    return u0.UPDATE_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK_SHOW_GRID_ACTIONS_FULL_SPAN /* 130 */:
                    return u0.SAVE_USER_SETTINGS_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL_ITEM /* 139 */:
                    return u0.NOTIFICATIONS_ICON;
                case RecyclerViewTypes.VIEW_TYPE_VTO_CAROUSEL_ITEM /* 144 */:
                    return u0.LINK_OUT_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_ARTICLE_CAROUSEL_ITEM_VIDEO /* 146 */:
                    return u0.NAVIGATION_HOME_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_FULL_SPAN_PLACEHOLDER /* 162 */:
                    return u0.WEBSITE_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_VIDEO /* 171 */:
                    return u0.COLLABORATOR_TEXT;
                case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_APP_INSTALL_IMAGE /* 172 */:
                    return u0.SEND_INVITE_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_GMA_NATIVE_AD_APP_INSTALL_IMAGE_FULL_SPAN /* 176 */:
                    return u0.PIN_FLAG_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_GMA_INLINE_AD_FULL_SPAN /* 179 */:
                    return u0.SEE_MORE_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_BUBBLE_NAVIGATION_REP /* 181 */:
                    return u0.COMMENTS_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_TODAY_TAB_ARTICLE_SECTION /* 208 */:
                    return u0.GPLUS_CONNECT;
                case RecyclerViewTypes.VIEW_TYPE_VTO_BUBBLE_CONTAINER /* 227 */:
                    return u0.SEARCH_BOX_TEXT_INPUT;
                case RecyclerViewTypes.VIEW_TYPE_SHARESHEET_APP /* 234 */:
                    return u0.VISUAL_SEARCH_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_ADS_CAROUSEL_PIN_ITEM /* 240 */:
                    return u0.LANGUAGE_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_SHOWCASE_SUBPAGE_ITEM /* 241 */:
                    return u0.GENDER_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_BUBBLE_TRIPLE_PREVIEW_DISPLAY_CARD_REP /* 245 */:
                    return u0.MORE_INFO_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_BUBBLE_STACKED_COLLAGE_DISPLAY_CARD_REP /* 246 */:
                    return u0.YOUR_PROFILE_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_CUTOUT_COLLAGE_PILL_REP /* 249 */:
                    return u0.CREATE_BOARD_BUTTON;
                case 255:
                    return u0.PIN_INTEREST;
                case RecyclerViewTypes.VIEW_TYPE_OTHER_BOARD_MORE_IDEAS_FEED_PAGES_HEADER /* 256 */:
                    return u0.PIN_SHARE_TWITTER_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_COMMENT_STICKER /* 257 */:
                    return u0.PIN_SHARE_FACEBOOK_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_ANKET_INLINE_SURVEY_VIEW /* 258 */:
                    return u0.PIN_SHARE_EMAIL_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_SHOPPING_UNIT_CARD /* 267 */:
                    return u0.FOLLOWING_PINNERS_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_SHOPPING_UNIT_THUMBNAIL /* 268 */:
                    return u0.FOLLOWING_BOARDS_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_PIN_VIDEO_AD_EXCLUDE /* 276 */:
                    return u0.CONVERSATION_CREATE_BUTTON;
                case RecyclerViewTypes.VIEW_TYPE_CAROUSEL_SINGLE_COLUMN_AD_EXCLUDE /* 278 */:
                    return u0.CONVERSATION_INBOX_BUTTON;
                case 283:
                    return u0.PIN_CELL_BUTTON_PROMOTED_PIN_SOURCE;
                case 284:
                    return u0.PIN_FEEDBACK_BUTTON_PFY;
                case 289:
                    return u0.PIN_FEEDBACK_DIALOG_BUTTON_PFY_STOP_RECS_FROM_THROUGH_BOARD;
                case 290:
                    return u0.PIN_FEEDBACK_DIALOG_BUTTON_LEARN_MORE_PROMOTED;
                case 294:
                    return u0.PIN_FEEDBACK_REASON_BUTTON_OFFENSIVE;
                case 295:
                    return u0.PIN_FEEDBACK_REASON_BUTTON_SEEN_BEFORE;
                case 296:
                    return u0.DIGEST_PIN;
                case wb.W0 /* 301 */:
                    return u0.SHARE_SOCIAL_BUTTON;
                case 317:
                    return u0.PIN_SHARE_WHATSAPP;
                case 318:
                    return u0.PIN_SHARE_FB_MESSENGER;
                case 332:
                    return u0.BOARD_SHARE_FACEBOOK_BUTTON;
                case 333:
                    return u0.BOARD_SHARE_EMAIL_BUTTON;
                case 362:
                    return u0.PIN_LINK_MODULE_DOMAIN_OWNER_PROFILE;
                case 372:
                    return u0.STORY_END_CELL;
                case 400:
                    return u0.MOVE_PINS_BUTTON;
                case 403:
                    return u0.BULK_DELETE_PINS_BUTTON;
                case 709:
                    return u0.SEARCH_QUERY_TYPO_CORRECTION;
                case 710:
                    return u0.TRENDING_QUERY;
                case 713:
                    return u0.RECOMMENDED_QUERY;
                case 952:
                    return u0.PIN_SHARE_LINE_BUTTON;
                case 953:
                    return u0.PIN_SHARE_SMS_BUTTON;
                case 954:
                    return u0.PIN_SHARE_OTHER_APP_BUTTON;
                case 955:
                    return u0.BOARD_SHARE_TWITTER_BUTTON;
                case 956:
                    return u0.BOARD_SHARE_WHATSAPP_BUTTON;
                case 957:
                    return u0.BOARD_SHARE_FBMESSENGER_BUTTON;
                case 958:
                    return u0.BOARD_SHARE_LINE_BUTTON;
                case 959:
                    return u0.BOARD_SHARE_SMS_BUTTON;
                case 960:
                    return u0.BOARD_SHARE_OTHER_APP_BUTTON;
                case 982:
                    return u0.PIN_HIDE_BUTTON;
                case 983:
                    return u0.REPIN_DIALOG_SUGGESTED_BOARD;
                case 997:
                    return u0.INVITE_CONTACT;
                case 1001:
                    return u0.RECOMMENDATION_SECTION;
                case 1009:
                    return u0.PIN_FEEDBACK_DIALOG_BUTTON_UNFOLLOW_BOARD;
                case 1010:
                    return u0.PIN_FEEDBACK_DIALOG_BUTTON_UNFOLLOW_USER;
                case 1011:
                    return u0.PIN_FEEDBACK_DIALOG_BUTTON_UNFOLLOW_INTEREST;
                case 1016:
                    return u0.EDUCATION_TOOLTIP_CONFIRM_BUTTON;
                case 1017:
                    return u0.EDUCATION_TOOLTIP_DISMISS_BUTTON;
                case 1022:
                    return u0.HOMEFEED_BUILDER_FOLLOW_TOAST;
                case 1030:
                    return u0.INTEREST_FOLLOW;
                case 1031:
                    return u0.FLASHLIGHT_SEARCH_ICON;
                case 1033:
                    return u0.LIBRARY_SORT_BOARDS;
                case 1034:
                    return u0.LIBRARY_SORT_BOARDS_OPTION_CHANGED;
                case 1040:
                    return u0.SUGGESTED_CONTACT_LIST_SEARCH_ITEM;
                case 1043:
                    return u0.SEARCH_CONTACT_INPUT;
                case 1044:
                    return u0.SEARCH_CONTACT_LIST_ITEM;
                case 1079:
                    return u0.USER_SEND_BUTTON;
                case 1080:
                    return u0.CONTACT_UPLOAD_BUTTON;
                case 1114:
                    return u0.HOMEFEED_TUNER_BUTTON;
                case 1115:
                    return u0.ARTICLE_CURATOR;
                case 1140:
                    return u0.USER_DID_IT_BUTTON;
                case 1147:
                    return u0.PIN_GRID_CLICKTHROUGH_BUTTON;
                case 1150:
                    return u0.SKIP_BUTTON;
                case 1151:
                    return u0.INTEREST_UNFOLLOW;
                case 1154:
                    return u0.BOARD_UNFOLLOW;
                case 1157:
                    return u0.SELECT_PHOTO_CELL;
                case 1187:
                    return u0.NEWS_HUB_HEADER_ICON;
                case 1188:
                    return u0.NEWS_HUB_HEADER_TEXT;
                case 1194:
                    return u0.NEWS_HUB_CELL;
                case 1197:
                    return u0.NEWS_HUB_PINS_REC_HF_UPSELL_BUTTON;
                case 1208:
                    return u0.ADD_BUTTON;
                case 1209:
                    return u0.ADD_FAB;
                case 1221:
                    return u0.PIN_IMAGE_TAG;
                case 1222:
                    return u0.DID_IT_SEND_BUTTON;
                case 1223:
                    return u0.PROMOTE_BUTTON;
                case 1237:
                    return u0.COLLABORATOR_APPROVE_BUTTON;
                case 1242:
                    return u0.PROFILE_AVATAR;
                case 1260:
                    return u0.SPOTLIGHT_DOT;
                case 1264:
                    return u0.DID_IT_CONFIRM_DELETE;
                case 1266:
                    return u0.USER_PROFILE;
                case 1281:
                    return u0.MORE_BUTTON;
                case 1296:
                    return u0.PIN_FEEDBACK_REASON_NOT_MY_TASTE;
                case 1301:
                    return u0.FLASHLIGHT_CAMERA_TORCH_BUTTON;
                case 1302:
                    return u0.FLASHLIGHT_CAMERA_ROTATE_CAMERA_BUTTON;
                case 1304:
                    return u0.FLASHLIGHT_CAMERA_BUTTON;
                case 1321:
                    return u0.FLASHLIGHT_CAMERA_SCOPE;
                case 1328:
                    return u0.EXPAND_PIN_DESCRIPTION_BUTTON;
                case 1332:
                    return u0.EDUCATION_TOOLTIP_PULSER;
                case 1335:
                    return u0.PIN_SAVED_BUTTON;
                case 1337:
                    return u0.RATING_REVIEW_CELL;
                case 1338:
                    return u0.EDIT_PIN_DESCRIPTION;
                case 1341:
                    return u0.SEARCH_FILTER_APPLY;
                case 8002:
                    return u0.HELP_CENTER_LINK;
                case 8004:
                    return u0.PRIVACY_LINK;
                case 10219:
                    return u0.DID_IT_SHARE_WHATSAPP;
                case 10220:
                    return u0.DID_IT_SHARE_FB_MESSENGER;
                case 10221:
                    return u0.DID_IT_SHARE_FB_TIMELINE;
                case 10222:
                    return u0.DID_IT_SHARE_THIRD_PARTY_EXTENSION;
                case 10223:
                    return u0.DID_IT_SHARE_LINE;
                case 10224:
                    return u0.DID_IT_SHARE_KAKAO;
                case 10225:
                    return u0.DID_IT_SHARE_WECHAT;
                case 10226:
                    return u0.DID_IT_SHARE_TWITTER;
                case 10227:
                    return u0.DID_IT_SHARE_SMS;
                case 10228:
                    return u0.DID_IT_SHARE_EMAIL;
                case 10236:
                    return u0.VISUAL_LINK_CHIP;
                case 10273:
                    return u0.PIN_CLOSEUP_DESCRIPTION_HASHTAG_TEXT;
                case 10306:
                    return u0.CREATE_SECTION_BUTTON;
                case 10312:
                    return u0.BOARD_SECTION;
                case 10313:
                    return u0.BOARD_SECTION_EDIT_BUTTON;
                case 10314:
                    return u0.BOARD_SECTION_DELETE_BUTTON;
                case 10315:
                    return u0.BOARD_SECTION_ADD_BUTTON;
                case 10334:
                    return u0.AGGREGATED_COMMENT_REPORT;
                case 10372:
                    return u0.UPSELL_HOMEFEED_REFRESH_BUTTON;
                case 10376:
                    return u0.COUNTRY_PICKER_ENTRY_SELECT;
                case 10381:
                    return u0.BOARD_SECTION_NEXT_BUTTON;
                case 10382:
                    return u0.BOARD_SECTION_DONE_BUTTON;
                case 10384:
                    return u0.BOARD_ORGANIZE_BUTTON;
                case 10390:
                    return u0.OVERFLOW_BUTTON;
                case 10412:
                    return u0.AD_INFO_LINK;
                case 10413:
                    return u0.ARCHIVE_BOARD_BUTTON;
                case 10414:
                    return u0.UNARCHIVE_BOARD_BUTTON;
                case 10420:
                    return u0.SKIN_TONE_FILTER_REMEMBER_YES;
                case 10421:
                    return u0.SKIN_TONE_FILTER_REMEMBER_NO;
                case 10429:
                    return u0.INSTAGRAM_CONNECT;
                case 10463:
                    return u0.BOARD_SECTION_REORDER_ENTRY_BUTTON;
                case 10464:
                    return u0.SELECT_ALL_BUTTON;
                case 10465:
                    return u0.UNSELECT_ALL_BUTTON;
                case 10468:
                    return u0.PRODUCT_PIN_CHIP;
                case 10502:
                    return u0.FOLLOWING_FACEPILES;
                case 10537:
                    return u0.TILTED_PINS_SOURCE_EDIT_BUTTON;
                case 10538:
                    return u0.SCROLL_TO_TOP_BUTTON;
                case 10555:
                    return u0.PRODUCT_PIN_CAROUSEL;
                case 10572:
                    return u0.BOARD_SECTION_MERGE_LIST_CELL;
                case 10573:
                    return u0.SEE_PIN_STATS_BUTTON;
                case 10574:
                    return u0.PIN_ANALYTICS_SEE_ALL_SAVED_BOARDS_BUTTON;
                case 10583:
                    return u0.SPAM;
                case 10584:
                    return u0.NUDITY;
                case 10592:
                    return u0.BOARD_ADD_COLLABORATOR_BUTTON;
                case 10597:
                    return u0.CONVERSATION_QUICK_REPLY_EMOJI_BUTTON;
                case 10598:
                    return u0.CONVERSATION_SEND_A_PIN_BACK_BUTTON;
                case 10599:
                    return u0.MORE_IDEAS_ONE_TAP_SAVE_BUTTON;
                case 10600:
                    return u0.MORE_IDEAS_DETAIL_BUTTON;
                case 10601:
                    return u0.MORE_IDEAS_FOOTER_BUTTON;
                case 10605:
                    return u0.PROFILE_PIN_REP_VIEW_DEFAULT_OPTION;
                case 10606:
                    return u0.PROFILE_PIN_REP_VIEW_DENSE_OPTION;
                case 10610:
                    return u0.MORE_IDEAS_TAB;
                case 10612:
                    return u0.TAB_CAROUSEL_TAB;
                case 10626:
                    return u0.PROFILE_PIN_REP_VIEW_SINGLE_COLUMN_OPTION;
                case 10643:
                    return u0.CREATE_PIN_BUTTON;
                case 10717:
                    return u0.VIDEO_MUTE_BUTTON;
                case 10718:
                    return u0.VIDEO_UNMUTE_BUTTON;
                case 10724:
                    return u0.ANALYTICS_HELP_CENTER_LINK;
                case 10774:
                    return u0.PIN_SHARE_FACEBOOK_STORY_BUTTON;
                case 10776:
                    return u0.BOARD_ACTION_CREATE_BUTTON;
                case 10799:
                    return u0.MERGE_CONFIRMATION_TOAST;
                case 10803:
                    return u0.PIN_REORDER_ENTRY_BUTTON;
                case 10805:
                    return u0.BOARD_MORE_IDEAS_UPSELL_TOAST;
                case 10809:
                    return u0.PIN_SHARE_FACEBOOK_LITE_BUTTON;
                case 10810:
                    return u0.PIN_SHARE_FACEBOOK_MESSENGER_LITE_BUTTON;
                case 10811:
                    return u0.BOARD_SHARE_FACEBOOK_LITE_BUTTON;
                case 10812:
                    return u0.BOARD_SHARE_FACEBOOK_MESSENGER_LITE_BUTTON;
                case 10813:
                    return u0.DID_IT_SHARE_FB_LITE;
                case 10814:
                    return u0.DID_IT_SHARE_FB_MESSENGER_LITE;
                case 10836:
                    return u0.PIN_DOWNLOAD_BUTTON;
                case 10847:
                    return u0.INSIGHTS_AUDIENCE_SELECT_LIST;
                case 10881:
                    return u0.FORGET_PW_LINK;
                case 10882:
                    return u0.PROFILE_MESSAGE_BUTTON;
                case 10898:
                    return u0.PIN_FEEDBACK_REASON_LOW_QUALITY;
                case 10900:
                    return u0.PIN_FEEDBACK_HIDE_PROMPT;
                case 10912:
                    return u0.ANALYTICS_CLAIMED_ACCOUNT_FILTER;
                case 10913:
                    return u0.ANALYTICS_CONTENT_FILTER;
                case 10914:
                    return u0.ANALYTICS_DEVICE_FILTER;
                case 10915:
                    return u0.ANALYTICS_SOURCE_FILTER;
                case 10919:
                    return u0.BOARD_COLLAB_REQUESTS_ENABLED_SWITCH;
                case 10920:
                    return u0.PIN_REP_BOARD_PAGE_LINK;
                case 10942:
                    return u0.PIN_STORY_PIN_SHARE_BUTTON;
                case 10943:
                    return u0.PIN_STORY_PIN_SAVE_BUTTON;
                case 10946:
                    return u0.PIN_STORY_PIN_MORE_ACTIONS_BUTTON;
                case 10947:
                    return u0.PIN_STORY_PIN_IMAGE;
                case 10949:
                    return u0.CREATE_STORY_PIN_BUTTON;
                case 10954:
                    return u0.PIN_STORY_PIN_HASHTAG;
                case 10957:
                    return u0.PIN_STORY_PIN_VIDEO;
                case 10991:
                    return u0.NAVIGATION_CREATE_BUTTON;
                case 10994:
                    return u0.BOARD_SECTION_MORE_IDEAS;
                case 11025:
                    return u0.CREATE_AD_BUTTON;
                case 11076:
                    return u0.ANALYTICS_VIEW_PIN_LINK;
                case 11078:
                    return u0.ANALYTICS_METRIC_SELECTLIST;
                case 11079:
                    return u0.ANALYTICS_SPLIT_SELECTLIST;
                case 11080:
                    return u0.ANALYTICS_RESET_BUTTON;
                case 11081:
                    return u0.MULTI_TAB_HOME_TAB;
                case 11082:
                    return u0.MULTI_TAB_MORE_IDEAS_TAB;
                case 11154:
                    return u0.CREATE_NEW_AD_BUTTON;
                case 11172:
                    return u0.PIN_FEEDBACK_REASON_REPETITIVE_AD;
                case 11178:
                    return u0.PIN_FEEDBACK_REASON_NOT_MY_LANGUAGE;
                case 11179:
                    return u0.PIN_FEEDBACK_REASON_OTHER;
                case 11180:
                    return u0.NOTICE_ACTION_BUTTON;
                case 11181:
                    return u0.PIN_FEEDBACK_UNDO_HIDE;
                case 11212:
                    return u0.CONVERT_TO_BUSINESS_BUTTON;
                case 11216:
                    return u0.ANALYTICS_PIN_FORMAT_FILTER;
                case 11290:
                    return u0.ACCEPT_BUTTON;
                case 11301:
                    return u0.BOARD_ALLOW_HOMEFEED_RECS;
                case 11347:
                    return u0.HOME_FEED_CONTROL_PANEL_PIN_FEEDBACK_BUTTON;
                case 11348:
                    return u0.HOME_FEED_CONTROL_PANEL_BOARDS_TAB;
                case 11349:
                    return u0.HOME_FEED_CONTROL_PANEL_ACTIVITY_TAB;
                case 11350:
                    return u0.HOME_FEED_CONTROL_PANEL_TOPICS_TAB;
                case 11351:
                    return u0.HOME_FEED_CONTROL_PANEL_BOARD_ITEM;
                case 11352:
                    return u0.HOME_FEED_CONTROL_PANEL_ACTIVITY_ITEM;
                case 11354:
                    return u0.PIN_REACTION_BUTTON;
                case 11376:
                    return u0.SHOPPING_BRAND_FILTER_TABLE_CELL;
                case 11411:
                    return u0.NEG_LINK_FEEDBACK_REASON_NOT_MY_LANGUAGE;
                case 11412:
                    return u0.NEG_LINK_FEEDBACK_SPAM;
                case 11414:
                    return u0.NEG_LINK_FEEDBACK_LOW_QUALITY;
                case 11415:
                    return u0.OTHER;
                case 11416:
                    return u0.BROKEN;
                case 11417:
                    return u0.CONVERSATION_GROUP_BOARD_UPSELL_NO_THANKS_BUTTON;
                case 11418:
                    return u0.CONVERSATION_GROUP_BOARD_UPSELL_ACCEPT_BUTTON;
                case 11420:
                    return u0.CONVERSATION_GROUP_BOARD_UPSELL_CREATE_GROUP_BOARD_BUTTON;
                case 11421:
                    return u0.CONVERSATION_GROUP_BOARD_UPSELL_GROUP_BOARD_CREATE_TOAST_BUTTON;
                case 11431:
                    return u0.GROUP_BOARDS_REACTION_BAR;
                case 11435:
                    return u0.PIN_REACTION_COUNT;
                case 11447:
                    return u0.PROFILE_HEADER_EXPAND_BUTTON;
                case 11460:
                    return u0.ANALYTICS_RECENT_PINS_FILTER;
                case 11516:
                    return u0.PERSONAL_BOUTIQUE_SHOP_TAB;
                case 11524:
                    return u0.VIRTUAL_TRY_ON_ICON;
                case 11532:
                    return u0.COMMENT_COUNT;
                case 11533:
                    return u0.CLOSEUP_COMMENT;
                case 11540:
                    return u0.EDIT_PIN_TITLE;
                case 11545:
                    return u0.SHOPPING_FILTER_CLEAR_BUTTON;
                case 11546:
                    return u0.SHOPPING_FILTER_SUBMIT_BUTTON;
                case 11569:
                    return u0.RECIPE_TEMPLATE_BUTTON;
                case 11570:
                    return u0.HOME_DIY_TEMPLATE_BUTTON;
                case 11571:
                    return u0.ANALYTICS_VIEW_BOARD_LINK;
                case 11587:
                    return u0.PIN_STORY_PIN_COOK_TIME_PICKER;
                case 11592:
                    return u0.FREESTYLE_TEMPLATE_BUTTON;
                case 11593:
                    return u0.PIN_INTEREST_TAG;
                case 11594:
                    return u0.PIN_INTEREST_TAG_SEARCH_BOX;
                case 11619:
                    return u0.CREATOR_CARD_LINK;
                case 11674:
                    return u0.TODAY_TAB_ENTRY;
                case 11677:
                    return u0.FLASHLIGHT_IMAGE_OVERLAY;
                case 11681:
                    return u0.BOARD_SHOP_SHOW_MORE_BUTTON;
                case 11689:
                    return u0.BACK_TO_HOME_FEED_BUTTON;
                case 11690:
                    return u0.END_OF_FEED_BACK_BUTTON;
                case 11704:
                    return u0.BOARD_MERGE_BUTTON;
                case 11722:
                    return u0.ANALYTICS_VIEW_PINS;
                case 11723:
                    return u0.ANALYTICS_START_DATEPICKER;
                case 11724:
                    return u0.ANALYTICS_END_DATEPICKER;
                case 11725:
                    return u0.ANALYTICS_DATEPICKER_PRESET;
                case 11726:
                    return u0.ANALYTICS_FILTER_MENU_BUTTON;
                case 11727:
                    return u0.ANALYTICS_DATE_MENU_BUTTON;
                case 11728:
                    return u0.ANALYTICS_OVERVIEW_TAB;
                case 11730:
                    return u0.ANALYTICS_GRAPH_CLOSEUP_BUTTON;
                case 11733:
                    return u0.SEARCH_EXPLORE_TAB;
                case 11734:
                    return u0.SEARCH_SHOP_TAB;
                case 11736:
                    return u0.SHOPPING_CATEGORY_FILTER_TABLE_CELL;
                case 11743:
                    return u0.VIRTUAL_TRY_ON_DOWNLOAD_TOAST;
                case 11744:
                    return u0.VIRTUAL_TRY_ON_READY_TOAST;
                case 11746:
                    return u0.IMPORT_FROM_INSTAGRAM_CONNECT;
                case 11753:
                    return u0.CONVERSATION_INBOX_MESSAGE_CONTACT_BUTTON;
                case 11756:
                    return u0.FLASHLIGHT_CLOSE_ICON;
                case 11758:
                    return u0.BOARD_ACTION_UPSELL_BANNER;
                case 11769:
                    return u0.PIN_STORY_PIN_MATERIALS_BUTTON;
                case 11797:
                    return u0.ANALYTICS_SEND_FEEDBACK_BUTTON;
                case 11828:
                    return u0.SHOPPING_DOMAIN_MODULE_USER_AVATAR;
                case 11829:
                    return u0.SHOPPING_DOMAIN_MODULE_SHOP_BUTTON;
                case 11830:
                    return u0.SHOPPING_DOMAIN_MODULE_CAROUSEL_PIN;
                case 11838:
                    return u0.SCENE_SHOP_TAG_BUTTON;
                case 11839:
                    return u0.NOTIFICATION_FILTERS_BUTTON;
                case 11891:
                    return u0.CONVERSATION_OPEN_GIF_REACTION_TRAY_BUTTON;
                case 11892:
                    return u0.CONVERSATION_SEND_A_PIN_USER_EMPTY_STATE_BUTTON;
                case 11896:
                    return u0.BOARD_ALLOW_INVITE_OTHERS;
                case 11897:
                    return u0.STORY_PIN_PUBLISH_BUTTON;
                case 11898:
                    return u0.PIN_STORY_PIN_SERVING_SIZE_PICKER;
                case 11899:
                    return u0.PIN_STORY_PIN_DIFFICULTY_LEVEL_PICKER;
                case 11901:
                    return u0.STORY_PIN_BOARD_SECTION;
                case 11902:
                    return u0.STORY_PIN_DETAILS_SECTION;
                case 11903:
                    return u0.STORY_PIN_TAGS_SECTION;
                case 11906:
                    return u0.SUBMIT_BUTTON;
                case 11915:
                    return u0.MENTION;
                case 11922:
                    return u0.PIN_THUMBNAIL_CAROUSEL_CELL;
                case 11925:
                    return u0.DISMISS_BUTTON;
                case 11926:
                    return u0.COMPLETE_BUTTON;
                case 11950:
                    return u0.BODY;
                case 11951:
                    return u0.USER_FOLLOW_BUTTON;
                case 11952:
                    return u0.BIZHUB_BUTTON;
                case 11953:
                    return u0.USER_CONTACT_BUTTON;
                case 11954:
                    return u0.USER_EMAIL_OPTION;
                case 11955:
                    return u0.USER_PHONE_OPTION;
                case 11956:
                    return u0.USER_MESSAGE_OPTION;
                case 11960:
                    return u0.ANALYTICS_AUDIENCE_INSIGHTS_TAB;
                case 11962:
                    return u0.CLOSEUP_STL_FLYOUT;
                case 11963:
                    return u0.STL_TAG_BUTTON;
                case 11973:
                    return u0.ANALYTICS_AUDIENCE_LOCATION_METROS_TAB;
                case 11974:
                    return u0.ANALYTICS_AUDIENCE_LOCATION_COUNTRIES_TAB;
                case 11977:
                    return u0.SEARCH_CURATED_SUGGESTION;
                case 11978:
                    return u0.ENGAGEMENT_LIST_ITEM;
                case 11981:
                    return u0.SEE_MORE_COMMENTS;
                case 11987:
                    return u0.NEGATIVE_FEEDBACK;
                case 11988:
                    return u0.NEUTRAL_FEEDBACK;
                case 11989:
                    return u0.POSITIVE_FEEDBACK;
                case 11990:
                    return u0.BOARD_TOOL_SHOP;
                case 11991:
                    return u0.BOARD_TOOL_MORE_IDEAS;
                case 11992:
                    return u0.BOARD_TOOL_ORGANIZE;
                case 11994:
                    return u0.BOARD_TOOL_MESSAGE_GROUP;
                case 12001:
                    return u0.STORY_PIN_CAMERA_ENABLE_GHOST_BUTTON;
                case 12002:
                    return u0.STORY_PIN_CAMERA_DISABLE_GHOST_BUTTON;
                case 12015:
                    return u0.EDIT_BUTTON;
                case 12016:
                    return u0.SHARE_BUTTON;
                case 12018:
                    return u0.SAVE_BUTTON;
                case 12019:
                    return u0.CONTINUE_BUTTON;
                case 12020:
                    return u0.FILTER_BUTTON;
                case 12021:
                    return u0.CLEAR_BUTTON;
                case 12032:
                    return u0.VIRTUAL_TRY_ON_MAKEUP_BUTTON;
                case 12054:
                    return u0.VERIFIED_MERCHANT_BADGE;
                case 12058:
                    return u0.PIN_AD_TARGETING_REASONS_LEARN_MORE_BLOCK_ADVERTISER;
                case 12059:
                    return u0.PIN_AD_TARGETING_REASONS_GEO_REGION;
                case 12103:
                    return u0.EMPTY_PIN_NOTE_FIELD;
                case 12104:
                    return u0.PIN_NOTE_EDIT_BUTTON;
                case 12105:
                    return u0.PIN_NOTE_DELETE_BUTTON;
                case 12106:
                    return u0.PIN_NOTE_DONE_BUTTON;
                case 12107:
                    return u0.PIN_NOTE_MODAL_BACKGROUND;
                case 12108:
                    return u0.PIN_NOTE_CONFIRM_DELETE_BUTTON;
                case 12109:
                    return u0.PIN_NOTE_CONFIRM_DISCARD_BUTTON;
                case 12110:
                    return u0.PINS_WITH_NOTES_FILTER;
                case 12111:
                    return u0.ALL_PINS_FILTER;
                case 12112:
                    return u0.ANALYTICS_REALTIME_FILTER;
                case 12114:
                    return u0.SPONSORSHIP_CONFIRM_REMOVE_BUTTON;
                case 12120:
                    return u0.PIN_STORY_PIN_MENTION;
                case 12121:
                    return u0.PIN_STORY_PIN_MENTION_TOOLTIP;
                case 12129:
                    return u0.BOARD_ORGANIZE_PINS_STORY;
                case 12173:
                    return u0.STORY_PIN_MULTI_DRAFTS_DELETE_BUTTON;
                case 12175:
                    return u0.STORY_PIN_DISCARD_BUTTON;
                case 12176:
                    return u0.STORY_PIN_STORE_BUTTON;
                case 12177:
                    return u0.PIN_STORY_PIN_HIDE_BUTTON;
                case 12208:
                    return u0.NEWS_HUB_FEED_ITEM_ELLIPSIS_ICON;
                case 12209:
                    return u0.NEWS_HUB_UNSUB_OR_RESUB_FROM_OBJECT_BUTTON;
                case 12210:
                    return u0.NEWS_HUB_VIEW_SETTINGS_BUTTON;
                case 12212:
                    return u0.LENS_PERMISSION_RESULT_DENIED;
                case 12216:
                    return u0.LENS_PERMISSION_RESULT_AUTHORIZED;
                case 12217:
                    return u0.LENS_PERMISSION_SETTINGS_BUTTON;
                case 12218:
                    return u0.LENS_PERMISSION_RESULT_EXITED;
                case 12220:
                    return u0.SHOPPING_BRAND_FILTER_OPTION;
                case 12221:
                    return u0.STORY_PIN_CREATE_PRODUCT_THUMBNAIL;
                case 12222:
                    return u0.STORY_PIN_PRODUCT_TAGGING_BUTTON;
                case 12223:
                    return u0.PIN_STORY_PIN_PRODUCT;
                case 12224:
                    return u0.PIN_STORY_PIN_PRODUCT_TOOLTIP;
                case 12225:
                    return u0.PIN_FAVORITE_BUTTON;
                case 12226:
                    return u0.PIN_UNFAVORITE_BUTTON;
                case 12227:
                    return u0.FAVORITE_PINS_FILTER;
                case 12228:
                    return u0.LENS_PERMISSION_OVERLAY;
                case 12230:
                    return u0.ANALYTICS_CURATED_CONTENT_FILTER;
                case 12241:
                    return u0.WHATS_NEW_ACTION_BUTTON;
                case 12248:
                    return u0.STORY_PIN_CAMERA_RECORD_BUTTON;
                case 12249:
                    return u0.STORY_PIN_CAMERA_RECORD_STOP_BUTTON;
                case 12250:
                    return u0.STORY_PIN_CAMERA_LENS_BUTTON;
                case 12252:
                    return u0.STORY_PIN_CAMERA_DELETE_CLIP_BUTTON;
                case 12254:
                    return u0.STORY_PIN_CAMERA_SPEED_BUTTON;
                case 12255:
                    return u0.STORY_PIN_CAMERA_SPEED_0_3X_BUTTON;
                case 12256:
                    return u0.STORY_PIN_CAMERA_SPEED_0_5X_BUTTON;
                case 12257:
                    return u0.STORY_PIN_CAMERA_SPEED_1X_BUTTON;
                case 12258:
                    return u0.STORY_PIN_CAMERA_SPEED_2X_BUTTON;
                case 12259:
                    return u0.STORY_PIN_CAMERA_SPEED_3X_BUTTON;
                case 12262:
                    return u0.PIN_STORY_PIN_COPY_MATERIALS_BUTTON;
                case 12271:
                    return u0.HOME_FEED_CONTROL_PANEL_PROFILES_TAB;
                case 12274:
                    return u0.SAVING_REPIN_TOAST_VIEW;
                case 12275:
                    return u0.SAVING_REPIN_TOAST_CHANGE_BUTTON;
                case 12276:
                    return u0.USER_EASY_FOLLOW_BUTTON;
                case 12277:
                    return u0.LINE_CONNECT;
                case 12278:
                    return u0.NOTIFICATION_FILTERS_OPTION_COMMENTS;
                case 12279:
                    return u0.NOTIFICATION_FILTERS_OPTION_PHOTOS;
                case 12280:
                    return u0.NOTIFICATION_FILTERS_OPTION_ALL;
                case 12281:
                    return u0.STORY_PIN_QUESTION_BUTTON;
                case 12285:
                    return u0.ADD_EXISTING_ACCOUNT_BTN;
                case 12286:
                    return u0.ADD_PERSONAL_ACCOUNT_BTN;
                case 12287:
                    return u0.ADD_BUSINESS_ACCOUNT_BTN;
                case 12292:
                    return u0.STORY_PIN_TRIMMER_DELETE_CLIP_BUTTON;
                case 12293:
                    return u0.STORY_PIN_TRIMMER_ADD_CLIP_BUTTON;
                case 12308:
                    return u0.WISHLIST_SHOW_MORE_BUTTON;
                case 12310:
                    return u0.STORY_PIN_TEXT;
                case 12311:
                    return u0.STORY_PIN_IMAGE;
                case 12312:
                    return u0.STORY_PIN_VIDEO;
                case 12313:
                    return u0.STORY_PIN_MENTION_TAG;
                case 12314:
                    return u0.STORY_PIN_PRODUCT_TAG;
                case 12315:
                    return u0.STORY_PIN_STATIC_STICKER;
                case 12316:
                    return u0.STORY_PIN_REQUEST_PERMISSIONS_BUTTON;
                case 12341:
                    return u0.STORY_PIN_EXAMPLES_OPTION;
                case 12342:
                    return u0.CREATOR_RESOURCES_OPTION;
                case 12343:
                    return u0.FEEDBACK_OPTION;
                case 12356:
                    return u0.STORY_PIN_LIST_CREATE_INGREDIENTS_BUTTON;
                case 12357:
                    return u0.STORY_PIN_LIST_CREATE_SUPPLIES_BUTTON;
                case 12358:
                    return u0.STORY_PIN_LIST_CREATE_NOTES_BUTTON;
                case 12359:
                    return u0.STORY_PIN_METADATA_SAVE_DRAFT_BUTTON;
                case 12368:
                    return u0.BEST_PRACTICES_SITE_OPTION;
                case 12369:
                    return u0.BEST_PRACTICES_IN_PRODUCT_OPTION;
                case 12372:
                    return u0.STORY_PIN_PREVIEW;
                case 12373:
                    return u0.VIEW_ALL_BUTTON;
                case 12374:
                    return u0.PIN_CELL;
                case 12378:
                    return u0.CREATOR_CODE_OPTION;
                case 12379:
                    return u0.IDEA_STREAM_NAV_BUTTON;
                case 12394:
                    return u0.TAP_TO_TRY_ON_INLINE;
                case 12395:
                    return u0.VIRTUAL_TRY_ON_INLINE_CAMERA;
                case 12396:
                    return u0.CLOSE_INLINE_VTO;
                case 12397:
                    return u0.FOLLOW_USER_OPTION;
                case 12398:
                    return u0.UNFOLLOW_USER_OPTION;
                case 12408:
                    return u0.STORY_PIN_PHOTO_PICKER_VIDEO;
                case 12409:
                    return u0.STORY_PIN_PHOTO_PICKER_PHOTO;
                case 12410:
                    return u0.STORY_PIN_PHOTO_PICKER_ALL;
                case 12412:
                    return u0.STORY_PIN_VIDEO_CLIPS_BUTTON;
                case 12413:
                    return u0.STORY_PIN_VIDEO_TEXT_BUTTON;
                case 12414:
                    return u0.STORY_PIN_VIDEO_MUSIC_BUTTON;
                case 12417:
                    return u0.STORY_PIN_VIDEO_STICKERS_BUTTON;
                case 12418:
                    return u0.STORY_PIN_VIDEO_BACKGROUND_BUTTON;
                case 12420:
                    return u0.STORY_PIN_TEXT_COLOR_BUTTON;
                case 12421:
                    return u0.STORY_PIN_TEXT_ALIGNMENT_BUTTON;
                case 12422:
                    return u0.STORY_PIN_TEXT_HIGHLIGHT_BUTTON;
                case 12423:
                    return u0.STORY_PIN_TEXT_FONT_PICKER_BUTTON;
                case 12424:
                    return u0.STORY_PIN_TEXT_ANIMATE_IN_BUTTON;
                case 12425:
                    return u0.STORY_PIN_TEXT_ANIMATE_OUT_BUTTON;
                case 12427:
                    return u0.STORY_PIN_MUSIC_GENRE_BUTTON;
                case 12428:
                    return u0.STORY_PIN_MUSIC_MOOD_BUTTON;
                case 12429:
                    return u0.STORY_PIN_MUSIC_ADD_SONG_BUTTON;
                case 12431:
                    return u0.STORY_PIN_MUSIC_REPLACE_SONG_BUTTON;
                case 12432:
                    return u0.STORY_PIN_MUSIC_VIEW_TERM_BUTTON;
                case 12433:
                    return u0.STORY_PIN_MUSIC_VOLUME_BUTTON;
                case 12434:
                    return u0.STORY_PIN_MUSIC_DURATION_BUTTON;
                case 12435:
                    return u0.STORY_PIN_MUSIC_SONG_PICKER_BUTTON;
                case 12441:
                    return u0.STORY_PIN_METADATA_EDIT_COVER_BUTTON;
                case 12442:
                    return u0.STORY_PIN_ADVANCED_SETTING_SECTION;
                case 12444:
                    return u0.STORY_PIN_MUSIC_SELECTION_BUTTON;
                case 12447:
                    return u0.SEARCH_PROFILES_TAB;
                case 12448:
                    return u0.VIEW_ANYWAY_BUTTON;
                case 12456:
                    return u0.STORY_PIN_PHOTO_PICKER_ALBUM;
                case 12461:
                    return u0.STORY_PIN_TEXT_FONT_PICKER_OPTION;
                case 12462:
                    return u0.STORY_PIN_MULTI_DRAFTS_EDIT_BUTTON;
                case 12464:
                    return u0.STORY_PIN_COLOR_SELECTION_BUTTON;
                case 12479:
                    return u0.STORY_PIN_TURN_OFF_COMMENTS_TOGGLE;
                case 12482:
                    return u0.CATEGORY_NAVIGATION_BUTTON;
                case 12483:
                    return u0.BRANDS_NAVIGATION_BUTTON;
                case 12484:
                    return u0.SHOPPING_LIST_NAVIGATION_BUTTON;
                case 12500:
                    return u0.STORY_PIN_PARTNERSHIP_TOGGLE;
                case 12501:
                    return u0.STORY_PIN_PARTNER_TAG_SECTION;
                case 12502:
                    return u0.STORY_PIN_PARTNER_TAG_SUBMIT_BUTTON;
                case 12503:
                    return u0.STORY_PIN_PARTNER_TAG_REMOVE_BUTTON;
                case 12504:
                    return u0.REMOVE_SPONSORSHIP_OPTION;
                case 12505:
                    return u0.REMOVE_SPONSORSHIP_CANCEL_BUTTON;
                case 12518:
                    return u0.STORY_PIN_MENTION_BUTTON;
                case 12519:
                    return u0.STORY_PIN_MENTION_THUMBNAIL;
                case 12541:
                    return u0.PIN_STORY_PIN_COMMENT_REPLY;
                case 12545:
                    return u0.STORY_PIN_DRAWING_UNDO_BUTTON;
                case 12546:
                    return u0.STORY_PIN_DRAWING_BRUSH_SELECTION_BUTTON;
                case 12548:
                    return u0.STORY_PIN_DRAWING_BUTTON;
                case 12551:
                    return u0.UNLINK_ACCOUNT_BUTTON;
                case 12555:
                    return u0.PIN_SHARE_INSTAGRAM_STORY_BUTTON;
                case 12559:
                    return u0.VTO_PRODUCT_PREVIEW_BUTTON;
                case 12560:
                    return u0.IDEA_PIN_VTO_ADD_STICKER_BUTTON;
                case 12561:
                    return u0.IDEA_PIN_VTO_STICKER;
                case 12562:
                    return u0.IDEA_PIN_VTO_STICKER_PREVIEW;
                case 12563:
                    return u0.IDEA_PIN_VTO_STICKER_PRODUCT_INFO;
                case 12564:
                    return u0.VTO_MINI_CAMERA_ALLOW_PERMISSIONS;
                case 12595:
                    return u0.ANALYTICS_ADS_PIN_FORMAT_FILTER;
                case 12596:
                    return u0.ANALYTICS_ORGANIC_PIN_FORMAT_FILTER;
                case 12601:
                    return u0.VIEW_PROFILE_BUTTON;
                case 12602:
                    return u0.UNFOLLOW_USER_BUTTON;
                case 12618:
                    return u0.STORY_PIN_PAUSE_BUTTON;
                case 12625:
                    return u0.SEARCH_AUTOCOMPLETE_SYOP_BUTTON;
                case 12634:
                    return u0.STORY_PIN_VTO_PRODUCT_TAG;
                case 12647:
                    return u0.PIN_FEEDBACK_HIDE_BY_CREATOR;
                case 12670:
                    return u0.CREATOR_HUB_ENTRY_POINT;
                case 12671:
                    return u0.CREATOR_HUB_TAB_DEFAULT;
                case 12674:
                    return u0.CREATOR_TOOL_ENGAGEMENT;
                case 12675:
                    return u0.CREATOR_TOOL_ANALYTICS;
                case 12676:
                    return u0.CREATOR_TOOL_DRAFTS;
                case 12719:
                    return u0.AR_SCENE_ICON;
                case 12720:
                    return u0.BROWSE_TAB;
                case 12721:
                    return u0.WATCH_TAB;
                case 12722:
                    return u0.ACCOUNT_SWITCHER_OPEN_SETTINGS_BTN;
                case 12724:
                    return u0.IDEA_PIN_STICKER_CATEGORY_BUTTON;
                case 12725:
                    return u0.IDEA_PIN_STICKER_SEATCH_BOX;
                case 12726:
                    return u0.IDEA_PIN_STICKER_SEATCH_CANCEL_BUTTON;
                case 12758:
                    return u0.CHANGE_BUTTON;
                case 12765:
                    return u0.EXTERNAL_LINK;
                case 12776:
                    return u0.AR_CALIBRATION_CTA;
                case 12786:
                    return u0.EDIT_BOARDS_VISIBILITY;
                case 12787:
                    return u0.ALL_PINS_VISIBILITY_SWITCH;
                case 12788:
                    return u0.SHOPPING_LIST_VISIBILITY_SWITCH;
                case 12796:
                    return u0.VISIT_BUTTON;
                case 12799:
                    return u0.USER_ADDRESS_OPTION;
                case 12801:
                    return u0.IDEA_PIN_BOARD_STICKER_BUTTON;
                case 12804:
                    return u0.IDEA_PIN_IMAGE_STICKER_BUTTON;
                case 12818:
                    return u0.USER_EDIT_ABOUT_TEXT_FIELD;
                case 12827:
                    return u0.IDEA_PIN_BOARD_STICKER;
                case 12828:
                    return u0.IDEA_PIN_BOARD_STICKER_TOOLTIP;
                case 12840:
                    return u0.ADD_AGE;
                case 12841:
                    return u0.ADD_GENDER;
                case 12868:
                    return u0.NAVIGATION_SEARCH_BUTTON;
                case 12873:
                    return u0.NAVIGATION_NOTIFICATIONS;
                case 12877:
                    return u0.IDEA_PIN_BOARD_STICKER_PICKER_OPTION;
                case 12879:
                    return u0.IDEA_PIN_CAMERA_FLASH_BUTTON;
                case 12880:
                    return u0.IDEA_PIN_CAMERA_TIMER_OFF_BUTTON;
                case 12881:
                    return u0.IDEA_PIN_CAMERA_TIMER_3S_BUTTON;
                case 12882:
                    return u0.IDEA_PIN_CAMERA_TIMER_10S_BUTTON;
                case 12890:
                    return u0.BUSINESS_PROFILE_WEBSITE_LINK;
                case 12893:
                    return u0.COLLAGE_BUTTON;
                case 12917:
                    return u0.MULTI_FACTOR_TOGGLE;
                case 12918:
                    return u0.CONFIRMATION_REQUIRED;
                case 12919:
                    return u0.BACKUP_CODE;
                case 12920:
                    return u0.RESEND_BUTTON;
                case 12921:
                    return u0.COUNTRY_CODE_PICKER;
                case 12933:
                    return u0.NEW_CODE_BUTTON;
                case 12934:
                    return u0.DATE_PICKER_SELECTION;
                case 12937:
                    return u0.USER_BIRTHDAY_OPTION;
                case 12970:
                    return u0.IDEA_PIN_LINK_SECTION;
                case 12971:
                    return u0.IDEA_PIN_LINK_BUTTON;
                case 12973:
                    return u0.IDEA_PIN_QUESTION_STICKER_BUTTON;
                case 12975:
                    return u0.IDEA_PIN_PHOTO_TAKING_CAMERA_PHOTO_BUTTON;
                case 12976:
                    return u0.IDEA_PIN_PHOTO_TAKING_CAMERA_VIDEO_BUTTON;
                case 13002:
                    return u0.BOARD_MORE_IDEAS_CARD;
                case 13003:
                    return u0.BOARD_MORE_IDEAS_GRID_ITEM;
                case 13037:
                    return u0.CREATOR_TOOL_BRANDED_CONTENT;
                case 13038:
                    return u0.BRANDED_CONTENT_ENROLLMENT;
                case 13039:
                    return u0.BRANDED_CONTENT_UNENROLLMENT;
                case 13077:
                    return u0.UNIFIED_CTA;
                case 13082:
                    return u0.IDEA_PIN_MUSIC_SEARCH_BOX;
                case 13083:
                    return u0.IDEA_PIN_MUSIC_SEARCH_CANCEL_BUTTON;
                case 13086:
                    return u0.IDEA_PIN_SEE_ALL_BUTTON;
                case 13097:
                    return u0.SEND_SHARE_DISMISS_BUTTON;
                case 13098:
                    return u0.SEND_SHARE_WHATSAPP_BUTTON;
                case 13100:
                    return u0.SEND_SHARE_MESSENGER_BUTTON;
                case 13101:
                    return u0.SEND_SHARE_FACEBOOK_BUTTON;
                case 13102:
                    return u0.SEND_SHARE_WECHAT_BUTTON;
                case 13103:
                    return u0.SEND_SHARE_COPYLINK_BUTTON;
                case 13104:
                    return u0.SEND_SHARE_KAKAO_BUTTON;
                case 13105:
                    return u0.SEND_SHARE_LINE_BUTTON;
                case 13106:
                    return u0.SEND_SHARE_SMS_BUTTON;
                case 13107:
                    return u0.SEND_SHARE_EMAIL_BUTTON;
                case 13108:
                    return u0.SEND_SHARE_FB_LITE_BUTTON;
                case 13109:
                    return u0.SEND_SHARE_FB_MESSENGER_LITE_BUTTON;
                case 13110:
                    return u0.SEND_SHARE_TELEGRAM_BUTTON;
                case 13112:
                    return u0.SEND_SHARE_VIBER_BUTTON;
                case 13113:
                    return u0.SEND_SHARE_SKYPE_BUTTON;
                case 13115:
                    return u0.SEND_SHARE_INSTAGRAM_BUTTON;
                case 13116:
                    return u0.SEND_SHARE_REDDIT_BUTTON;
                case 13117:
                    return u0.IDEA_PIN_ARTIST;
                case 13123:
                    return u0.DATE_PICKER_OK_BUTTON;
                case 13124:
                    return u0.DATE_PICKER_CANCEL_BUTTON;
                case 13125:
                    return u0.VIRTUAL_TRY_ON_OPEN_GALLERY;
                case 13126:
                    return u0.VIRTUAL_TRY_ON_GALLERY_ICON;
                case 13127:
                    return u0.VIRTUAL_TRY_ON_CAMERA_ICON;
                case 13128:
                    return u0.VIRTUAL_TRY_ON_CAMERA;
                case 13129:
                    return u0.VIRTUAL_TRY_ON_IMAGE;
                case 13130:
                    return u0.VIRTUAL_TRY_ON_SELECT_FROM_GALLERY;
                case 13131:
                    return u0.VIRTUAL_TRY_ON_NO_FACE_DETECTED_OVERLAY;
                case 13135:
                    return u0.NEWS_HUB_HIDE_ITEM_BUTTON;
                case 13141:
                    return u0.DEFAULT_LANGUAGE_BUTTON;
                case 13142:
                    return u0.ADDITIONAL_LANGUAGE_BUTTON;
                case 13143:
                    return u0.DEFAULT_LANGUAGE;
                case 13144:
                    return u0.ADDITIONAL_LANGUAGE;
                case 13149:
                    return u0.AR_3D_PREVIEW_ICON;
                case 13150:
                    return u0.AR_ZOOM_ROTATE_CTA;
                case 13275:
                    return u0.PIN_CLOSEUP_PRODUCT_MORE_OPTIONS;
                case 13277:
                    return u0.PIN_CLOSEUP_PRODUCT_DETAILS_COLLAPSED;
                case 13278:
                    return u0.PIN_CLOSEUP_PRODUCT_DETAILS_EXPANDED;
                case 13286:
                    return u0.SEND_SHARE_TWITTER_BUTTON;
                case 13308:
                    return u0.CREATOR_HUB_RECENT_PINS_EMPTY_STATE_BUTTON;
                case 13332:
                    return u0.MFA_INVALID_EMAIL;
                case 13333:
                    return u0.UPDATE_EMAIL_ADDRESS_TXT;
                case 13348:
                    return u0.CREATOR_METRICS_TOAST;
                case 13349:
                    return u0.MESSAGING_PERMISSIONS_DIRECT_TO_INBOX;
                case 13350:
                    return u0.MESSAGING_PERMISSIONS_SEND_REQUEST;
                case 13351:
                    return u0.MESSAGING_PERMISSIONS_BLOCKED;
                case 13359:
                    return u0.HAIR_PATTERN_FILTER_REMEMBER_YES;
                case 13360:
                    return u0.HAIR_PATTERN_FILTER_REMEMBER_NO;
                case 13361:
                    return u0.PIN_AD_TARGETING_CHANGE_USER_SETTINGS;
                case 13371:
                    return u0.SKIN_TONE_FILTER_REMEMBER_DIALOG;
                case 13382:
                    return u0.ADS_ONLY_PROFILE_EXTERNAL;
                case 13383:
                    return u0.ADS_ONLY_PROFILE_REDIRECT;
                case 13389:
                    return u0.IDEA_PIN_CANVAS_ASPECT_RATIO_BUTTON;
                case 13390:
                    return u0.IDEA_PIN_CANVAS_CROPPER;
                case 13391:
                    return u0.IDEA_PIN_CANVAS_ORIENTATION_BUTTON;
                case 13395:
                    return u0.IDEA_PIN_CANVAS_ASPECT_RATIO_OPTION_BUTTON;
                case 13401:
                    return u0.PIN_AD_TARGETING_AD_PREFERENCES;
                case 13402:
                    return u0.PIN_AD_TARGETING_PRIVACY_POLICY;
                case 13407:
                    return u0.PIN_AD_TARGETING_CREATOR_PROFILE;
                case 13411:
                    return u0.LEAD_FORM_NAME;
                case 13412:
                    return u0.LEAD_FORM_EMAIL;
                case 13413:
                    return u0.LEAD_FORM_PHONE_NUMBER;
                case 13414:
                    return u0.LEAD_FORM_ZIPCODE;
                case 13498:
                    return u0.SEND_SHARE_SEARCH_ICON;
                case 13502:
                    return u0.CONVERSATION_INBOX_CONTACT_SYNC_BTN;
                case 13504:
                    return u0.GOOGLE_CONTINUE_BUTTON;
                case 13520:
                    return u0.FILTER_CLEAR_BUTTON;
                case 13521:
                    return u0.FILTER_SUBMIT_BUTTON;
                case 13533:
                    return u0.MULTI_TAB_TOPIC_TAB;
                case 13538:
                    return u0.QUIZ_PIN_QUESTION;
                case 13539:
                    return u0.QUIZ_PIN_RESULT;
                case 13540:
                    return u0.QUIZ_PIN_BACK_BUTTON;
                case 13541:
                    return u0.QUIZ_PIN_RESULT_FALLBACK;
                case 13545:
                    return u0.AD_CLICKTHROUGH_MEDIA;
                case 13547:
                    return u0.AD_CLICKTHROUGH_PROMOTER_NAME;
                case 13548:
                    return u0.AD_CLICKTHROUGH_TITLE;
                case 13575:
                    return u0.ANALYTICS_HELP_CENTER_OPTION;
                case 13576:
                    return u0.HELP_CENTER_OPTION;
                case 13577:
                    return u0.HOME_FEED_CONTROL_PANEL_ACTIVITY_TAB_FILTER_TYPE_DROPDOWN;
                case 13578:
                    return u0.HOME_FEED_CONTROL_PANEL_ACTIVITY_TAB_FILTER_TYPE_DROPDOWN_OPTION_ALL;
                case 13579:
                    return u0.HOME_FEED_CONTROL_PANEL_ACTIVITY_TAB_FILTER_TYPE_DROPDOWN_OPTION_SAVED;
                case 13580:
                    return u0.HOME_FEED_CONTROL_PANEL_ACTIVITY_TAB_FILTER_TYPE_DROPDOWN_OPTION_VIEWED;
                case 13581:
                    return u0.DSA_TURN_PROFILING_ON_BANNER_BUTTON;
                case 13592:
                    return u0.PIN_CLOSEUP_PRODUCT_BRAND_MERCHANT_LOCKUP;
                case 13593:
                    return u0.VIRTUAL_TRY_ON_MODEL;
                case 13594:
                    return u0.STELA_PRODUCTS_EXPAND_BUTTON;
                case 13595:
                    return u0.STELA_PRODUCTS_COLLAPSE_BUTTON;
                case 13604:
                    return u0.VIRTUAL_TRY_ON_MODEL_ICON;
                case 13608:
                    return u0.IDEA_PIN_PRODUCT_TAG_ADD_BUTTON;
                case 13609:
                    return u0.STORY_PIN_PRODUCT_TAGS_SECTION;
                case 13614:
                    return u0.LEAD_FORM_FIRST_NAME;
                case 13615:
                    return u0.LEAD_FORM_LAST_NAME;
                case 13616:
                    return u0.LEAD_FORM_AGE;
                case 13617:
                    return u0.LEAD_FORM_GENDER;
                case 13618:
                    return u0.LEAD_FORM_COUNTRY;
                case 13619:
                    return u0.LEAD_FORM_CITY;
                case 13620:
                    return u0.LEAD_FORM_STATE_PROVINCE;
                case 13621:
                    return u0.LEAD_FORM_CUSTOM_TEXT_FIELD;
                case 13622:
                    return u0.LEAD_FORM_CUSTOM_TEXT_AREA;
                case 13623:
                    return u0.LEAD_FORM_CUSTOM_RADIO_LIST;
                case 13624:
                    return u0.LEAD_FORM_CUSTOM_CHECKBOX;
                case 13634:
                    return u0.AD_CLICKTHROUGH_CHIN_CTA;
                case 13638:
                    return u0.RVC_VIEW_STATEMENT_OF_REASONS_LINK;
                case 13639:
                    return u0.RVC_CONTEXT_MENU_BUTTON;
                case 13640:
                    return u0.RVC_APPEAL_DECISION_OPTION;
                case 13641:
                    return u0.RVC_SELF_HARM_RESOURCES_OPTION;
                case 13642:
                    return u0.RVC_SUBMIT_APPEAL_BUTTON;
                case 13648:
                    return u0.PARENTAL_PASSCODE_OPTION;
                case 13688:
                    return u0.COMMENT_COMPOSER_IMAGE_CLOSE_BUTTON;
                case 13719:
                    return u0.MUSIC_PLAYLIST_ATTRIBUTION;
                case 13750:
                    return u0.PIN_STORY_PIN_MUTE_BUTTON;
                case 13752:
                    return u0.QUICK_SAVE_TOAST_VIEW;
                case 13808:
                    return u0.PASSCODE_TOGGLE;
                case 13823:
                    return u0.PINS_DISPLAY_OPTIONS_BUTTON;
                case 13824:
                    return u0.BOARDS_DISPLAY_OPTIONS_BUTTON;
                case 13825:
                    return u0.PINS_TAB_EMPTY_STATE_FIND_IDEAS_BUTTON;
                case 13826:
                    return u0.PINS_TAB_EMPTY_STATE_CREATE_IDEA_BUTTON;
                case 13827:
                    return u0.BOARDS_TAB_EMPTY_STATE_ORGANIZE_BUTTON;
                case 13830:
                    return u0.PIN_FILTER;
                case 13831:
                    return u0.PRIVATE_PROFILE_TOGGLE;
                case 13841:
                    return u0.PRODUCTS_CHIP;
                case 13844:
                    return u0.CREATE_COLLAGE_BUTTON;
                case 13846:
                    return u0.CUTOUT_TOOL_SAVE_BUTTON;
                case 13847:
                    return u0.CUTOUT_TOOL_LASSO_BUTTON;
                case 13848:
                    return u0.CUTOUT_TOOL_REFINE_BUTTON;
                case 13849:
                    return u0.CUTOUT_TOOL_REFINE_CONFIRM_BUTTON;
                case 13850:
                    return u0.CUTOUT_TOOL_REFINE_DISMISS_BUTTON;
                case 13851:
                    return u0.CUTOUT_TOOL_REFINE_ADD_BUTTON;
                case 13852:
                    return u0.CUTOUT_TOOL_REFINE_ERASE_BUTTON;
                case 13853:
                    return u0.PROFILE_ORGANIZE_BUTTON;
                case 13890:
                    return u0.BODY_TYPE_FILTER_REMEMBER_YES;
                case 13891:
                    return u0.BODY_TYPE_FILTER_REMEMBER_NO;
                case 13906:
                    return u0.PEAR_SURVEY_HAPPY;
                case 13907:
                    return u0.PEAR_SURVEY_NEUTRAL;
                case 13908:
                    return u0.PEAR_SURVEY_SAD;
                case 13910:
                    return u0.PEAR_SHARE_BUTTON;
                case 13923:
                    return u0.PEAR_STYLE_PILL;
                case 13930:
                    return u0.HOW_TO_CREATE_PINS_OPTION;
                case 13931:
                    return u0.SHARE_PROFILE;
                case 13932:
                    return u0.SEND_MESSAGE;
                case 13933:
                    return u0.NOT_NOW;
                case 13936:
                    return u0.SAVE_CHANGES_BUTTON;
                case 13937:
                    return u0.DISCARD_CHANGES_BUTTON;
                case 13939:
                    return u0.COLLAGE_COMPOSER_CUTOUT_PICKER_BUTTON;
                case 13940:
                    return u0.COLLAGE_COMPOSER_DRAWING_TOOL_BUTTON;
                case 13941:
                    return u0.COLLAGE_COMPOSER_TEXT_TOOL_BUTTON;
                case 13943:
                    return u0.COLLAGE_COMPOSER_PICKER_BOARDS_CARD;
                case 13944:
                    return u0.COLLAGE_COMPOSER_PICKER_YOUR_CUTOUTS_CARD;
                case 13945:
                    return u0.COLLAGE_COMPOSER_PICKER_RECENT_SAVES_CARD;
                case 13953:
                    return u0.SHOP_BUTTON;
                case 13974:
                    return u0.COLLAGE_COMPOSER_NEXT_TRAY_SAVE_AND_EXIT;
                case 13975:
                    return u0.COLLAGE_COMPOSER_ITEM;
                case 13976:
                    return u0.COLLAGE_COMPOSER_ITEM_DELETE;
                case 13977:
                    return u0.COLLAGE_COMPOSER_ITEM_SAVE;
                case 13978:
                    return u0.COLLAGE_COMPOSER_ITEM_DUPLICATE;
                case 13979:
                    return u0.COLLAGE_COMPOSER_ITEM_EDIT;
                case 13980:
                    return u0.CUTOUT_TOOL_CROP_BUTTON;
                case 13997:
                    return u0.SKIN_TONE_FILTER_EXPAND_BUTTON;
                case 13998:
                    return u0.SKIN_TONE_FILTER_COLLAPSE_BUTTON;
                case 13999:
                    return u0.CLOSEUP_DETAILS_LIST_EXPAND_BUTTON;
                case 14000:
                    return u0.CLOSEUP_DETAILS_LIST_COLLAPSE_BUTTON;
                case 14001:
                    return u0.RICH_RECIPE_EXPAND_BUTTON;
                case 14002:
                    return u0.RICH_RECIPE_COLLAPSE_BUTTON;
                case 14003:
                    return u0.CREATOR_ANALYTICS_OPEN_DRAWER_BUTTON;
                case 14012:
                    return u0.STICKER_COMMENT_BUTTON;
                case 14014:
                    return u0.RELATED_PINS_FILTER_REP;
                case 14015:
                    return u0.SHUFFLES_COLLAGE_CREATE_PUBLISH_BUTTON;
                case 14016:
                    return u0.SHUFFLES_COLLAGE_CREATE_SAVE_FOR_LATER_BUTTON;
                case 14025:
                    return u0.COLLAGE_COMPOSER_CAMERA_TOOL_BUTTON;
                case 14026:
                    return u0.COLLAGE_COMPOSER_ASSET_PICKER_TOOL_BUTTON;
                case 14058:
                    return u0.PRIVACY_BLOCKER_CONFIRM_BUTTON;
                case 14059:
                    return u0.PRIVACY_BLOCKER_MANAGE_BUTTON;
                case 14063:
                    return u0.COLLAGE_COMPOSER_NEXT_TRAY_HOW_COLLAGING_WORKS;
                case 14074:
                    return u0.PIN_COMMENT_TEXTVIEW;
                case 14076:
                    return u0.COMMENT_REACT_BUTTON;
                case 14077:
                    return u0.CREATOR_MODULE;
                case 14080:
                    return u0.COLLAGE_COMPOSER_ITEM_RETRY;
                case 14114:
                    return u0.COLLAGE_COMPOSER_COMMUNITY_CUTOUTS_CUTOUTS_FOR_YOU_CARD;
                case 14115:
                    return u0.COLLAGE_COMPOSER_MOTION_EFFECT_TAB;
                case 14116:
                    return u0.COLLAGE_COMPOSER_COLOR_EFFECT_TAB;
                case 14117:
                    return u0.COLLAGE_COMPOSER_BORDER_EFFECT_TAB;
                case 14118:
                    return u0.COLLAGE_COMPOSER_EFFECT_APPLY;
                case 14119:
                    return u0.COLLAGE_COMPOSER_COMMUNITY_CUTOUTS_CUTOUTS_FOR_YOU_SINGLE_CUTOUT;
                case 14120:
                    return u0.EXTERNAL_SHARE_OPTION;
                case 14121:
                    return u0.ANKET_DISLIKE_ANSWER;
                case 14122:
                    return u0.ANKET_LIKE_ANSWER;
                case 14123:
                    return u0.ANKET_SAD_EMOJI_ANSWER;
                case 14124:
                    return u0.ANKET_NEUTRAL_EMOJI_ANSWER;
                case 14125:
                    return u0.ANKET_HAPPY_EMOJI_ANSWER;
                case 14126:
                    return u0.ANKET_FIRST_SCALE_ANSWER;
                case 14127:
                    return u0.ANKET_SECOND_SCALE_ANSWER;
                case 14128:
                    return u0.ANKET_THIRD_SCALE_ANSWER;
                case 14129:
                    return u0.ANKET_FOURTH_SCALE_ANSWER;
                case 14130:
                    return u0.ANKET_FIFTH_SCALE_ANSWER;
                case 14179:
                    return u0.BOARD_RESTORE_BUTTON;
                case 14180:
                    return u0.ADD_TO_COLLAGE_BUTTON;
                case 14187:
                    return u0.BOARDLESS_PIN_ORGANIZE_DONE_BUTTON;
                case 14204:
                    return u0.MORE_IDEAS_SECTION_NAME;
                case 14264:
                    return u0.FILTER;
                case 14265:
                    return u0.BOARD_ADD_COLLABORATOR_EMPTY_STATE;
                case 14266:
                    return u0.REPIN_ANIMATION_DEFAULT;
                case 14267:
                    return u0.REPIN_ANIMATION_DEFAULT_WITH_CONFETTI;
                case 14268:
                    return u0.REPIN_ANIMATION_EXAGGERATED;
                case 14269:
                    return u0.REPIN_ANIMATION_EXAGGERATED_WITH_CONFETTI;
                case 14271:
                    return u0.QUIZ_PIN_AUTO_SCROLL_PREVIEW;
                case 14273:
                    return u0.COLLAGE_COMPOSER_OPTIONS_TAB;
                case 14275:
                    return u0.PEAR_ANSWER_BUTTON;
                case 14276:
                    return u0.PEAR_RETAKE_QUIZ_BUTTON;
                case 14277:
                    return u0.COLLAGE_COMPOSER_NEXT_TRAY_START_NEW_COLLAGE;
                case 14283:
                    return u0.RECOMMENDED_BOARD_PAGE;
                case 14285:
                    return u0.ANKET_FIRST_VERTICAL_SCALE_ANSWER;
                case 14286:
                    return u0.ANKET_SECOND_VERTICAL_SCALE_ANSWER;
                case 14287:
                    return u0.ANKET_THIRD_VERTICAL_SCALE_ANSWER;
                case 14288:
                    return u0.ANKET_FOURTH_VERTICAL_SCALE_ANSWER;
                case 14289:
                    return u0.ANKET_FIFTH_VERTICAL_SCALE_ANSWER;
                case 14291:
                    return u0.SHOPPING_PRICE_FILTER;
                case 14303:
                    return u0.ONE_TAP_SAVE_EDIT;
                case 14304:
                    return u0.AUTH_COLLECTION_EMAIL_INPUT;
                case 14305:
                    return u0.AUTH_COLLECTION_DISMISS_MASK;
                case 14306:
                    return u0.AUTH_COLLECTION_PASSWORD_INPUT;
                case 14310:
                    return u0.CLOSED_CAPTIONS_BUTTON;
                case 14321:
                    return u0.TEEN_SAFETY_RESOURCES_LINK;
                case 14326:
                    return u0.BOARD_CREATOR_NAME;
                case 14327:
                    return u0.BOARD_CREATOR_AVATAR;
                case 14328:
                    return u0.REPIN_COUNT;
                case 14340:
                    return u0.STRUCTURED_FEED_HEADER_THUMBNAIL;
                case 14348:
                    return u0.INLINE_BOARD_PICKER;
                case 14352:
                    return u0.COLLAGE_COMPOSER_CAROUSEL_DRAFTS_CARD;
                case 14354:
                    return u0.COLLAGE_COMPOSER_CAROUSEL_TUTORIAL_CARD;
                case 14356:
                    return u0.COLLAGE_COMPOSER_ITEM_SWAP;
                case 14357:
                    return u0.SHOPPING_MERCHANT_FILTER;
                case 14361:
                    return u0.COLLAGE_REMIX_COLLAGE_BUTTON;
                case 14363:
                    return u0.COLLAGE_COMPOSER_CAROUSEL_REMIX_CARD;
                case 14366:
                    return u0.ROOM_REPAINTING_MODULE;
                case 14367:
                    return u0.CONTINUE_SSO_BUTTON;
                case 14372:
                    return u0.FLOATING_WEBSITE_BUTTON;
                case 14373:
                    return u0.PIN_LINK_MODULE_FLOATING_VISIT_BAR;
                case 14376:
                    return u0.AD_CLICKTHROUGH_EXPAND;
                case 14377:
                    return u0.BOARD_UNORGANIZED_IDEAS;
                case 14380:
                    return u0.ROOM_REPAINT_RESULT_THUMBUP;
                case 14381:
                    return u0.ROOM_REPAINT_RESULT_THUMBDOWN;
                case 14382:
                    return u0.ROOM_REPAINT_RESULT_SHARE;
                case 14383:
                    return u0.ROOM_REPAINT_RESULT_DOWNLOAD;
                case 14384:
                    return u0.ROOM_REPAINT_RESULT_REPORT;
                case 14385:
                    return u0.ROOM_REPAINT_STYLE_PICKER_CANCEL;
                case 14386:
                    return u0.ROOM_REPAINT_GENERATION_CANCEL;
                case 14389:
                    return u0.PIN_FEEDBACK_COPY_LINK;
                case 14392:
                    return u0.BOARD_MORE_IDEAS_PRODUCT_PIVOTS;
                case 14394:
                    return u0.ROOM_REPAINT_START_GENERATION;
                case 14396:
                    return u0.ROOM_REPAINT_GENERATION_SUCCESS;
                case 14397:
                    return u0.ROOM_REPAINT_GENERATION_FAILED;
                case 14415:
                    return u0.CLOSEUP_COMMENT_POST;
                case 14421:
                    return u0.RELATED_PINS_RESET_ALL_FILTERS_BUTTON;
                case 14422:
                    return u0.RELATED_PINS_FILTER_OPTION_REP;
                case 14424:
                    return u0.SHOPPING_BRAND_FILTER;
                case 14433:
                    return u0.HAIR_PATTERN_FILTER_EXPAND_BUTTON;
                case 14434:
                    return u0.HAIR_PATTERN_FILTER_COLLAPSE_BUTTON;
                case 14446:
                    return u0.BOARD_PREVIEW_COPY_LINK_FIELD;
                case 14447:
                    return u0.BOARD_PREVIEW_TEMPLATE_PREVIEW;
                case 14449:
                    return u0.SHOPPING_ON_SALE_FILTER;
                case 14450:
                    return u0.AUTH_COLLECTION_BANNER;
                case 14460:
                    return u0.EDIT_BOARD_HEADER_BUTTON;
                case 14461:
                    return u0.DELETE_BOARD_HEADER_BUTTON;
                case 14462:
                    return u0.BOARD_HEADER_IMAGE_PREVIEW;
                case 14463:
                    return u0.BOARD_HEADER_IMAGE;
                case 14468:
                    return u0.PIN_CREATION_EDITOR_BUTTON;
                case 14473:
                    return u0.PIN_FEEDBACK_REASON_WRONG_SKIN_TONE;
                case 14474:
                    return u0.PIN_FEEDBACK_REASON_WRONG_HAIR_PATTER;
                case 14475:
                    return u0.PIN_FEEDBACK_REASON_WRONG_BODY_TYPE;
                case 14487:
                    return u0.HF_TAB_UNFOLLOW_BUTTON;
                case 14488:
                    return u0.HF_TAB_UNFOLLOW_UNDO_BUTTON;
                case 14489:
                    return u0.HF_TAB_MODAL_UNFOLLOW_BUTTON;
                case 14490:
                    return u0.HF_TAB_MODAL_CANCEL_BUTTON;
                case 14497:
                    return u0.DISABLED_VIDEO_UNMUTE_BUTTON;
                case 14498:
                    return u0.BOARD_FILTER_FAVORITE_EMPTY_STATE;
                case 14499:
                    return u0.BOARD_GROUPING_NAME;
                case 14538:
                    return u0.COLLAGE_DRAFT_CELL_DELETE_BUTTON;
                case 14539:
                    return u0.COLLAGE_DRAFT_CELL_DUPLICATE_BUTTON;
                case 14571:
                    return u0.END_SESSION_BUTTON;
                case 14574:
                    return u0.USE_CASE_PIN;
                case 14575:
                    return u0.USE_CASE_PIN_FOLLOW;
                case 14576:
                    return u0.USE_CASE_PIN_UNFOLLOW;
                case 14577:
                    return u0.COLLAGES_TAB_EMPTY_STATE_BUTTON;
                case 14583:
                    return u0.ONE_TAP_SAVE_BUTTON;
                case 14584:
                    return u0.MULTI_TAB_PINTEREST_PICKS_TAB;
                case 14585:
                    return u0.FILTER_BUTTON_COUNT_BADGE;
                case 14597:
                    return u0.CONVERSATION_HIDE_BUTTON;
                case 14599:
                    return u0.CONVERSATION_NOTIFICATIONS_ALWAYS_ON_BUTTON;
                case 14600:
                    return u0.CONVERSATION_NOTIFICATIONS_MUTE_ONE_HOUR_BUTTON;
                case 14601:
                    return u0.CONVERSATION_NOTIFICATIONS_MUTE_EIGHT_HOURS_BUTTON;
                case 14602:
                    return u0.CONVERSATION_NOTIFICATIONS_MUTE_ONE_WEEK_BUTTON;
                case 14603:
                    return u0.CONVERSATION_NOTIFICATIONS_MUTE_INDEFINITELY_BUTTON;
                case 14604:
                    return u0.AD_CLICKTHROUGH_HEADER;
                case 14652:
                    return u0.FILTER_ERROR_STATE_BUTTON;
                case 14660:
                    return u0.CLOSEUP_METADATA_EXPAND_BUTTON;
                case 14661:
                    return u0.CLOSEUP_METADATA_COLLAPSE_BUTTON;
                case 14663:
                    return u0.CLOSEUP_PDP_METADATA_EXPAND_BUTTON;
                case 14664:
                    return u0.CLOSEUP_PDP_METADATA_COLLAPSE_BUTTON;
                case 14680:
                    return u0.USER_REMOVE_BUTTON;
                case 14684:
                    return u0.AD_CLICKTHROUGH_PROMO_METADATA;
                case 14886:
                    return u0.LEAD_FORM_ADDRESS;
                case 14914:
                    return u0.LEAD_FORM_DATE_OF_BIRTH;
                case 15873:
                    return u0.ACCOUNT_RESILIENCE_UPSELL;
                case 15874:
                    return u0.ADS_STL_CATEGORY_ITEM;
                case 15875:
                    return u0.ADS_STL_HEADER;
                case 15876:
                    return u0.URL_BUILDER_SAVE_BUTTON;
                case 15877:
                    return u0.URL_BUILDER_DISMISS_BUTTON;
                case 15878:
                    return u0.URL_BUILDER_RESET_BUTTON;
                case 15879:
                    return u0.URL_BUILDER_ADD_PARAMETER_BUTTON;
                case 15880:
                    return u0.URL_BUILDER_REMOVE_PARAMETER_BUTTON;
                case 15881:
                    return u0.PERFORMANCE_PLUS_EDIT_AD_GROUP_URL_PARAMS_BUTTON;
                case 15882:
                    return u0.SAVE_AND_APPLY_URL_PARAMS_MODAL_CANCEL_BUTTON;
                case 15883:
                    return u0.SAVE_AND_APPLY_URL_PARAMS_MODAL_SAVE_BUTTON;
                case 15889:
                    return u0.CLOSEUP_BOARD_TOOLS_COLLAPSE_BUTTON;
                case 15890:
                    return u0.CLOSEUP_BOARD_TOOLS_EXPAND_BUTTON;
                case 15893:
                    return u0.PERFORMANCE_PLUS_CAMPAIGN_BUDGET_TYPE_DROPDOWN;
                case 15894:
                    return u0.PERFORMANCE_PLUS_AD_GROUP_TARGETING_AGE_HELP_BUTTON;
                case 15895:
                    return u0.PIN_STATS_METRICS_SEGMENTED_CONTROL;
                case 15896:
                    return u0.PIN_STATS_TAGGED_PRODUCTS_METRIC_SELECTLIST;
                case 15899:
                    return u0.PIN_STATS_TAGGED_PRODUCTS_TABLE_SORT;
                case 15900:
                    return u0.SHOW_MORE_BUTTON;
                case 15901:
                    return u0.PERFORMANCE_PLUS_CAMPAIGN_BUDGET_TYPE_DROPDOWN_LEARN_MORE_LINK;
                case 15908:
                    return u0.PIN_STATS_TAGGED_PRODUCTS_DETAILS_BUTTON;
                case 15909:
                    return u0.PIN_STATS_TAGGED_PRODUCTS_INFO_BUTTON;
                case 15910:
                    return u0.ANALYTICS_GRAPH_CLOSEUP_TAGGED_PRODUCTS_METRIC_SELECTLIST;
                case 15912:
                    return u0.BUSINESS_HUB_AUDIENCE_SECTION_WRAPPER;
                case 15913:
                    return u0.BUSINESS_HUB_VIEW_AUDIENCE_INSIGHTS;
                case 15914:
                    return u0.BUSINESS_HUB_VIEW_TRENDS;
                case 15917:
                    return u0.SEND_SHARE_PREVIEW_EDIT_BUTTON;
                case 15918:
                    return u0.SEND_SHARE_PREVIEW_CAROUSEL;
                case 15920:
                    return u0.WAISTA_GEN_AI_LABEL;
                case 15921:
                    return u0.PERFORMANCE_PLUS_RETARGETING_AD_GROUP_NAME_POPOVER_LEARN_MORE_LINK;
                case 15925:
                    return u0.PERFORMANCE_PLUS_AD_GROUP_URL_PARAMS_INFO_ICON;
                case 15926:
                    return u0.DWEB_DL_COLLECTION_ADS;
                case 15927:
                    return u0.MWEB_DL_COLLECTION_ADS;
                case 15928:
                    return u0.CREATE_PASSWORD_BUTTON;
                case 15929:
                    return u0.CREATE_PASSWORD_LINK;
                case 15930:
                    return u0.MOVE_GOOGLE_LOGIN_BUTTON;
                case 15931:
                    return u0.MOVE_GOOGLE_LOGIN_LINK;
                case 15933:
                    return u0.BOARD_ALLOW_SHOP_MODULE;
                case 15935:
                    return u0.PROMOTION_MISLEADING;
                case 15936:
                    return u0.POST_CREATE_UPSELL_CONNECT_BUTTON;
                case 15937:
                    return u0.AD_CLICKTHROUGH_DISCLOSURE;
                case 15945:
                    return u0.MULTI_TAB_USE_CASE_TAB;
                case 15946:
                    return u0.USE_CASE_FEED_ONE_TAP_SAVE_BUTTON;
                case 15947:
                    return u0.EDIT_CAMPAIGN_URL_PARAMS_BUTTON;
                case 15949:
                    return u0.PEAR_ENTER_QUIZ_BUTTON;
                case 15950:
                    return u0.USE_CASE;
                case 15953:
                    return u0.PEAR_QUIZ_BOARD;
                case 15954:
                    return u0.NEWS_HUB_TITLE_TEXT;
                case 15966:
                    return u0.PERFORMANCE_PLUS_MDL_RADIO_BUTTON_DEFAULT_SELECT;
                case 15968:
                    return u0.CREATE_PROMOTIONS_CTA;
                case 15969:
                    return u0.PROMO_MODAL_CREATE_BUTTON;
                case 15970:
                    return u0.PROMO_MODAL_CREATE_CAMPAIGN_BUTTON;
                case 15971:
                    return u0.PROMO_MODAL_APPLY_PROMO_BUTTON;
                case 15972:
                    return u0.PROMO_MODAL_ALL_CAMPAIGNS_CHECKBOX;
                case 15973:
                    return u0.PROMO_MODAL_CAMPAIGN_ROW_CHECKBOX;
                case 15974:
                    return u0.PROMO_MODAL_AD_GROUP_ROW_CHECKBOX;
                case 15975:
                    return u0.PROMO_APPLIED_TOAST;
                case 15976:
                    return u0.PROMO_TYPE_SELECTLIST;
                case 15977:
                    return u0.SEARCH_BOX_VOICE_INPUT;
                case 15978:
                    return u0.VOICE_SEARCH_SUCCESS;
                case 15979:
                    return u0.VOICE_SEARCH_FAILURE;
                case 15980:
                    return u0.COLLAGE_COMPOSER_LAYERS_TOOL_BUTTON;
                case 15981:
                    return u0.COLLAGE_COMPOSER_MORE_TOOL_BUTTON;
                case 15982:
                    return u0.COLLAGE_COMPOSER_TOOL_OVERFLOW_MENU;
                case 15983:
                    return u0.ACCOUNT_CLAIMING_BUTTON;
                case 15996:
                    return u0.STRUCTURED_FEED_HEADER_ATTRIBUTION_LINK;
                case 15998:
                    return u0.COLLAGES_TAB_CREATE_NEW;
                case 16007:
                    return u0.PIN_FEATURED_HOLIDAY_BOARD_PREVIEW;
                case 16011:
                    return u0.EU_PERSONALIZED_ADS_PROMPT_INTRO;
                case 16012:
                    return u0.EU_PERSONALIZED_ADS_PROMPT_SELECTION;
                case 16013:
                    return u0.EU_PERSONALIZED_ADS_PROMPT_PREFERENCE_BUTTON;
                case 16014:
                    return u0.EU_PERSONALIZED_ADS_PROMPT_CONFIRM_BUTTON;
                case 16015:
                    return u0.EU_PERSONALIZED_ADS_PROMPT_PAGE_SWITCH_BUTTON;
                case 16016:
                    return u0.COLLAGE_COMPOSER_NEXT_TRAY_DUPLICATE_COLLAGE;
                case 16017:
                    return u0.GROUP_BOARD_JOIN_BUTTON;
                case 16021:
                    return u0.SEARCH_ACCOUNT_BTN;
                case 16033:
                    return u0.SEND_NEW_CODE_LINK;
                case 16034:
                    return u0.CONFIRM_EMAIL_CHANGE_MODAL;
                case 16035:
                    return u0.ENTER_BUTTON;
                case 16036:
                    return u0.OKAY_BUTTON;
                case 16037:
                    return u0.RVC_COUNTER_NOTICE_FORM_BUTTON;
                case 16038:
                    return u0.BUSINESS_HUB_CATALOGS_OVERVIEW;
                case 16039:
                    return u0.STRUCTURED_FEED_EMPTY_STATE_BUTTON;
                case 16046:
                    return u0.CATALOGS_OVERVIEW_BEGIN_REVIEW_BUTTON_CLAIMED_WEBSITE;
                case 16047:
                    return u0.CATALOGS_OVERVIEW_BEGIN_REVIEW_BUTTON_UPLOAD_CATALOG;
                case 16048:
                    return u0.CATALOGS_OVERVIEW_BEGIN_REVIEW_BUTTON_CONVERSIONS;
                case 16049:
                    return u0.CATALOGS_OVERVIEW_BEGIN_REVIEW_MODAL;
                case 16050:
                    return u0.CATALOGS_OVERVIEW_ADS_CREDIT_DISMISS_BUTTON;
                case 16051:
                    return u0.CATALOGS_OVERVIEW_ADS_CREDIT_COMPLETE_BUTTON;
                case 16052:
                    return u0.CATALOGS_OVERVIEW_BEST_PRACTICES_INGESTION;
                case 16053:
                    return u0.CATALOGS_OVERVIEW_BEST_PRACTICES_PRODUCT_GROUPS;
                case 16054:
                    return u0.CATALOGS_OVERVIEW_CONVERSION_UPSELL_DISMISS_BUTTON;
                case 16055:
                    return u0.CATALOGS_OVERVIEW_CONVERSION_UPSELL_COMPLETE_BUTTON;
                case 16056:
                    return u0.CATALOGS_OVERVIEW_DIAGNOSTICS_WIDGET_CTA;
                case 16057:
                    return u0.CATALOGS_OVERVIEW_ANALYTICS_WIDGET_CTA;
                case 16058:
                    return u0.CATALOGS_OVERVIEW_NOT_APPROVED_SUBMIT_BUTTON;
                case 16059:
                    return u0.CATALOGS_OVERVIEW_PROMOTE_YOUR_PRODUCTS_CTA;
                case 16060:
                    return u0.CATALOG_OVERVIEW_PROMOTE_YOUR_PRODUCTS_NAME_LINK;
                case 16061:
                    return u0.CATALOG_OVERVIEW_PROMOTE_YOUR_PRODUCTS_CAMPAIGN_LINK;
                case 16062:
                    return u0.CATALOG_OVERVIEW_PROMOTE_YOUR_PRODUCTS_PROMOTE_LINK;
                case 16063:
                    return u0.CATALOGS_OVERVIEW_SUCCESS_STORIES_IKEA;
                case 16064:
                    return u0.CATALOGS_OVERVIEW_SUCCESS_STORIES_PACSUN;
                case 16077:
                    return u0.BOARD_TOOL_LOOKBOOK;
                case 16079:
                    return u0.AD_LIMIT_WEIGHT_LOSS;
                case 16080:
                    return u0.WL_CONTROL_SEE_LESS;
                case 16091:
                    return u0.CATALOGS_OVERVIEW_GENERIC_ADS_UPSELL_DISMISS_BUTTON;
                case 16092:
                    return u0.CATALOGS_OVERVIEW_GENERIC_ADS_UPSELL_COMPLETE_BUTTON;
                case 16094:
                    return u0.CATALOGS_OVERVIEW_ADS_RECOMMENDATION_BANNER_DISMISS_BUTTON;
                case 16095:
                    return u0.CATALOGS_OVERVIEW_ADS_RECOMMENDATION_BANNER_CTA_BUTTON;
                case 16096:
                    return u0.CATALOGS_OVERVIEW_ADS_RECOMMENDATION_BANNER_TOAST;
                case 16097:
                    return u0.CATALOGS_OVERVIEW_HERO_CAROUSEL_DISMISS_BUTTON;
                case 16098:
                    return u0.CATALOGS_OVERVIEW_HERO_CAROUSEL_CTA_BUTTON;
                case 16099:
                    return u0.ABOUT_AUTOMAGICAL_BOARD_BUTTON;
                case 16142:
                    return u0.VOICE_SEARCH_CANCELLED;
                case 16147:
                    return u0.CREATE_BOARD_GRID_REP;
                case 16148:
                    return u0.PROFILE_NO_BOARDS_EMPTY_STATE;
                case 16149:
                    return u0.PIN_SEE_MORE_BUTTON;
                case 16150:
                    return u0.PIN_SEE_MORE_UNDO_BUTTON;
                case 16151:
                    return u0.PIN_SEE_LESS_BUTTON;
                case 16152:
                    return u0.PIN_SEE_LESS_UNDO_BUTTON;
                case 16153:
                    return u0.AMAZON_CONNECT;
                case 16155:
                    return u0.COLLAGE_COMPOSER_ITEM_DOWNLOAD;
                case 16156:
                    return u0.COLLAGE_COMPOSER_ITEM_REMIX;
                case 16157:
                    return u0.COLLAGE_COMPOSER_ITEM_SHARE;
                case 16158:
                    return u0.PIN_SAVED_SPLIT_BUTTON_TEXT;
                case 16159:
                    return u0.PIN_SAVED_SPLIT_BUTTON_ICON;
                case 16162:
                    return u0.COLLAGE_COMPOSER_OVERFLOW_MENU_DOWNLOAD_IMAGE;
                case 16163:
                    return u0.COLLAGE_COMPOSER_OVERFLOW_MENU_CREATE_PIN;
                case 16164:
                    return u0.COLLAGE_COMPOSER_OVERFLOW_MENU_SAVE_AND_EXIT;
                case 16165:
                    return u0.COLLAGE_COMPOSER_OVERFLOW_MENU_HOW_COLLAGING_WORKS;
                case 16166:
                    return u0.COLLAGE_COMPOSER_OVERFLOW_MENU_START_NEW_COLLAGE;
                case 16167:
                    return u0.COLLAGE_COMPOSER_OVERFLOW_MENU_DUPLICATE_COLLAGE;
                case 16168:
                    return u0.COLLAGE_COMPOSER_OVERFLOW_MENU_DELETE;
                case 16169:
                    return u0.COLLAGE_COMPOSER_OVERFLOW_MENU_SAVE;
                case 16170:
                    return u0.COLLAGE_COMPOSER_OVERFLOW_MENU_DUPLICATE;
                case 16171:
                    return u0.COLLAGE_COMPOSER_OVERFLOW_MENU_DOWNLOAD;
                case 16172:
                    return u0.COLLAGE_COMPOSER_OVERFLOW_MENU_REMIX;
                case 16173:
                    return u0.COLLAGE_COMPOSER_OVERFLOW_MENU_SHARE;
                case 16174:
                    return u0.COLLAGE_QUICK_SWAP_BUTTON;
                case 16175:
                    return u0.COLLAGE_QUICK_SWAP_RANDOM_BUTTON;
                case 16176:
                    return u0.LONG_PRESS_FLASHLIGHT;
                case 16177:
                    return u0.LONG_PRESS_PIN_DESCRIPTOR;
                case 16185:
                    return u0.RELATED_SEARCH_OPTION;
                case 16186:
                    return u0.LONG_PRESS_VISUAL_SEARCH;
                case 16187:
                    return u0.PERFORMANCE_PLUS_AD_GROUP_TARGETING_COUNTRY_DROPDOWN;
                case 16188:
                    return u0.PERFORMANCE_PLUS_AD_GROUP_TARGETING_COUNTRY_CLEAR_BUTTON;
                case 16189:
                    return u0.PERFORMANCE_PLUS_AD_GROUP_TARGETING_COUNTRY_REGION_SELECTOR;
                case 16190:
                    return u0.PERFORMANCE_PLUS_AD_GROUP_TARGETING_ALL_AGES_RADIO_BUTTON;
                case 16191:
                    return u0.PERFORMANCE_PLUS_AD_GROUP_TARGETING_18_PLUS_RADIO_BUTTON;
                case 16196:
                    return u0.LONG_PRESS_CUTOUT_ANIMATION;
                case 16197:
                    return u0.VISUAL_SEARCH_HOVER_GLOW_ANIMATION;
                case 16198:
                    return u0.INSTAGRAM_LINK_BUTTON;
                case 16212:
                    return u0.DELETE_MESSAGE_BUTTON;
                case 16213:
                    return u0.DELETE_MESSAGE_CONFIRM_BUTTON;
                case 16214:
                    return u0.DELETE_MESSAGE_CANCEL_BUTTON;
                case 16215:
                    return u0.PIN_GENAI_LEARN_MORE_LINK;
                case 16216:
                    return u0.COLLAGE_COMPOSER_ITEM_VIEW;
                case 16226:
                    return u0.PIN_SEE_LESS_GEN_AI_TOPIC_BUTTON;
                case 16235:
                    return u0.URL_BUILDER_ENCODE_WARNING_BANNER;
                case 16236:
                    return u0.QR_CODE_CONFIRM_BUTTON;
                case 16237:
                    return u0.QR_CODE_REJECT_BUTTON;
                case 16238:
                    return u0.QR_CODE_CONFIRMATION_TOAST;
                case 16239:
                    return u0.QR_CODE_ERROR_OK_BUTTON;
                case 16248:
                    return u0.QR_CODE_ERROR_TOAST;
                case 16275:
                    return u0.PEAR_INSIGHT_STORY_ENTRY_POINT;
                case 16283:
                    return u0.CANCEL_TEST_BUTTON;
                case 16284:
                    return u0.AB_TEST_FEASIBILITY_RESULT;
                case 16285:
                    return u0.SELECT_CAMPAIGNS_TABLE_FILTER_OPTION;
                case 16311:
                    return u0.AUDIENCE_PAGE_MANAGE_CUSTOMER_GROUPS_BUTTON;
                case 16313:
                    return u0.VISUAL_ANSWERS_SEARCH_STORY_CARD_STACK;
                case 16314:
                    return u0.VISUAL_ANSWERS_FEED_SECTION_CAROUSEL;
                case 16315:
                    return u0.VISUAL_ANSWERS_FEED_RELATED_QUESTION;
                case 16316:
                    return u0.SPEND_CONTROL_TOGGLE;
                case 16320:
                    return u0.CUTOUT_TOOL_SHAPE_PREVIEW;
                case 16321:
                    return u0.COLLAGE_DRAFTS_TAB;
                case 16322:
                    return u0.COLLAGE_TEMPLATES_TAB;
                case 16323:
                    return u0.COLLAGE_TEMPLATE_PREVIEW;
                case 18000:
                    return u0.AUTO_PRODUCT_TAG_FEEDBACK;
                case 19876:
                    return u0.BOARD_TOOL_STYLE_INSIGHT;
                case 20001:
                    return u0.SHOPPING_SORT_FILTER_TABLE_CELL;
                case 20005:
                    return u0.FOLLOW_UP_REASON;
                default:
                    switch (i13) {
                        case 22:
                            return u0.BOARD_CREATE;
                        case 23:
                            return u0.BOARD_CREATE_SUGGESTED;
                        case 24:
                            return u0.ANALYTICS_BUTTON;
                        default:
                            switch (i13) {
                                case 43:
                                    return u0.SEARCH_BUTTON;
                                case 44:
                                    return u0.CREATE_BUTTON;
                                case 45:
                                    return u0.REFRESH_BUTTON;
                                default:
                                    switch (i13) {
                                        case 47:
                                            return u0.PIN_REPORT_BUTTON;
                                        case 48:
                                            return u0.PIN_SAVE_BUTTON;
                                        case 49:
                                            return u0.PIN_DELETE_BUTTON;
                                        case 50:
                                            return u0.BOARD_DELETE_BUTTON;
                                        default:
                                            switch (i13) {
                                                case 59:
                                                    return u0.INVITE_BUTTON;
                                                case 60:
                                                    return u0.SUPPORT_BUTTON;
                                                case 61:
                                                    return u0.TOS_BUTTON;
                                                case 62:
                                                    return u0.USER_FOLLOW;
                                                case 63:
                                                    return u0.PROFILE_IMAGE;
                                                default:
                                                    return null;
                                            }
                                    }
                            }
                    }
            }
        }
        return u0.PIN_BOARD;
    }
}
