package n00;

import com.pinterest.feature.core.view.RecyclerViewTypes;
import lb.l0;
import org.jetbrains.annotations.NotNull;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes.dex */
public final class c {
    private static final /* synthetic */ el2.a $ENTRIES;
    private static final /* synthetic */ c[] $VALUES;
    public static final c INVALID = new c("INVALID", 0);
    public static final c DYNAMIC_GRID_FEED = new c("DYNAMIC_GRID_FEED", 1);
    public static final c DYNAMIC_GRID_FEED_WITH_BOARD_FIELDS = new c("DYNAMIC_GRID_FEED_WITH_BOARD_FIELDS", 2);
    public static final c USER_ME = new c("USER_ME", 3);
    public static final c DEFAULT_USER_FEED = new c("DEFAULT_USER_FEED", 4);
    public static final c USER_PROFILE = new c("USER_PROFILE", 5);
    public static final c DEFAULT_BOARD_FEED = new c("DEFAULT_BOARD_FEED", 6);
    public static final c DEFAULT_BOARD_FEED_LARGE_THUMBNAILS = new c("DEFAULT_BOARD_FEED_LARGE_THUMBNAILS", 7);
    public static final c BOARD_PICKER_FRAGMENT = new c("BOARD_PICKER_FRAGMENT", 8);
    public static final c BOARD_INVITES_DETAILS = new c("BOARD_INVITES_DETAILS", 9);
    public static final c BOARD_RELATED_FEED = new c("BOARD_RELATED_FEED", 10);
    public static final c INTEREST_FEED_DEFAULT = new c("INTEREST_FEED_DEFAULT", 11);
    public static final c INTEREST_FOLLOWED_FEED = new c("INTEREST_FOLLOWED_FEED", 12);
    public static final c USECASE_DEFAULT = new c("USECASE_DEFAULT", 13);
    public static final c DID_IT_MODEL = new c("DID_IT_MODEL", 14);
    public static final c PIN_CLOSEUP_SCREENSHOT = new c("PIN_CLOSEUP_SCREENSHOT", 15);
    public static final c CONTEXTUAL_EXPLORE = new c("CONTEXTUAL_EXPLORE", 16);
    public static final c EXPLORE_ARTICLE_COVER = new c("EXPLORE_ARTICLE_COVER", 17);
    public static final c EXPLORE_COVER_IMAGE = new c("EXPLORE_COVER_IMAGE", 18);
    public static final c EXPLORE_ARTICLE = new c("EXPLORE_ARTICLE", 19);
    public static final c NEWS_HUB_FEED = new c("NEWS_HUB_FEED", 20);
    public static final c NEWS_HUB_DETAIL = new c("NEWS_HUB_DETAIL", 21);
    public static final c BOARD_INVITE_NOTIFICATION = new c("BOARD_INVITE_NOTIFICATION", 22);
    public static final c BOARD_INVITE_NOTIFICATION_EXTRA = new c("BOARD_INVITE_NOTIFICATION_EXTRA", 23);
    public static final c BOARD_VIEW = new c("BOARD_VIEW", 24);
    public static final c CONVERSATION_FEED = new c("CONVERSATION_FEED", 25);
    public static final c CONVERSATION_MESSAGE_FEED = new c("CONVERSATION_MESSAGE_FEED", 26);
    public static final c CONVERSATION_MESSAGE_FEED_WITH_THREADS = new c("CONVERSATION_MESSAGE_FEED_WITH_THREADS", 27);
    public static final c SEARCH_PIN_FEED = new c("SEARCH_PIN_FEED", 28);
    public static final c PIN_EDIT_ADD = new c("PIN_EDIT_ADD", 29);
    public static final c DID_IT_EDIT_ADD = new c("DID_IT_EDIT_ADD", 30);
    public static final c PIN_CLOSEUP = new c("PIN_CLOSEUP", 31);
    public static final c PIN_CLOSEUP_AD_PREVIEW = new c("PIN_CLOSEUP_AD_PREVIEW", 32);
    public static final c BOARD_PIN_FEED = new c("BOARD_PIN_FEED", 33);
    public static final c LIBRARY_BOARD_FEED = new c("LIBRARY_BOARD_FEED", 34);
    public static final c LIBRARY_BOARD_FEED_WITH_CREATOR_ATTRIBUTION_AND_BOARD_PIN_COUNT = new c("LIBRARY_BOARD_FEED_WITH_CREATOR_ATTRIBUTION_AND_BOARD_PIN_COUNT", 35);
    public static final c LIBRARY_SHOWCASE = new c("LIBRARY_SHOWCASE", 36);
    public static final c SEND_SHARE_CONTACT = new c("SEND_SHARE_CONTACT", 37);
    public static final c CONTACT_REQUEST = new c("CONTACT_REQUEST", 38);
    public static final c DEFAULT_PIN_FEED = new c("DEFAULT_PIN_FEED", 39);
    public static final c PIN_PUSH_NOTIFICATION = new c("PIN_PUSH_NOTIFICATION", 40);
    public static final c HOMEFEED_BUILDER_INTERESTS_FEED = new c("HOMEFEED_BUILDER_INTERESTS_FEED", 41);
    public static final c DID_IT_CAROUSEL = new c("DID_IT_CAROUSEL", 42);
    public static final c SHOP_SECTION_COLLECTIONS = new c("SHOP_SECTION_COLLECTIONS", 43);
    public static final c SHOP_SECTION = new c("SHOP_SECTION", 44);
    public static final c SHOP_RECOMMENDATIONS = new c("SHOP_RECOMMENDATIONS", 45);
    public static final c MERCHANT_META_DATA = new c("MERCHANT_META_DATA", 46);
    public static final c BASE_PIN_FEED = new c("BASE_PIN_FEED", 47);
    public static final c LIBRARY_USER_FEED = new c("LIBRARY_USER_FEED", 48);
    public static final c PIN_MINI_CELL_FIELDS = new c("PIN_MINI_CELL_FIELDS", 49);
    public static final c NUX_INTEREST_FEED_DEFAULT = new c("NUX_INTEREST_FEED_DEFAULT", 50);
    public static final c RELATED_PIN_FIELDS = new c("RELATED_PIN_FIELDS", 51);
    public static final c PIN_BASE_FIELDS = new c("PIN_BASE_FIELDS", 52);
    public static final c AGGREGATED_COMMENT_FIELDS = new c("AGGREGATED_COMMENT_FIELDS", 53);
    public static final c AGGREGATED_COMMENT_REPLY_FIELDS = new c("AGGREGATED_COMMENT_REPLY_FIELDS", 54);
    public static final c BOARD_SECTION_DETAILED = new c("BOARD_SECTION_DETAILED", 55);
    public static final c BOARD_SECTION_SUMMARY = new c("BOARD_SECTION_SUMMARY", 56);
    public static final c BUBBLE_ARTICLE = new c("BUBBLE_ARTICLE", 57);
    public static final c BOARD_SECTION_PIN_JOIN = new c("BOARD_SECTION_PIN_JOIN", 58);
    public static final c SEARCH_PERSONAL_RETRIEVAL = new c("SEARCH_PERSONAL_RETRIEVAL", 59);
    public static final c FOLLOW_RECOMMENDATIONS = new c("FOLLOW_RECOMMENDATIONS", 60);
    public static final c BOARD_BULK_ACTION = new c("BOARD_BULK_ACTION", 61);
    public static final c REPINNED_BOARDS = new c("REPINNED_BOARDS", 62);
    public static final c BOARD_WITH_BULK_ACTION = new c("BOARD_WITH_BULK_ACTION", 63);
    public static final c USER_REACTION = new c("USER_REACTION", 64);
    public static final c BOARD_NEW_IDEAS = new c("BOARD_NEW_IDEAS", 65);
    public static final c BOARD_SECTION_PIN_FEED = new c("BOARD_SECTION_PIN_FEED", 66);
    public static final c PIN_STATS_PIN_FEED = new c("PIN_STATS_PIN_FEED", 67);
    public static final c PIN_STATS_PIN_FEED_WITH_BOARD_SECTION = new c("PIN_STATS_PIN_FEED_WITH_BOARD_SECTION", 68);
    public static final c PIN_STATS_DETAILS_FIELDS = new c("PIN_STATS_DETAILS_FIELDS", 69);
    public static final c IDEAS_CARD_FEED_METADATA = new c("IDEAS_CARD_FEED_METADATA", 70);
    public static final c STORY_PIN_DATA = new c("STORY_PIN_DATA", 71);
    public static final c BOARD_ORGANIZE = new c("BOARD_ORGANIZE", 72);
    public static final c TAGGED_CONTENT_PIN_BASE_FIELDS = new c("TAGGED_CONTENT_PIN_BASE_FIELDS", 73);
    public static final c PRODUCT_GROUP = new c("PRODUCT_GROUP", 74);
    public static final c HOMEFEED_TAB_SETTINGS_FIELDS = new c("HOMEFEED_TAB_SETTINGS_FIELDS", 75);
    public static final c SHOPPING_CLOSEUP_MODULE_FIELDS = new c("SHOPPING_CLOSEUP_MODULE_FIELDS", 76);
    public static final c HOMEFEED_TUNER_BOARD_RECOMMENDATIONS_FIELDS = new c("HOMEFEED_TUNER_BOARD_RECOMMENDATIONS_FIELDS", 77);
    public static final c HOMEFEED_TUNER_PIN_ACTIVITY_FIELDS = new c("HOMEFEED_TUNER_PIN_ACTIVITY_FIELDS", 78);
    public static final c USER_AVATAR_FIELDS = new c("USER_AVATAR_FIELDS", 79);
    public static final c USER_FOLLOW_FIELDS = new c("USER_FOLLOW_FIELDS", 80);
    public static final c PIN_REACTION_FIELDS = new c("PIN_REACTION_FIELDS", 81);
    public static final c ACCOUNT_SETTINGS = new c("ACCOUNT_SETTINGS", 82);
    public static final c MESSAGE_SETTINGS = new c("MESSAGE_SETTINGS", 83);
    public static final c EDIT_PROFILE = new c("EDIT_PROFILE", 84);
    public static final c VIRTUAL_TRY_ON = new c("VIRTUAL_TRY_ON", 85);
    public static final c SEARCH_USER_FEED = new c("SEARCH_USER_FEED", 86);
    public static final c SHOPPING_FULL_FEED_FIELDS = new c("SHOPPING_FULL_FEED_FIELDS", 87);
    public static final c VIRTUAL_TRY_ON_SHOPPING_CLOSEUP_MODULE_FIELDS = new c("VIRTUAL_TRY_ON_SHOPPING_CLOSEUP_MODULE_FIELDS", 88);
    public static final c TODAY_ARTICLE_DEFAULT = new c("TODAY_ARTICLE_DEFAULT", 89);
    public static final c BOARD_EDIT = new c("BOARD_EDIT", 90);
    public static final c EXPLORE_ARTICLE_BASE = new c("EXPLORE_ARTICLE_BASE", 91);
    public static final c UNIFIED_FLASHLIGHT_SHOPPING_FIELDS = new c("UNIFIED_FLASHLIGHT_SHOPPING_FIELDS", 92);
    public static final c UNIFIED_COMMENTS_PREVIEW_FIELDS = new c("UNIFIED_COMMENTS_PREVIEW_FIELDS", 93);
    public static final c UNIFIED_COMMENTS_FIELDS = new c("UNIFIED_COMMENTS_FIELDS", 94);
    public static final c RESPONSE_FIELDS = new c("RESPONSE_FIELDS", 95);
    public static final c TODAY_ARTICLE_FEED_FIELDS = new c("TODAY_ARTICLE_FEED_FIELDS", 96);
    public static final c STORY_PIN_DISPLAY_FIELDS = new c("STORY_PIN_DISPLAY_FIELDS", 97);
    public static final c USER_AVATAR_FIELDS_PRODUCT_DETAIL_PAGE = new c("USER_AVATAR_FIELDS_PRODUCT_DETAIL_PAGE", 98);
    public static final c USER_BUSINESSES = new c("USER_BUSINESSES", 99);
    public static final c ADS_QUIZ_PIN = new c("ADS_QUIZ_PIN", 100);
    public static final c STL_TAGGED_PRODUCT_FIELDS = new c("STL_TAGGED_PRODUCT_FIELDS", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_HAIR_PATTERN_QUERIES_MODULE);
    public static final c COMPLETE_PROFILE = new c("COMPLETE_PROFILE", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_SHOPPING_MODULE);
    public static final c USER_PROFILE_WITH_HAS_QUICK_CREATE_BOARD = new c("USER_PROFILE_WITH_HAS_QUICK_CREATE_BOARD", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_TEMPLATE_DETAILS_MODULE);
    public static final c PIN_NOTE_FIELDS = new c("PIN_NOTE_FIELDS", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_PEAR_STYLES_MODULE);
    public static final c PROFILE_HIGHLIGHT_FIELDS = new c("PROFILE_HIGHLIGHT_FIELDS", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_SEE_IT_STYLED_MODULE);
    public static final c PROFILE_ALL_PINS_FIELDS = new c("PROFILE_ALL_PINS_FIELDS", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_PLACEHOLDER_LOADING_GRID);
    public static final c PROFILE_ALL_MY_PINS_FIELDS = new c("PROFILE_ALL_MY_PINS_FIELDS", RecyclerViewTypes.VIEW_TYPE_PIN_PDP_MONOLITH_HEADER);
    public static final c STORY_PIN_AUDIO_FIELDS = new c("STORY_PIN_AUDIO_FIELDS", RecyclerViewTypes.VIEW_TYPE_PIN_CLOSEUP_STL_SHOPPING_MODULE);
    public static final c STORY_PIN_AUDIO_TAG_FIELDS = new c("STORY_PIN_AUDIO_TAG_FIELDS", RecyclerViewTypes.VIEW_TYPE_LIVE_SINGLE_COLUMN_UPSELL);
    public static final c CONVERSATION_GIF_REACTION_FIELDS = new c("CONVERSATION_GIF_REACTION_FIELDS", RecyclerViewTypes.VIEW_TYPE_TV_CATEGORY_PICKER_CAROUSEL);
    public static final c USER_NUX_CREATOR = new c("USER_NUX_CREATOR", RecyclerViewTypes.VIEW_TYPE_TV_SCHEDULE_EPISODE);
    public static final c SUGGESTED_CREATORS = new c("SUGGESTED_CREATORS", RecyclerViewTypes.VIEW_TYPE_TV_CATEGORY_PAGE_HEADER);
    public static final c BOARD_ORGANIZE_OPTIONS_FIELDS = new c("BOARD_ORGANIZE_OPTIONS_FIELDS", RecyclerViewTypes.VIEW_TYPE_SCHEDULED_PIN_CELL);
    public static final c BOARD_REPIN_SUGGESTIONS_FIELDS = new c("BOARD_REPIN_SUGGESTIONS_FIELDS", RecyclerViewTypes.VIEW_TYPE_SCHEDULED_PIN_SECTION_HEADER);
    public static final c STORY_PINS_PRODUCT_FEED_FIELDS = new c("STORY_PINS_PRODUCT_FEED_FIELDS", RecyclerViewTypes.VIEW_TYPE_ANNOUNCEMENT_MODAL_TYPE_ONE);
    public static final c SEARCH_LANDING_FEED_FIELDS = new c("SEARCH_LANDING_FEED_FIELDS", RecyclerViewTypes.VIEW_TYPE_PROFILE_CREATED_TAB_SCHEDULED_PINS_PREVIEW);
    public static final c BOARD_WISHLIST_FILTER = new c("BOARD_WISHLIST_FILTER", RecyclerViewTypes.VIEW_TYPE_CAROUSEL_SINGLE_COLUMN);
    public static final c DISCOVER_CREATORS_PICKER_FIELDS = new c("DISCOVER_CREATORS_PICKER_FIELDS", RecyclerViewTypes.VIEW_TYPE_SIMPLE_IMAGE_CELL);
    public static final c ENGAGEMENT_TAB_DETAILS_FIELDS = new c("ENGAGEMENT_TAB_DETAILS_FIELDS", RecyclerViewTypes.VIEW_TYPE_CAROUSEL_VIDEO_CELL);
    public static final c ENGAGEMENT_TAB_FIELDS = new c("ENGAGEMENT_TAB_FIELDS", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_GRID_CELL);
    public static final c ENGAGEMENT_TAB_TRY_FIELDS = new c("ENGAGEMENT_TAB_TRY_FIELDS", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_VIDEO_GRID_CELL);
    public static final c FLOATING_AGGREGATED_COMMENT_FIELDS = new c("FLOATING_AGGREGATED_COMMENT_FIELDS", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_VIDEO_GRID_CELL_FULL_SPAN);
    public static final c REPORT_FLOW_FIELDS = new c("REPORT_FLOW_FIELDS", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SHARE_PIN_CAROUSEL);
    public static final c USER_HAS_CONFIRMED_EMAIL_FIELDS = new c("USER_HAS_CONFIRMED_EMAIL_FIELDS", RecyclerViewTypes.VIEW_TYPE_STORY_BOARD_IDEAS_PREVIEW_FOOTER);
    public static final c IDEA_PIN_RELATED_CONTENT_FIELDS = new c("IDEA_PIN_RELATED_CONTENT_FIELDS", RecyclerViewTypes.VIEW_TYPE_STORY_BOARD_IDEAS_PREVIEW_DETAILED);
    public static final c IDEA_PIN_CREATE_FIELDS = new c("IDEA_PIN_CREATE_FIELDS", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_GRID_CELL);
    public static final c USER_BOARDS_MANAGE_VISIBILITY_FIELDS = new c("USER_BOARDS_MANAGE_VISIBILITY_FIELDS", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK);
    public static final c PIN_DEEPLINK = new c("PIN_DEEPLINK", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK_FULL_SPAN);
    public static final c BOARD_METADATA_FIELDS = new c("BOARD_METADATA_FIELDS", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK_SHOW_GRID_ACTIONS);
    public static final c IDEA_PIN_LOCATION_FIELDS = new c("IDEA_PIN_LOCATION_FIELDS", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_FEEDBACK_SHOW_GRID_ACTIONS_FULL_SPAN);
    public static final c SEARCH_BOARD_FEED = new c("SEARCH_BOARD_FEED", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_PIN_VIDEO_GRID_CELL);
    public static final c SHOP_SEARCH_PIN_FEED = new c("SHOP_SEARCH_PIN_FEED", RecyclerViewTypes.VIEW_TYPE_FEED_SECTION_TITLE);
    public static final c USER_OPTED_IN_TO_PAID_PARTNERSHIPS_FIELDS = new c("USER_OPTED_IN_TO_PAID_PARTNERSHIPS_FIELDS", RecyclerViewTypes.VIEW_TYPE_PIN_CAROUSEL);
    public static final c USER_ANALYTICS_GRAPH = new c("USER_ANALYTICS_GRAPH", RecyclerViewTypes.VIEW_TYPE_PIN_MINI_CELL);
    public static final c SCHEDULED_PIN_PREVIEW = new c("SCHEDULED_PIN_PREVIEW", RecyclerViewTypes.VIEW_TYPE_FIXED_SIZE_PIN_CELL);
    public static final c SCHEDULED_PIN_FEED = new c("SCHEDULED_PIN_FEED", RecyclerViewTypes.VIEW_TYPE_SEE_MORE_ACTION_CELL);
    public static final c STRUCTURED_FEED_FIELDS = new c("STRUCTURED_FEED_FIELDS", RecyclerViewTypes.VIEW_TYPE_FIXED_SIZE_PIN_IMAGE);
    public static final c BOARD_PEAR_INSIGHTS = new c("BOARD_PEAR_INSIGHTS", RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL);
    public static final c PEAR_CLOSEUP_HEADER = new c("PEAR_CLOSEUP_HEADER", RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL_ITEM);
    public static final c PEAR_STYLE_HEADER = new c("PEAR_STYLE_HEADER", RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL_ACTION_ITEM);
    public static final c PEAR_INSIGHT_TOPIC = new c("PEAR_INSIGHT_TOPIC", RecyclerViewTypes.VIEW_TYPE_VIDEO_CAROUSEL_ITEM_HIDDEN);
    public static final c PEAR_QUIZ_V2 = new c("PEAR_QUIZ_V2", RecyclerViewTypes.VIEW_TYPE_ARTICLE_CAROUSEL);
    public static final c PEAR_QUIZ_OUTPUT_V2 = new c("PEAR_QUIZ_OUTPUT_V2", RecyclerViewTypes.VIEW_TYPE_ARTICLE_CAROUSEL_ITEM_IMAGE);
    public static final c PEAR_QUIZ_OUTPUT_SECTIONS_V2 = new c("PEAR_QUIZ_OUTPUT_SECTIONS_V2", RecyclerViewTypes.VIEW_TYPE_VTO_CAROUSEL_ITEM);
    public static final c IDEA_PIN_BOARD_STICKER_PICKER = new c("IDEA_PIN_BOARD_STICKER_PICKER", RecyclerViewTypes.VIEW_TYPE_VTO_CAROUSEL_ITEM_TINTED);
    public static final c COLLAGE_RETRIEVAL_FEED = new c("COLLAGE_RETRIEVAL_FEED", RecyclerViewTypes.VIEW_TYPE_ARTICLE_CAROUSEL_ITEM_VIDEO);
    public static final c COLLAGE_COMPOSER_BROWSE_FEED = new c("COLLAGE_COMPOSER_BROWSE_FEED", RecyclerViewTypes.VIEW_TYPE_SEARCH_PRODUCT_COLLAGE_STORY);
    public static final c COLLAGE_REMIX_FEED = new c("COLLAGE_REMIX_FEED", RecyclerViewTypes.VIEW_TYPE_SHOPPING_BUBBLES_PACKAGE_GRID_MODULE);
    public static final c COLLAGE_CUTOUT_CLOSEUP_FEED = new c("COLLAGE_CUTOUT_CLOSEUP_FEED", RecyclerViewTypes.VIEW_TYPE_SHOPPING_BRAND_PACKAGE_GRID_MODULE);
    public static final c COLLAGE_PREVIEW = new c("COLLAGE_PREVIEW", RecyclerViewTypes.VIEW_TYPE_SHOPPING_CATEGORY);
    public static final c MORE_BOARDS_FIELDS = new c("MORE_BOARDS_FIELDS", RecyclerViewTypes.VIEW_TYPE_SHOPPING_UNIFIED_FILTER_MULTI_SELECT_ITEM);
    public static final c PIN_SELECTION_SHEET = new c("PIN_SELECTION_SHEET", RecyclerViewTypes.VIEW_TYPE_SHOPPING_PRICE_FILTER_ITEM);
    public static final c BOARD_DETAIL_PIN_FEED = new c("BOARD_DETAIL_PIN_FEED", RecyclerViewTypes.VIEW_TYPE_STANDARD_FILTER_ITEM);
    public static final c BOARD_SECTION_DETAIL_PIN_FEED = new c("BOARD_SECTION_DETAIL_PIN_FEED", RecyclerViewTypes.VIEW_TYPE_SHOPPING_PRODUCT_FILTER_HEADER);
    public static final c BOARD_HEADER_IMAGE_SELECTOR_FEED = new c("BOARD_HEADER_IMAGE_SELECTOR_FEED", RecyclerViewTypes.VIEW_TYPE_SHOPPING_COLOR_FILTER);
    public static final c NUX_USE_CASE = new c("NUX_USE_CASE", RecyclerViewTypes.VIEW_TYPE_SHOPPING_CATEGORY_FILTER_ITEM);
    public static final c NUX_USE_CASE_FEED = new c("NUX_USE_CASE_FEED", RecyclerViewTypes.VIEW_TYPE_SHOPPING_SORT_FILTER);
    public static final c AUTO_MAGICAL_BOARD_VIEW = new c("AUTO_MAGICAL_BOARD_VIEW", RecyclerViewTypes.VIEW_TYPE_STELA_IN_FLASHLIGHT_ONE_COLUMN);
    public static final c WAISTA_GEN_AI = new c("WAISTA_GEN_AI", RecyclerViewTypes.VIEW_TYPE_ONE_TAP_SAVE_EDUCATION_HEADER);
    public static final c INSTAGRAM_CONNECT = new c("INSTAGRAM_CONNECT", 160);

    private static final /* synthetic */ c[] $values() {
        return new c[]{INVALID, DYNAMIC_GRID_FEED, DYNAMIC_GRID_FEED_WITH_BOARD_FIELDS, USER_ME, DEFAULT_USER_FEED, USER_PROFILE, DEFAULT_BOARD_FEED, DEFAULT_BOARD_FEED_LARGE_THUMBNAILS, BOARD_PICKER_FRAGMENT, BOARD_INVITES_DETAILS, BOARD_RELATED_FEED, INTEREST_FEED_DEFAULT, INTEREST_FOLLOWED_FEED, USECASE_DEFAULT, DID_IT_MODEL, PIN_CLOSEUP_SCREENSHOT, CONTEXTUAL_EXPLORE, EXPLORE_ARTICLE_COVER, EXPLORE_COVER_IMAGE, EXPLORE_ARTICLE, NEWS_HUB_FEED, NEWS_HUB_DETAIL, BOARD_INVITE_NOTIFICATION, BOARD_INVITE_NOTIFICATION_EXTRA, BOARD_VIEW, CONVERSATION_FEED, CONVERSATION_MESSAGE_FEED, CONVERSATION_MESSAGE_FEED_WITH_THREADS, SEARCH_PIN_FEED, PIN_EDIT_ADD, DID_IT_EDIT_ADD, PIN_CLOSEUP, PIN_CLOSEUP_AD_PREVIEW, BOARD_PIN_FEED, LIBRARY_BOARD_FEED, LIBRARY_BOARD_FEED_WITH_CREATOR_ATTRIBUTION_AND_BOARD_PIN_COUNT, LIBRARY_SHOWCASE, SEND_SHARE_CONTACT, CONTACT_REQUEST, DEFAULT_PIN_FEED, PIN_PUSH_NOTIFICATION, HOMEFEED_BUILDER_INTERESTS_FEED, DID_IT_CAROUSEL, SHOP_SECTION_COLLECTIONS, SHOP_SECTION, SHOP_RECOMMENDATIONS, MERCHANT_META_DATA, BASE_PIN_FEED, LIBRARY_USER_FEED, PIN_MINI_CELL_FIELDS, NUX_INTEREST_FEED_DEFAULT, RELATED_PIN_FIELDS, PIN_BASE_FIELDS, AGGREGATED_COMMENT_FIELDS, AGGREGATED_COMMENT_REPLY_FIELDS, BOARD_SECTION_DETAILED, BOARD_SECTION_SUMMARY, BUBBLE_ARTICLE, BOARD_SECTION_PIN_JOIN, SEARCH_PERSONAL_RETRIEVAL, FOLLOW_RECOMMENDATIONS, BOARD_BULK_ACTION, REPINNED_BOARDS, BOARD_WITH_BULK_ACTION, USER_REACTION, BOARD_NEW_IDEAS, BOARD_SECTION_PIN_FEED, PIN_STATS_PIN_FEED, PIN_STATS_PIN_FEED_WITH_BOARD_SECTION, PIN_STATS_DETAILS_FIELDS, IDEAS_CARD_FEED_METADATA, STORY_PIN_DATA, BOARD_ORGANIZE, TAGGED_CONTENT_PIN_BASE_FIELDS, PRODUCT_GROUP, HOMEFEED_TAB_SETTINGS_FIELDS, SHOPPING_CLOSEUP_MODULE_FIELDS, HOMEFEED_TUNER_BOARD_RECOMMENDATIONS_FIELDS, HOMEFEED_TUNER_PIN_ACTIVITY_FIELDS, USER_AVATAR_FIELDS, USER_FOLLOW_FIELDS, PIN_REACTION_FIELDS, ACCOUNT_SETTINGS, MESSAGE_SETTINGS, EDIT_PROFILE, VIRTUAL_TRY_ON, SEARCH_USER_FEED, SHOPPING_FULL_FEED_FIELDS, VIRTUAL_TRY_ON_SHOPPING_CLOSEUP_MODULE_FIELDS, TODAY_ARTICLE_DEFAULT, BOARD_EDIT, EXPLORE_ARTICLE_BASE, UNIFIED_FLASHLIGHT_SHOPPING_FIELDS, UNIFIED_COMMENTS_PREVIEW_FIELDS, UNIFIED_COMMENTS_FIELDS, RESPONSE_FIELDS, TODAY_ARTICLE_FEED_FIELDS, STORY_PIN_DISPLAY_FIELDS, USER_AVATAR_FIELDS_PRODUCT_DETAIL_PAGE, USER_BUSINESSES, ADS_QUIZ_PIN, STL_TAGGED_PRODUCT_FIELDS, COMPLETE_PROFILE, USER_PROFILE_WITH_HAS_QUICK_CREATE_BOARD, PIN_NOTE_FIELDS, PROFILE_HIGHLIGHT_FIELDS, PROFILE_ALL_PINS_FIELDS, PROFILE_ALL_MY_PINS_FIELDS, STORY_PIN_AUDIO_FIELDS, STORY_PIN_AUDIO_TAG_FIELDS, CONVERSATION_GIF_REACTION_FIELDS, USER_NUX_CREATOR, SUGGESTED_CREATORS, BOARD_ORGANIZE_OPTIONS_FIELDS, BOARD_REPIN_SUGGESTIONS_FIELDS, STORY_PINS_PRODUCT_FEED_FIELDS, SEARCH_LANDING_FEED_FIELDS, BOARD_WISHLIST_FILTER, DISCOVER_CREATORS_PICKER_FIELDS, ENGAGEMENT_TAB_DETAILS_FIELDS, ENGAGEMENT_TAB_FIELDS, ENGAGEMENT_TAB_TRY_FIELDS, FLOATING_AGGREGATED_COMMENT_FIELDS, REPORT_FLOW_FIELDS, USER_HAS_CONFIRMED_EMAIL_FIELDS, IDEA_PIN_RELATED_CONTENT_FIELDS, IDEA_PIN_CREATE_FIELDS, USER_BOARDS_MANAGE_VISIBILITY_FIELDS, PIN_DEEPLINK, BOARD_METADATA_FIELDS, IDEA_PIN_LOCATION_FIELDS, SEARCH_BOARD_FEED, SHOP_SEARCH_PIN_FEED, USER_OPTED_IN_TO_PAID_PARTNERSHIPS_FIELDS, USER_ANALYTICS_GRAPH, SCHEDULED_PIN_PREVIEW, SCHEDULED_PIN_FEED, STRUCTURED_FEED_FIELDS, BOARD_PEAR_INSIGHTS, PEAR_CLOSEUP_HEADER, PEAR_STYLE_HEADER, PEAR_INSIGHT_TOPIC, PEAR_QUIZ_V2, PEAR_QUIZ_OUTPUT_V2, PEAR_QUIZ_OUTPUT_SECTIONS_V2, IDEA_PIN_BOARD_STICKER_PICKER, COLLAGE_RETRIEVAL_FEED, COLLAGE_COMPOSER_BROWSE_FEED, COLLAGE_REMIX_FEED, COLLAGE_CUTOUT_CLOSEUP_FEED, COLLAGE_PREVIEW, MORE_BOARDS_FIELDS, PIN_SELECTION_SHEET, BOARD_DETAIL_PIN_FEED, BOARD_SECTION_DETAIL_PIN_FEED, BOARD_HEADER_IMAGE_SELECTOR_FEED, NUX_USE_CASE, NUX_USE_CASE_FEED, AUTO_MAGICAL_BOARD_VIEW, WAISTA_GEN_AI, INSTAGRAM_CONNECT};
    }

    static {
        c[] $values = $values();
        $VALUES = $values;
        $ENTRIES = l0.b0($values);
    }

    private c(String str, int i13) {
    }

    @NotNull
    public static el2.a getEntries() {
        return $ENTRIES;
    }

    public static c valueOf(String str) {
        return (c) Enum.valueOf(c.class, str);
    }

    public static c[] values() {
        return (c[]) $VALUES.clone();
    }
}
